### ISSUE TITLE
ImportError: Library "c" not found.

### ISSUE THREAD

**Issue by KONPEITO1205** [pyglet/pyglet#100]
Hello everyone.

OS : Ubuntu 18.04
GPU : GTX 1080
CUDA Version : 10.01
Driver Version : 430.50
Python version : 3.7.3
pyglet version : 1.3.2

> $  glxinfo | grep "version string"
server glx version string: 1.4
client glx version string: 1.4
OpenGL core profile version string: 4.6.0 NVIDIA 430.50
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 430.50
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 430.50
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

I got error below.

> Traceback (most recent call last):
  File "/home/tkr/python_lib/gym/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 16, in <module>
    from pyglet.app.xlib import XlibSelectDevice
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/app/__init__.py", line 175, in <module>
    event_loop = EventLoop()
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/app/base.py", line 119, in __init__
    self.clock = clock.get_default()
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/clock.py", line 169, in <module>
    _c = pyglet.lib.load_library('c')
  File "/home/tkr/anaconda3/lib/python3.7/site-packages/pyglet/lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "c" not found.

How do I solve this error?

I can run this line without error.
> from pyglet.gl import *

**Comment by takeru1205** [comment]
I could run by append below line to bashrc file.

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu/libc.so.6

**Comment by KONPEITO1205** [comment]
If I load c library on python there's no error.
> import pyglet
> library = pyglet.lib.load_library('c')
> print(library)
<CDLL 'libc.so.6', handle 7fd9e7b631f0 at 0x7fd9e4ce94e0>

And also I run other check, but no error

> from pyglet.lib import LinuxLibraryLoader
lib = LinuxLibraryLoader()
lib.find_library('c')
>> 'libc.so.6'

**Comment by benmoran56** [comment]
Could you try this again with your system Python (not through Anaconda), and see if that works? 

In addition, give it a try with the latest pyglet release. 1.3.2 is fairly old, and there have been a lot of bug fixes since then (including library loading).

**Comment by KONPEITO1205** [comment]
Thank you benmoran56.

Actually, I ran my code with OpenAI Gym environment.
If I made instance before make agent, it was no error.

So, maybe it was my mistake. Sorry, and thank you.
