### ISSUE TITLE
Error when trying to use pyglet.image.Framebuffer objects 

### ISSUE THREAD

**Issue by kingadami** [pyglet/pyglet#1020]
The pyglet/image/buffer.py file is missing an import pyglet line at the top causing an error when trying to use the Framebuffer object.

The following code reproduces the error:

```
#!/usr/bin/env python3

import pyglet
import math

class Board(pyglet.window.Window):
    def __init__(self):
        super().__init__(caption="Window")

        self.image = pyglet.image.create(self.size[0],self.size[1])
        self.buffer = pyglet.image.Framebuffer()
        self.buffer.attach_texture(self.image.get_texture())

        label = pyglet.text.Label("Hello World", font_name="Times New Roman", font_size=36, x=self.size[0]//2, y=self.size[1]//2, anchor_x="center", anchor_y="center")

        # Draw to our image
        self.buffer.bind()
        label.draw()
        pyglet.shapes.Line(0,0,self.image.width,self.image.height,10).draw()
        self.buffer.unbind()

        self.sprite = pyglet.sprite.Sprite(img=self.image)

    def on_draw(self):
        self.clear()
        self.sprite.draw()

if __name__ == "__main__":
    board = Board()
    pyglet.app.run()
```
It produces the following error:
```
Traceback (most recent call last):
  File "./test.py", line 28, in <module>
    board = Board()
  File "./test.py", line 11, in __init__
    self.buffer = pyglet.image.Framebuffer()
  File "/home/adam/.local/lib/python3.8/site-packages/pyglet-2.0.10-py3.8.egg/pyglet/image/buffer.py",
 line 77, in __init__
NameError: name 'pyglet' is not defined
Exception ignored in: <function Framebuffer.__del__ at 0x7f5a3b3f45e0>
Traceback (most recent call last):
  File "/home/adam/.local/lib/python3.8/site-packages/pyglet-2.0.10-py3.8.egg/pyglet/image/buffer.py",
 line 116, in __del__
AttributeError: 'Framebuffer' object has no attribute '_id'
```
It can be fixed by just adding the line `import pyglet` to the top of the file buffer.py

Currently broken on commit [e48bc0c](https://github.com/pyglet/pyglet/commit/e48bc0cd740e3b7df4a275399fe25578a6d626cd) in the master branch.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. I just fixed this in the master branch.
