### ISSUE TITLE
persisting xlib issue

### ISSUE THREAD

**Issue by aryzach** [pyglet/pyglet#1024]
[Old issue persists](https://github.com/pyglet/pyglet/issues/520)- marked partially fixed in [2.0.10 release](https://github.com/pyglet/pyglet/releases/tag/v2.0.10)

```
import locale
import pyglet


print("Locale:", locale.getlocale())
print("_have_utf8 check:", locale.getlocale()[1] == 'UTF-8')
print("_have_utf8 real :", pyglet.window.xlib._have_utf8)

pyglet.window.Window()
```

produces:

```
Locale: ('en_US', 'UTF-8')
_have_utf8 check: True
Traceback (most recent call last):
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/__init__.py", line 315, in __getattr__
    return getattr(self._module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'xlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neurofit/projects/testpyglet.py", line 7, in <module>
    print("_have_utf8 real :", pyglet.window.xlib._have_utf8)
                               ^^^^^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/__init__.py", line 321, in __getattr__
    __import__(import_name)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 578, in __init__
    self._create()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 369, in _create
    self.set_caption(self._caption)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 529, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 904, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property
```

`python -m pyglet.info` produces:

```Platform
------------------------------------------------------------------------------
platform:  Linux-5.10.104-tegra-aarch64-with-glibc2.31
release:   5.10.104-tegra
machine:   aarch64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 11:57:02) [GCC 12.3.0]
sys.maxint: 9223372036854775807
os.getcwd(): /home/neurofit/projects

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.10
pyglet.compat_platform: linux
pyglet.__file__: /home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 178, in _try_dump
    func()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 62, in dump_window
    from pyglet.gl import gl_info
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 578, in __init__
    self._create()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 369, in _create
    self.set_caption(self._caption)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 529, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 904, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 178, in _try_dump
    func()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 125, in dump_media
    import pyglet.media
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/player.py", line 8, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 578, in __init__
    self._create()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 255, in _create
    self.context.attach(self.canvas)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 188, in attach
    self.set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 192, in set_current
    super().set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/base.py", line 281, in set_current
    self._info.set_active_context()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/gl_info.py", line 72, in set_active_context
    self.vendor = asstr(cast(glGetString(GL_VENDOR), c_char_p).value)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/lib.py", line 66, in errcheck
    raise GLException('No GL context; create a Window first')
pyglet.gl.lib.GLException: No GL context; create a Window first

pyglet.media.ffmpeg
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 178, in _try_dump
    func()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/info.py", line 133, in dump_ffmpeg
    import pyglet.media
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/player.py", line 8, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 578, in __init__
    self._create()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 255, in _create
    self.context.attach(self.canvas)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 188, in attach
    self.set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 192, in set_current
    super().set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/base.py", line 281, in set_current
    self._info.set_active_context()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/gl_info.py", line 72, in set_active_context
    self.vendor = asstr(cast(glGetString(GL_VENDOR), c_char_p).value)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/lib.py", line 66, in errcheck
    raise GLException('No GL context; create a Window first')
pyglet.gl.lib.GLException: No GL context; create a Window first

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle aaaadefd2af0 at 0xffffa42b1f90>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
Exception ignored in atexit callback: <function _delete_audio_driver at 0xffffa421fc40>
Traceback (most recent call last):
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/drivers/__init__.py", line 79, in _delete_audio_driver
    from .. import Source
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/__init__.py", line 44, in <module>
    from .player import Player, PlayerGroup
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/media/player.py", line 8, in <module>
    from pyglet.gl import GL_TEXTURE_2D
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 191, in <module>
    import pyglet.window
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/__init__.py", line 578, in __init__
    self._create()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 255, in _create
    self.context.attach(self.canvas)
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 188, in attach
    self.set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 192, in set_current
    super().set_current()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/base.py", line 281, in set_current
    self._info.set_active_context()
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/gl_info.py", line 72, in set_active_context
    self.vendor = asstr(cast(glGetString(GL_VENDOR), c_char_p).value)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neurofit/miniforge3/envs/neuroFitONE/lib/python3.11/site-packages/pyglet/gl/lib.py", line 66, in errcheck
    raise GLException('No GL context; create a Window first')
pyglet.gl.lib.GLException: No GL context; create a Window first
AL lib: (EE) alc_cleanup: 2 devices not closed
```

**Comment by aryzach** [comment]
the fixes mentioned in the original issue [linked above and here](https://github.com/pyglet/pyglet/issues/520) don't fix it for me

**Comment by benmoran56** [comment]
What do the following commands give you? 
```sh
localectl
```
and 
```
localectl list-locales
```

**Comment by aryzach** [comment]
@benmoran56 

```
  System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
```

```
C.UTF-8
en_AG.UTF-8
en_AU.UTF-8
en_BW.UTF-8
en_CA.UTF-8
en_DK.UTF-8
en_GB.UTF-8
en_HK.UTF-8
en_IE.UTF-8
en_IL.UTF-8
en_IN.UTF-8
en_NG.UTF-8
en_NZ.UTF-8
en_PH.UTF-8
en_SG.UTF-8
en_US.UTF-8
en_ZA.UTF-8
en_ZM.UTF-8
en_ZW.UTF-8
```

**Comment by benmoran56** [comment]
Looks OK except for that unset VC Keymap. I'm not sure if an unset Virtual Console Keymap will cause any issues, but might be worth looking into. 

Basically pyglet is crashing while making this call to xlib: `xlib.Xutf8TextListToTextProperty`

I would try regenerating your locales (locale-gen) to see if that helps. If not, try manually forcing UTF8 support off in pyglet. This might work: 
```py
import pyglet

pyglet.options['shadow_window'] = False
pyglet.window.xlib._have_utf8 = False
```

**Comment by aryzach** [comment]
thanks. for now I solved by pulling in the dependency using conda's pip (compared to local version of the pyglet or conda directly)

**Comment by caffeinepills** [comment]
Closing as it looks like user solved his issue.
