### ISSUE TITLE
AssertionError: Font: 'calibri.ttf' not found in loaded or system font collection.

### ISSUE THREAD

**Issue by happyleibniz** [pyglet/pyglet#1041]
**Describe the bug**
It looks like the font file can't be loaded:
the font file is in the same dir but it can't be loaded
**System Information:**
windows11 ,AMD cpu,using pycharm pro,using venv,version 2.0.10

code snippet:
```
import pyglet
def GetFont(FontName, FontSize):
    pyglet.resource.add_font(FontName)
    font = pyglet.font.load(FontName, int(FontSize))
    return font
self.FONT1= GetFont("calibri.ttf", "20")
```
error code:
```
Traceback (most recent call last):
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\shell_startup.py", line 137, in <module>
    main()
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\shell_startup.py", line 134, in main
    computer.start()
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\shell_startup.py", line 128, in start
    pyglet.app.run(interval=0)
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\app\__init__.py", line 76, in run
    event_loop.run(interval)
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\app\base.py", line 163, in run
    timeout = self.idle()
              ^^^^^^^^^^^
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\app\base.py", line 224, in idle
    self.clock.call_scheduled_functions(dt)
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\clock.py", line 217, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\shell_startup.py", line 75, in update
    self.FONT1= GetFont("calibri.ttf", "20")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\Disk\__system\__internal\font_get.py", line 6, in GetFont
    font = pyglet.font.load(FontName, int(FontSize))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\font\__init__.py", line 190, in load
    font = _system_font_class(name, size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leibniz\Desktop\Documents\all python\pythonOS in pyglet\venv\Lib\site-packages\pyglet\font\directwrite.py", line 2049, in __init__
    assert self._collection is not None, f"Font: '{name}' not found in loaded or system font collection."
AssertionError: Font: 'calibri.ttf' not found in loaded or system font collection.
```

**Comment by benmoran56** [comment]
The font name is not the same as the file name.  The easiest way to confirm the name is to open the font in a font viewer/editor. There are some online ones as well.

**Comment by benmoran56** [comment]
Closing due to no reply, but please follow up if you still have questions.

**Comment by happyleibniz** [comment]
yup,thanks,it did go right
