### ISSUE TITLE
Circular import when debug trace

### ISSUE THREAD

**Issue by zhengxyz123** [pyglet/pyglet#1046]
When I run
```bash
PYGLET_DEBUG_TRACE=1 python ...
```

It raises
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/jason/Desktop/mystery/mystery/__init__.py", line 4, in <module>
    from pyglet import version as pyglet_ver
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/__init__.py", line 307, in <module>
    class _ModuleProxy:
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/__init__.py", line 307, in _ModuleProxy
    class _ModuleProxy:
    
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/__init__.py", line 307, in _ModuleProxy
    class _ModuleProxy:
    
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/__init__.py", line 277, in _trace_func
    _trace_frame(thread, frame, indent)
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/__init__.py", line 221, in _trace_frame
    from pyglet import lib
  File "/home/jason/Desktop/mystery/lib/python3.11/site-packages/pyglet/lib.py", line 21, in <module>
    script_path = pyglet.resource.get_script_home()
                  ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'pyglet' has no attribute 'resource' (most likely due to a circular import)
```

Maybe a circular import happened(in pyglet 2.0.10).

**Comment by benmoran56** [comment]
Can you try removing that import, and copying the `get_script_home` function directly into the lib module?

**Comment by zhengxyz123** [comment]
I have found an easier way by replacing this line

https://github.com/pyglet/pyglet/blob/74970f8eed8ecccfcba986f9f40540230977a9c2/pyglet/lib.py#L13

with
```python
13 import pyglet
14 import pyglet.resource
```

**Comment by benmoran56** [comment]
If you put `pyglet.options['debug_trace'] = True` in the top of your program, that _does_ work OK.

Your solution also works, but it lead me to the root issue: 
In `pyglet.__init__`, we are calling the `_install_trace()` function _**before**_ we set up the ModuleProxy code. That means the `pyglet.resource` module doesn't exist yet :sweat_smile:

I'll try to rearrange those.

**Comment by benmoran56** [comment]
Can you give it a try with the latest code in master?

**Comment by zhengxyz123** [comment]
There is no problem when I run
```bash
PYGLET_DEBUG_TRACE=1 python3
```
then `import pyglet`.

**Comment by benmoran56** [comment]
Great! Thanks for testing. We can close this I think. It will be in the next release (hopefully soon).
