### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context - when trying to create a window

### ISSUE THREAD

**Issue by Whiax** [pyglet/pyglet#1047]
**Describe the bug**

Hi, I'm coding on a remote computer and I have the following issue when I try to create a window in pyglet:
```
Traceback (most recent call last):
  File "main_pyglet.py", line 7, in <module>
    window = pyglet.window.Window()
             ^^^^^^^^^^^^^^^^^^^^
  File "/site-packages/pyglet/__init__.py", line 321, in __getattr__
    __import__(import_name)
  File "/site-packages/pyglet/window/__init__.py", line 1929, in <module>
    gl._create_shadow_window()
  File "/site-packages/pyglet/gl/__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
                     ^^^^^^^^^^^^^^
  File "/site-packages/pyglet/gl/__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/site-packages/pyglet/window/__init__.py", line 538, in __init__
    context = config.create_context(gl.current_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/site-packages/pyglet/gl/xlib.py", line 105, in create_context
    return XlibContext(self, share)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/site-packages/pyglet/gl/xlib.py", line 127, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```
The code works in pyglet 1.5.28 but doesn't in 2.0.

I guess the code is not the problem (import pyglet; window = pyglet.window.Window() ). I'm using a remote computer which doesn't have a display, which may be the main issue. It works with a remote desktop software and I have a standard GUI (xfce), all usual programs work with no issue. Perhaps there is a specific way to call openGL in this situation?
It seems this issue already existed: https://github.com/mmatl/pyrender/issues/13 , but nothing in there worked for me.

**System Information:**

Ubuntu 20.04 / RTX 2070 Super

> Platform
> ------------------------------------------------------------------------------
> platform:  Linux-5.4.0-65-generic-x86_64-with-glibc2.31
> release:   5.4.0-65-generic
> machine:   x86_64
> 
> Python
> ------------------------------------------------------------------------------
> implementation: CPython
> sys.version: 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0]
> sys.maxint: 9223372036854775807
> 
> pyglet
> ------------------------------------------------------------------------------
> pyglet.version: 2.0.10
> pyglet.compat_platform: linux
> pyglet.__file__: pyglet/__init__.py
> pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
> pyglet.options['debug_font'] = False
> pyglet.options['debug_gl'] = True
> pyglet.options['debug_gl_trace'] = False
> pyglet.options['debug_gl_trace_args'] = False
> pyglet.options['debug_gl_shaders'] = False
> pyglet.options['debug_graphics_batch'] = False
> pyglet.options['debug_lib'] = False
> pyglet.options['debug_media'] = False
> pyglet.options['debug_texture'] = False
> pyglet.options['debug_trace'] = False
> pyglet.options['debug_trace_args'] = False
> pyglet.options['debug_trace_depth'] = 1
> pyglet.options['debug_trace_flush'] = True
> pyglet.options['debug_win32'] = False
> pyglet.options['debug_input'] = False
> pyglet.options['debug_x11'] = False
> pyglet.options['shadow_window'] = True
> pyglet.options['vsync'] = None
> pyglet.options['xsync'] = True
> pyglet.options['xlib_fullscreen_override_redirect'] = False
> pyglet.options['search_local_libs'] = True
> pyglet.options['win32_gdi_font'] = False
> pyglet.options['headless'] = False
> pyglet.options['headless_device'] = 0
> pyglet.options['win32_disable_shaping'] = False
> pyglet.options['dw_legacy_naming'] = False
> pyglet.options['win32_disable_xinput'] = False
> pyglet.options['com_mta'] = False
> pyglet.options['osx_alt_loop'] = False

**Comment by benmoran56** [comment]
pyglet requires OpenGL 3.3+ since v2.0. You can check what's available in your remote context with: `glxinfo | grep OpenGL`. 
If OpenGL 3.3+ is not available for your hardware, _and_ you're using the MESA stack, you can force software rendering. For example:
```sh
LIBGL_ALWAYS_SOFTWARE=1 python -m pyglet.info
```

**Comment by benmoran56** [comment]
The output shows that you are already using the software renderer (`llvmpipe`). The latest versions of `llvmpipe` do support up to OpenGL 4.6, but I don't know about 21.2.6. It _should_ support at least GL 3.3, but it doesn't appear to on your system. 

Are you expecting your NVidia card to be used? If the glxinfo output is the same with or without the ALWAYS_SOFTWARE, then your NVidia driver isn't in use.

I'm not sure what to suggest at this point, but glxinfo is a good test point to see what drivers are being used.

**Comment by Whiax** [comment]
The output is the same with and without the flag. The driver and the nvidia card are used and do work with pytorch for example. I can use nvidia-smi, see vram usage, launch jobs on gpus etc. 

I guess I'm on a specific configuration, it's not easy to correctly install nvidia drivers for my needs (pytorch gpu, remote desktop, etc.) and for example "nvidia-settings" doesn't work in this situation so I guess it's a bit unstable. I know nvidia proprietary drivers can cause troubles in some situations but they are required for some of my work. I could try to update the driver but I can't do it just now. I can code with pyglet on another platform so it's not a big issue. 

If pyglet requires opengl 3.3+ and I don't have it, it's on me! Thanks for the support!

**Comment by caffeinepills** [comment]
Just to note, pyglet 2.x requires OpenGL 3.3+

Pyglet 1.5 can use the older OpenGL calls. Your best bet would be to try that.

I will close this for now, but if you have any questions, feel free to reach out.
