### ISSUE TITLE
AttributeError: dlsym(0x3c07d83b0, class_getMethodImplementation_stret): symbol not found

### ISSUE THREAD

**Issue by dickreuter** [pyglet/pyglet#1052]
self.viewer = PygletWindow(450,650) causes:

Traceback (most recent call last):
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dickr/dev/neuron_poker/main.py", line 255, in <module>
    command_line_parser()
  File "/Users/dickr/dev/neuron_poker/main.py", line 65, in command_line_parser
    runner.random_agents()
  File "/Users/dickr/dev/neuron_poker/main.py", line 112, in random_agents
    self.env.reset()
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dickr/dev/neuron_poker/gym_env/env.py", line 183, in reset
    self._get_environment()
  File "/Users/dickr/dev/neuron_poker/gym_env/env.py", line 298, in _get_environment
    self.render()
  File "/Users/dickr/dev/neuron_poker/gym_env/env.py", line 680, in render
    self.viewer = PygletWindow(screen_width + 50, screen_height + 50)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dickr/dev/neuron_poker/gym_env/rendering.py", line 23, in __init__
    self.display_surface = pyglet.window.Window(width=X, height=Y + 50)
                           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1888, in <module>
    from pyglet.window.cocoa import CocoaWindow as Window
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/window/cocoa/__init__.py", line 44, in <module>
    from pyglet.canvas.cocoa import CocoaCanvas
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/canvas/__init__.py", line 102, in <module>
    from pyglet.canvas.cocoa import CocoaDisplay as Display
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/canvas/cocoa.py", line 41, in <module>
    from pyglet.libs.darwin.cocoapy import CGDirectDisplayID, quartz, cf
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
    from .cocoapy import *
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 32, in <module>
    from .runtime import objc, send_message, send_super
  File "/Users/dickr/dev/neuron_poker/.venv/lib/python3.11/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 133, in <module>
    objc.class_getMethodImplementation_stret.restype = c_void_p
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: dlsym(0x3c07d83b0, class_getMethodImplementation_stret): symbol not found. Did you mean: 'class_getMethodImplementation'?

**Comment by caffeinepills** [comment]
Not enough information. No pyglet version/info and no OS information provided.

**Comment by dickreuter** [comment]
Pyglet version: 1.5.11
MacOS 14.2.1

**Comment by caffeinepills** [comment]
I would try upgrading the pyglet version. 1.5.11 is 4 years old. The latest pyglet 1.5 release is 1.5.27, give that a try.

**Comment by unoctanium** [comment]
I have exactly the same error.
when I run >>>pyglet.display.get_display()
is there any solution?

**Comment by benmoran56** [comment]
@unoctanium unfortunately iPad is not currently supported. It may be able to work, but we can't provide support for it. 
This may change in the future, but nobody is currently working on it.
