### ISSUE TITLE
AttributeErrors with NoneType and clock with Python 3.8

### ISSUE THREAD

**Issue by patrikhuber** [pyglet/pyglet#114]
I believe pyglet might not be python 3.8 ready yet? I'm trying to run a simple example with [pyrender](https://pyrender.readthedocs.io/en/latest/examples/quickstart.html#minimal-example-for-3d-viewer) which uses pyglet, with `pyglet-1.4.0b1` installed, and getting a bunch of errors from pyglet:

```
Traceback (most recent call last):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrender\__init__.py", line 12, in <module>
    from .viewer import Viewer
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrender\viewer.py", line 36, in <module>
    class Viewer(pyglet.window.Window):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\window\__init__.py", line 1859, in <module>
    from pyglet.window.win32 import Win32Window as Window
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\window\win32\__init__.py", line 59, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\canvas\__init__.py", line 63, in <module>
    from pyglet.app import WeakSet
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\app\__init__.py", line 163, in <module>
    event_loop = EventLoop()
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\app\base.py", line 152, in __init__
    self.clock = clock.get_default()
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\clock.py", line 137, in <module>
    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

I believe these are related to Python 3.8, see e.g. https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8.

Original issue in the pyrender tracker: https://github.com/mmatl/pyrender/issues/95

**Comment by benmoran56** [comment]
Hi Patrick, 

1.4.0b is too old for Python 3.8. If you update to the latest 1.4.x release it should work fine.

**Comment by patrikhuber** [comment]
Hi Ben,

Thanks for the quick reply.

Right! It seems like pyrender need to update their dependencies then - when I upgrade pyglet, I get:

`ERROR: pyrender 0.1.33 has requirement pyglet==1.4.0b1, but you'll have pyglet 1.4.8 which is incompatible.`. I'll report it back to them.

Thanks a lot.
