### ISSUE TITLE
Setting pyglets 'audio' option fails

### ISSUE THREAD

**Issue by eruvanos** [pyglet/pyglet#1159]
**Describe the bug**
The type check for setting the audio option, causes an exception, even when a tuple with strings is passed.

**System info**

Apple M1
OS: 14.5
Python: 3.9.18

**How To Reproduce**

```
pyglet.options["audio"] = ("openal", "xaudio2", "directsound", "pulse", "silent")
```

Causes

```
File "/Users/****/arcade/.venv/lib/python3.9/site-packages/pyglet/__init__.py", line 260, in __setitem__
    assert type(value).__name__ == self.__annotations__[key], f"Invalid type: '{type(value)}' for '{key}'"
AssertionError: Invalid type: '<class 'tuple'>' for 'audio'
```

**Comment by einarf** [comment]
I think it was something missing in development branch. Setting the value using the `.audio` attribute works.

**Comment by eruvanos** [comment]
Setting `pyglet.options.audio` works, is this expected behaviour?
Might be not a bug at all then.

**Comment by Square789** [comment]
The type check is too aggressive, the env variable `PYGLET_AUDIO` does not work anymore as well:
```
> PYGLET_AUDIO="openal,silent" python3 -m examples.media.soundspace.soundspace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/square/Code/python/pyglet/examples/media/soundspace/soundspace.py", line 39, in <module>
    import pyglet
  File "/home/square/Code/python/pyglet/pyglet/__init__.py", line 257, in <module>
    options[_key] = _value.split(",")
    ~~~~~~~^^^^^^
  File "/home/square/Code/python/pyglet/pyglet/__init__.py", line 245, in __setitem__
    assert type(value).__name__ == self.__annotations__[key], f"Invalid type: '{type(value)}' for '{key}'"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid type: '<class 'list'>' for 'audio'
```

**Comment by benmoran56** [comment]
Thanks for the PR @Square789,. The stricter behavior is new, but that was actually supposed to be commented out.
