### ISSUE TITLE
When silent pyglet should not try to load other audio drivers

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#121]
When specifying 
`pyglet.options['audio'] = ('silent',)`
pyglet should not try to load any audio  driver.

Consider a machine with no ffmpeg installed, and this script:

```python
#file pyglet_silent.py
import pyglet
import pyglet.media

try:
    decoders = pyglet.media.codecs._decoder_extensions.get(".mp3", [])
except Exception:
    decoders = None

print("decoders:", decoders)

if decoders:
    have_mp3 = True
else:
    pyglet.options['audio'] = ('silent',)
    have_mp3 = False

music_player = pyglet.media.Player()
```

With pyglet 1.3.3
```
...
Installing collected packages: pyglet
Successfully installed pyglet-1.3.3

(py38-cocos2020) D:\dev\_pyglet_silent>python pyglet_silent.py
decoders: None

(py38-cocos2020) D:\dev\_pyglet_silent>
```

with 1.4.9 (and probably all 1.4.x)

```
...
Successfully installed pyglet-1.4.9

(py38-cocos2020) D:\dev\_pyglet_silent>python pyglet_silent.py
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
Traceback (most recent call last):
  File "pyglet_silent.py", line 2, in <module>
    import pyglet.media
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\__init__.py",
 line 146, in <module>
    add_default_media_codecs()
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\lib.py", line 148,
in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56'. Try using the full path wi
th constructor syntax.
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\__init__.py",
 line 146, in <module>
    add_default_media_codecs()
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\__init
__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\media\codecs\ffmpeg
_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "d:\dev\venvs\py38-cocos2020\lib\site-packages\pyglet\lib.py", line 148,
in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "D:\prog\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56'. Try using the full path wi
th constructor syntax.

(py38-cocos2020) D:\dev\_pyglet_silent>
```

The point of a silent driver is to allow to play a game even if theres no support for audio.

details: win7, py 3.8, pyglet 1.4.9 from pypi

ref: https://github.com/los-cocos/cocos/pull/333#issuecomment-573287826

**Comment by benmoran56** [comment]
Hi Claudio,

Thanks for opening the issue. It looks like this might be a bug with the ffmpeg detection, not with the driver loading. 
```
    if have_ffmpeg():
```
If ffmpeg fails to load, it should just return `False` instead of crashing with a `FileNotFoundError`. 
The driver loading itself seems to be OK.  I put a fix into the 1.4-maintenance branch. If possible, could you let me know if that works for you?

**Comment by ccanepa** [comment]
Its okey in the sense there's no crash.

Not sure if an error message should show always when ffmpeg is not instaled, by example pyglet's noisy.py uses a .wav, which does not need ffmpeg and still will show the error message:

````
(py38-cocos2020) D:\dev\pyglet-2019\examples\noisy>python noisy.py
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
```

Also, when the error message is needed it would be better to prhase on the lines of "ffmpeg audio - video error, bla bla..."

**Comment by benmoran56** [comment]
The error message is not needed, and in fact, I found that we had an explicit print statement in the library loading code.  I've fixed this so that the error message gets raised as part of the exception, not explicitly printed **and** raised. In the case of checking if FFmpeg is available, we want to catch the exception if it's not. 

It should be OK now in 1.4-maintenance branch. (Your other ticket that you opened still remains, but I'll comment on that separately). 

Thanks!

**Comment by ccanepa** [comment]
Neat. Thanks Benjamin.

**Comment by benmoran56** [comment]
This should be fixed now. Could you give it a try, and see how it goes?

**Comment by ccanepa** [comment]
Much better.
 - while running the app all clean
 - but, quiting the app produces some errors:

```
(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
Exception ignored in: <function DirectSoundListener.__del__ at 0x0000000008666AF
0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
425, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
428, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundDriver.__del__ at 0x0000000008642B80>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
76, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBufferFactory.__del__ at 0x0000000008
642DC0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
96, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x0000000008664280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x0000000008664280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:

Original exception was:

(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
Exception ignored in: <function DirectSoundListener.__del__ at 0x000000000861CAF
0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
425, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
428, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundDriver.__del__ at 0x00000000085F5B80>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
76, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBufferFactory.__del__ at 0x0000000008
5F5DC0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
96, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x000000000861A280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x000000000861A280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
``` 

On another  side noisy.py and astraea.py don't complain when quiting.

**Comment by ccanepa** [comment]
Works fine and clean, thanks.

Tested with
win7-64, py38, pyglet as
commit c4acb39 (HEAD -> pyglet-1.4-maintenance,
origin/pyglet-1.4-maintenance)
Author: Benjamin Moran
Date: Tue Jan 14 10:21:06 2020 +0900

**Comment by benmoran56** [comment]
Great! I'll close this for now, but feel free to reopen it if you see anything strange.
