### ISSUE TITLE
Add support for loading uncompressed DDS files

### ISSUE THREAD

**Issue by Yuriy-Leonov** [pyglet/pyglet#122]
### Env:
pyglet: 1.4.9
Ubuntu: 18.04 and Windows 10 (exception is different based on platform)

### Introduce
I created example with issue - https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/tree/master/dds_without_compression

python script - https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/dds_without_compression/convert_and_open_dds.py (very short)

```
import pyglet


def convert():
    from wand import image
    with image.Image(filename="31_21.png") as img:
        img.strip()
        img.flip()
        image.library.MagickSetOption(img.wand, b"dds:mipmaps", b"0")
        image.library.MagickSetOption(img.wand, b"dds:compression", b"none")
        img.save(filename="31_21.dds")


def load():
    pyglet.image.load("31_21.dds")


if __name__ == '__main__':
    convert()
    load()
```
Convertation for `.png` could be done either as via python as via Ubuntu console - `convert file.png -define dds:compression=none out.dds` (based on SO answer https://stackoverflow.com/questions/59703196/how-to-convert-png-to-uncompressed-dds-in-linux/59704501#59704501 )

### Conddition:
There is a `.dds` file with no compression.
Try to load this file in pyglet.

Using GIMP this file could be opened successfully:
![GIMP](https://github.com/Yuriy-Leonov/pyglet_dds_power_of_two/blob/master/dds_without_compression/file_could_be_opened_with_GIMP.png?raw=true)

### Exceptions:
On Ubuntu 18.04:
```
Traceback (most recent call last):
  File "convert_and_open_dds.py", line 20, in <module>
    load()
  File "convert_and_open_dds.py", line 15, in load
    pyglet.image.load("31_21.dds")
  File "/<path to venv>/lib/python3.6/site-packages/pyglet/image/__init__.py", line 208, in load
    raise first_exception
  File "/<path to venv>/lib/python3.6/site-packages/pyglet/image/__init__.py", line 198, in load
    image = decoder.decode(file, filename)
  File "/<path to venv>/lib/python3.6/site-packages/pyglet/image/codecs/gdkpixbuf2.py", line 311, in decode
    return loader.get_pixbuf().to_image()
  File "/<path to venv>/lib/python3.6/site-packages/pyglet/image/codecs/gdkpixbuf2.py", line 137, in get_pixbuf
    self._finish_load()
  File "/<path to venv>/lib/python3.6/site-packages/pyglet/image/codecs/gdkpixbuf2.py", line 123, in _finish_load
    raise ImageDecodeException(_gerror_to_string(error))
pyglet.image.codecs.ImageDecodeException: GdkPixBuf Error: domain[66], code[3]: <ctypes.LP_c_char object at 0x7f824b832950>
```

On Windows 10:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\<path_to_venv>\venv\lib\site-packages\pyglet\image\__init__.py", line 208, in load
    raise first_exception
  File "E:\<path_to_venv>\venv\lib\site-packages\pyglet\image\__init__.py", line 198, in load
    image = decoder.decode(file, filename)
  File "E:\<path_to_venv>\venv\lib\site-packages\pyglet\image\codecs\gdiplus.py", line 284, in decode
    bitmap = self._load_bitmap(file, filename)
  File "E:\<path_to_venv>\venv\lib\site-packages\pyglet\image\codecs\gdiplus.py", line 227, in _load_bitmap
    raise ImageDecodeException('GDI+ cannot load %r' % (filename or file))
pyglet.image.codecs.ImageDecodeException: GDI+ cannot load '31_21.dds'
```

#### Why does it need:
Uncompressed DDS could be use used for speedup loading images to GPU without loose the quality.
And it sould use a bit less RAM compared to PNG(in theory)

**Comment by benmoran56** [comment]
Hi @Yuriy-Leonov, 

It seems that the DDS codec does not support loading uncompressed DDS files. I updated the codec so that it raises a proper exception now: 
```
pyglet.image.codecs.ImageDecodeException: Uncompressed DDS textures not supported.
```

It should not be *too* difficult to add support, but it's not a high priority at the moment. It was also a bit difficult to find information on this. Some things that are not yet clear to me are: 
Is `glCompressedTexImage2D` still used? 
What flag is used? Instead of "GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT" or similar, would we use "GL_COMPRESSED_SRGB" or something else? 

If anyone has any information it would be appreciated.

**Comment by Yuriy-Leonov** [comment]
@benmoran56 
Good questions. :) I was try to do only code in example and I didn't set any specific flags. It was experiment to try load unconpressed DDS.
If it low priority - let it be on hold.

**Comment by kingadami** [comment]
@benmoran56 I have been looking at this one and think this might be more challenging for me to do, in that it allows me to learn more aspects of pyglet.  I have already made some changes to the dds.py file to allow for it to read uncompressed RGB with or without an alpha channel correctly (it even reads the file supplied in the above example).  I see that you mentioned a question related to sRGB for this issue.  In reading the DDS spec, I don't think it uses the sRGB color spaces by default and you can only specify it if you include the DX10 header extension, which so far GIMP isn't saving it with that header.

But, if it is including the DX10 header extension and then specifies an uncompressed sRGB format like DXGI_FORMAT_R8G8B8A8_UNORM_SRGB then I think you would use glTexture2D with the format of SRGB_ALPHA_EXT or similar(?) assuming GL_EXT_texture_sRGB is supported.

However, like I said before, I think basic initial support can be added for non-DX10 textures without to much effort and then I can work on the DX10 based extended DXGI formats.  What do you think?

**Comment by benmoran56** [comment]
Hi @kingadami, 

Sure, these would be welcome additions. Let me know if you have any implementation questions.

One thing to keep in mind when working with codecs is that all exceptions should be caught and raised as `ImageDecodeException`. This lets us gracefully move on to the next codec in case of failure (or unknown format).
