### ISSUE TITLE
Continuous errors from directaudio while running pyglet's noisy.py

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#123]
Repro:

 - start noisy.py
 - press once the space key

The pyglet's window shows a bouncing ball,  the ping sound is listened but console displays a continuous stream of errors:

```
(py38-cocos2020) D:\dev\pyglet-2019\examples\noisy>python noisy.py
Unexpected error loading library avutil-56: Could not find module 'avutil-56'. T
ry using the full path with constructor syntax.
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 225, in _run_func
tion
    self._func()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 182, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 187, in refill
    audio_data = self._get_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 208, in _get_audiodata
    self._get_new_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 216, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 141, in get_audio
_time_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists
Exception in thread Thread-22:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 225, in _run_func
tion
    self._func()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 182, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 187, in refill
    audio_data = self._get_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 208, in _get_audiodata
    self._get_new_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 216, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 141, in get_audio
_time_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists
Exception in thread Thread-30:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 225, in _run_func
tion
    self._func()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 182, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 187, in refill
    audio_data = self._get_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 208, in _get_audiodata
    self._get_new_audiodata()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 216, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 141, in get_audio
_time_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists
Exception in thread Thread-32:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\base.py", line 225, in _run_func
tion
    self._func()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 182, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 192, in refill
    self.write(audio_data, length)
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\adaptation.py", line
 313, in write
    audio_data.consume(write_ptr.audio_length_1.value, self.source.audio_format)

ReferenceError: weakly-referenced object no longer exists
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x0000000008144280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
    self.delete()
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
177, in delete
    self._native_buffer.Stop()
  File "d:\dev\pyglet-2019\pyglet\com.py", line 131, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

(py38-cocos2020) D:\dev\pyglet-2019\examples\noisy>
```

win7, no ffmpeg installed, py 3.8,  pyglet-1.4-maintenance at commit
commit 6e9c4485cb62789c3c3b5bb27bc75e6dd82653ae
Author: Benjamin Moran
Date:   Sun Jan 12 17:42:02 2020 +0900

**Comment by benmoran56** [comment]
Hi Claudio, 

This is a little bit of a work-in-progress. It should be fixed soon hopefully, so I'll update this ticket when it's fixed.

**Comment by ccanepa** [comment]
ACK

**Comment by benmoran56** [comment]
This should be fixed now. Could you give it a try, and see if you still get any console spam?

**Comment by ccanepa** [comment]
Much better.

 - while running the app all clean
 - but, quiting the app produces some errors:
```
(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
Exception ignored in: <function DirectSoundListener.__del__ at 0x0000000008666AF
0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
425, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
428, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundDriver.__del__ at 0x0000000008642B80>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
76, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBufferFactory.__del__ at 0x0000000008
642DC0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
96, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x0000000008664280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x0000000008664280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:

Original exception was:

(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
Exception ignored in: <function DirectSoundListener.__del__ at 0x000000000861CAF
0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
425, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
428, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundDriver.__del__ at 0x00000000085F5B80>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
76, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBufferFactory.__del__ at 0x0000000008
5F5DC0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
96, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x000000000861A280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x000000000861A280>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
172, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
175, in delete
TypeError: 'NoneType' object is not callable
```
On another side noisy.py and astraea.py don't complain when quiting.

**Comment by benmoran56** [comment]
HI @ccanepa, 

Does this happen with `noisy.py` as well, or just with the tetrico demo?

**Comment by ccanepa** [comment]
just with the tetrico demo

**Comment by benmoran56** [comment]
Looks like this is related to #113.
If you comment out the assertion at the top of the `__del__` method in interface.py, line 172, does it avoid the traceback?

**Comment by benmoran56** [comment]
Could you give it a try with the latest 1.5-maintenance branch? It should be fixed.

**Comment by ccanepa** [comment]
worse in 1.5

While running tetrico, and before quiting some errors show in console, also the sound decays to a short loop.

console before quit:

```
(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>python tetrico.py
Exception in thread Thread-71:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet15\pyglet\media\player.py", line 59, in _tick_clock
    self.tick()
  File "d:\dev\pyglet15\pyglet\clock.py", line 348, in tick
    self.call_scheduled_functions(delta_t)
  File "d:\dev\pyglet15\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 17
3, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 17
8, in refill
    audio_data = self._get_audiodata()
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 19
9, in _get_audiodata
    self._get_new_audiodata()
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 20
7, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "d:\dev\pyglet15\pyglet\media\drivers\base.py", line 144, in get_audio_ti
me_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists
```

after quit
```
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x00000000070DB5E0>

Traceback (most recent call last):
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\interface.py", line 169
, in __del__
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\interface.py", line 173
, in delete
  File "d:\dev\pyglet15\pyglet\com.py", line 138, in _call
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>
```

**Comment by ccanepa** [comment]
> Looks like this is related to #113.
If you comment out the assertion at the top of the __del__ method in interface.py, line 172, does it avoid the traceback?

in 1.4, after astraea fix: no, comenting out does not prevent the traceback when quiting:

```
Exception ignored in: <function DirectSoundListener.__del__ at 0x000000000864794
0>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
425, in __del__
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
428, in delete
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundDriver.__del__ at 0x000000000860A9D0>

Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
76, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function DirectSoundBufferFactory.__del__ at 0x0000000008
60AC10>
Traceback (most recent call last):
  File "d:\dev\pyglet-2019\pyglet\media\drivers\directsound\interface.py", line
96, in __del__
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:

Original exception was:

(py38-cocos2020) D:\dev\cocos2020\samples\tetrico>
```

**Comment by ccanepa** [comment]
Another observation in 1.5: noisy.py gives audio related tracebacks while running (app continues working)
```
(py38-cocos2020) D:\dev\pyglet15\examples\noisy>python noisy.py
Exception in thread Thread-156:
Traceback (most recent call last):
  File "D:\prog\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\prog\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "d:\dev\pyglet15\pyglet\media\player.py", line 59, in _tick_clock
    self.tick()
  File "d:\dev\pyglet15\pyglet\clock.py", line 348, in tick
    self.call_scheduled_functions(delta_t)
  File "d:\dev\pyglet15\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 17
3, in _check_refill
    self.refill(write_size)
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 17
8, in refill
    audio_data = self._get_audiodata()
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 19
9, in _get_audiodata
    self._get_new_audiodata()
  File "d:\dev\pyglet15\pyglet\media\drivers\directsound\adaptation.py", line 20
7, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "d:\dev\pyglet15\pyglet\media\drivers\base.py", line 144, in get_audio_ti
me_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists

``` 

win7, py38, pyglet
```
commit ecad2e8959efc52f2ac06d36d1c28e6734cff0fa (HEAD -> pyglet-1.5-maintenance,
 origin/pyglet-1.5-maintenance)
Author: Benjamin Moran
Date:   Fri Jan 24 10:42:48 2020 +0900

    Fix bad example code in quickstart documentation. #136
```

**Comment by benmoran56** [comment]
Hi Claudio, sorry for the delay. When you have a chance, could you try the `noisy.py` example on the latest 1.5 branch?

**Comment by ccanepa** [comment]
Hi Benjamin

pyglet commit 6386315b93f99a7300340324167ed6c4eb2931b0 (HEAD -> pyglet-1.5-maintenance,
 origin/pyglet-1.5-maintenance)
Author: Benjamin Moran
Date:   Mon Feb 17 18:20:03 2020 +0900

noisy.py with py37 or 38 runs clean and ends clean

astraea.py runs clean but ends dirty
```
(py38-cocos2020) D:\dev\pyglet15\examples\astraea>python astraea.py
Error in sys.excepthook:

Original exception was:

(py38-cocos2020) D:\dev\pyglet15\examples\astraea>
```

**Comment by benmoran56** [comment]
Thanks Claudio, 

That `sys.excepthook` looks like an unrelated issue. I'll have a look at that next.

**Comment by benmoran56** [comment]
Hi Claudio, 

I can't replicate the "sys.excepthook" on my system (Linux). There are two places where `sys.exit` might be called in the code. If you are still seeing the issue, could you try replacing those calls with `pyglet.app.exit`? 

Other than that I found a few similar bug reports in other projects, but I haven't found any reason for it.

**Comment by benmoran56** [comment]
This doesn't happen on my Windows 10 machine, with the latest 1.5-maintenance branch code. If you have time, could you try it as well?

**Comment by ccanepa** [comment]
I tried, and reported in the other issue, #142 
The current code using pyglet.app.exit gives the exception in astraea, while win.close runs clean.

win7, py38.

**Comment by benmoran56** [comment]
I'm going to close this for now, since it seems better. Thanks again for the ticket!
