### ISSUE TITLE
Out of Memory OpenALException when calling source.play() 256 times

### ISSUE THREAD

**Issue by Alfro** [pyglet/pyglet#1239]
**Describe the bug**
When loading a media source and repeatedly calling .play(), the source._players keep growing until it reaches 256 elements, at which point I get the following error:

> pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40965: b'Out of Memory']: Failed to create source.

Here is the full stack trace
```
Traceback (most recent call last):
  File "/home/alfro/projects/pyglet_issue/pyglet_issue.py", line 13, in <module>
    src.play()
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/codecs/base.py", line 246, in play
    player.play()
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/player.py", line 225, in play
    self._set_playing(True)
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/player.py", line 177, in _set_playing
    self._create_audio_player()
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/player.py", line 348, in _create_audio_player
    self._audio_player = audio_driver.create_audio_player(source, self)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/adaptation.py", line 33, in create_audio_player
    return OpenALAudioPlayer(self, source, player)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/adaptation.py", line 97, in __init__
    self.alsource = driver.context.create_source()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/interface.py", line 134, in create_source
    new_source = OpenALSource(self)
                 ^^^^^^^^^^^^^^^^^^
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/interface.py", line 148, in __init__
    self._check_error('Failed to create source.')
  File "/home/alfro/projects/pyglet_issue/.venv/lib/python3.12/site-packages/pyglet/media/drivers/openal/interface.py", line 37, in _check_error
    raise OpenALException(message=message,
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40965: b'Out of Memory']: Failed to create source.
```

**System Information:**
CPython: 3.21.6
pyglet: 2.0.18
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')

**How To Reproduce**
```
import pyglet

src = pyglet.media.load(f"./example.wav", streaming=False)
while True:
    src.play()
    print(len(src._players))
```
(Note. I've tested .wav and .ogg files, getting the same issue)

**Comment by benmoran56** [comment]
Hi, it's currently necessary to have a running pyglet event loop in order for the cleanup to be processed. This will work: 

```py
import pyglet

src = pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.2))


def play_source(dt):
    src.play()
    print(len(src._players))


pyglet.clock.schedule_interval(play_source, 1/60)
pyglet.app.run()
```

**Comment by Alfro** [comment]
Hm, I see, so just calling `pyglet.app.platform_event_loop.dispatch_posted_events()` also suffices.

There is actually a mention to calling dispatch_posted_events on the docs at the end of the "Playing Sound and Video" section, but there's no mention of this behaviour, or the need for an event loop to be running: https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#ticking-the-clock

Is it worth keeping this  open as a bug? Maybe it's enough to expand the info on that section of the docs.

**Comment by benmoran56** [comment]
I updated that section of the docs a bit, and tried to make it clearer. If you have another suggestion, or it's still not clear, please let us know.
