### ISSUE TITLE
Font rendering error with pyglet.text.Label on Windows (argument error in win32.py)

### ISSUE THREAD

**Issue by ShivamKR12** [pyglet/pyglet#1250]
# Bug Report: ctypes.ArgumentError with pyglet.text.Label on Windows

## Describe the Bug
I am encountering a `ctypes.ArgumentError` while creating a `pyglet.text.Label` with a specific font on Windows. The traceback suggests an issue related to the `GdipCreateBitmapFromScan0` function in `win32.py`.

## System Information
- **OS**: Windows 11  
- **Python Version**: 3.12.5  
- **Pyglet Version**: 2.0.20  

## How to Reproduce
Use the following code to create a label:

```python
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label(
    'Hello, Pyglet!',
    font_name='Arial',  # Tried Arial and other fonts
    font_size=25,
    x=window.width // 2, 
    y=window.height // 2,
    anchor_x='center', 
    anchor_y='center'
)
pyglet.app.run()
```

## Expected Behavior
The program should create a `pyglet.text.Label` without errors and render it correctly on the window.

## Actual Behavior
The program crashes with the following traceback:

```
PS C:\Users\Shivam\Desktop\TerraCraft-master> & c:/Users/Shivam/Desktop/TerraCraft-master/venv/Scripts/python.exe c:/Users/Shivam/Desktop/TerraCraft-master/main.py
c:\Users\Shivam\Desktop\TerraCraft-master\main.py:4: SyntaxWarning: invalid escape sequence '\ '
  """
c:\Users\Shivam\Desktop\TerraCraft-master\game\scenes.py:3: SyntaxWarning: invalid escape sequence '\ '
  """
Traceback (most recent call last):
  File "c:\Users\Shivam\Desktop\TerraCraft-master\main.py", line 65, in <module>
    main()
  File "c:\Users\Shivam\Desktop\TerraCraft-master\main.py", line 56, in main
    scene_manager = SceneManager(window=window)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Shivam\Desktop\TerraCraft-master\game\scenemanager.py", line 55, in __init__
    self.add_scene(MenuScene(self.window))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Shivam\Desktop\TerraCraft-master\game\scenes.py", line 124, in __init__
    self.start_label = pyglet.text.Label('Select save & press Enter to start', font_name='Arial', font_size=25,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\__init__.py", line 469, in __init__
    super(Label, self).__init__(document, x, y, width, height,
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\__init__.py", line 268, in __init__
    super(DocumentLabel, self).__init__(document,
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 858, in __init__
    self.document = document
    ^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 887, in document
    self._init_document()
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1336, in _init_document
    self._update()
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1247, in _update
    lines = self._get_lines()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1224, in _get_lines
    glyphs = self._get_glyphs()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\text\layout.py", line 1384, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\font\base.py", line 401, in get_glyphs
    glyph_renderer = self.glyph_renderer_class(self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\font\win32.py", line 100, in __init__
    self._create_bitmap(width, height)
  File "C:\Users\Shivam\Desktop\TerraCraft-master\venv\Lib\site-packages\pyglet\font\win32.py", line 324, in _create_bitmap
    gdiplus.GdipCreateBitmapFromScan0(width, height, width * 4,
ctypes.ArgumentError: argument 5: TypeError: expected LP_c_ubyte instance instead of c_byte_Array_3520
PS C:\Users\Shivam\Desktop\TerraCraft-master>
```

## Additional Notes
- I tried using other fonts like "Times New Roman," but the issue persists.
- The issue seems related to font rendering and bitmap creation in Windows via GDI+.
- This error does not occur on other operating systems like Linux or macOS.

**Comment by ShivamKR12** [comment]
or you can do the same by just running the main.py file of the terracraft "https://github.com/XenonLab-Studio/TerraCraft"

**Comment by ShivamKR12** [comment]
Additional Info:

I have tried using various fonts (Arial, Courier New) and different font sizes, but the issue persists.
I have also checked if GDI+ is installed, and I have the Visual C++ Redistributables installed.

**Comment by caffeinepills** [comment]
Looks like your install is not correct. You say you are using the newest 2.0.20 version, but the paths to the traceback do not indicate that.

Furthermore there were fixes to address the c_ubyte issue with the newer pythons are in recent versions. Update your Pyglet version or uninstall and reinstall. If that doesn't fix it, you may have to delete and reinstall your virtual environment.

**Comment by ShivamKR12** [comment]
then, could you please guide me on how i can install the latest version of the pyglet which has the c_ubyte fixed?
@caffeinepills

**Comment by ShivamKR12** [comment]
all right, let me try reinstallijg it.
