### ISSUE TITLE
WindowEventLogger() throws Out of Index on Ubuntu18.04

### ISSUE THREAD

**Issue by xiahualiu** [pyglet/pyglet#136]
I was following the tutorials of the Pyglet documents and tried to push `WindowEventLogger()` to the window event loop:

```python
#!/usr/bin/env python3
from __future__ import print_function

__docformat__ = 'restructuredtext'
__version__ = '$Id$'

import pyglet
from pyglet.window import key
from pyglet.window import mouse

window = pyglet.window.Window()
window.push_handlers(pyglet.window.event.WindowEventLogger())

@window.event
def on_key_press(symbol, modifiers):
    if symbol == key.A:
        print('The "A" key was pressed.')
    elif symbol == key.LEFT:
        print('The left arrow key was pressed.')
    elif symbol == key.ENTER:
        print('The enter key was pressed.')


@window.event
def on_mouse_press(x, y, button, modifiers):
    if button == mouse.LEFT:
        print('The left mouse button was pressed.')


@window.event
def on_draw():
    window.clear()


pyglet.app.run()
```

And it throw an error:
```
Traceback (most recent call last):
  File "./events.py", line 51, in <module>
    @window.event
  File "/home/liux/.local/lib/python3.6/site-packages/pyglet/event.py", line 511, in event
    self.set_handler(name, func)
  File "/home/liux/.local/lib/python3.6/site-packages/pyglet/event.py", line 279, in set_handler
    self._event_stack[0][name] = handler
IndexError: list index out of range
```

The python version is 3.6.9 and the system is Ubuntu18.04 latest update:

```bash
liux@liux-MS-7A72:~/Downloads/pyglet/examples/programming_guide$ uname -a
Linux liux-MS-7A72 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
liux@liux-MS-7A72:~/Downloads/pyglet/examples/programming_guide$ python3 --version
Python 3.6.9
```

I am pretty sure that the whole program went well except after adding the `WindowEventLogger()` line, since I was still on the beginning state of learning Pyglet API, so if it was my fault, please let me know.

**Comment by xiahualiu** [comment]
The Pyglet I used is 1.4.10(latest) version.

**Comment by benmoran56** [comment]
Hi @xiahualiu,  this is an error in the documentation. You need to keep a local reference to the `WindowEventLogger` instance, or it will fall out of scope (and be garbage collected). 

This should work: 

```
window = pyglet.window.Window()
event_logger = pyglet.window.event.WindowEventLogger()
window.push_handlers(event_logger)
```

I'll update the documentation.

**Comment by benmoran56** [comment]
I've updated this documentation.
Version 1.5 of pyglet will be released soon, so at that time the documentation will also be updated on ReadTheDocs. 

Thanks for the report!
