### ISSUE TITLE
b'invalid operation' when attempting to play video file in 2.0.dev0

### ISSUE THREAD

**Issue by kdougan** [pyglet/pyglet#138]
Test code:
```
# coding: utf-8

import pyglet

class App(pyglet.window.Window):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        fname = 'SampleVideo_1280x720_1mb.flv'
        src = pyglet.media.load(fname)
        self.player = pyglet.media.Player()
        self.player.queue(src)

    def run(self):
        pyglet.clock.schedule_interval(self.update, 1/60)
        self.player.play()
        pyglet.app.run()
        self.impl.shutdown()
    
    def update(self, dt):
        pass
    
    def on_draw(self):
        self.clear()
        if self.player.source and self.player.source.video_format:
            self.player.get_texture().blit(0,0)

App(1280,720).run()
```

produces:
```
/python/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 'v3f'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
/python/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 't3f'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
Traceback (most recent call last):
  File "Untitled 10.py", line 28, in <module>
    App(1280,720).run()
  File "Untitled 10.py", line 17, in run
    pyglet.app.run()
  File "/python/.venv/lib/python3.7/site-packages/pyglet/app/__init__.py", line 106, in run
    event_loop.run(interval)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 177, in run
    timeout = self.idle()
  File "/python/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 238, in idle
    self.clock.call_scheduled_functions(dt)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/clock.py", line 268, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 152, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/python/.venv/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1290, in dispatch_event
    EventDispatcher.dispatch_event(self, *args)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/event.py", line 420, in dispatch_event
    if getattr(self, event_type)(*args):
  File "Untitled 10.py", line 26, in on_draw
    self.player.get_texture().blit(0,0)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/image/__init__.py", line 1460, in blit
    ('t3f', self.tex_coords))
  File "/python/.venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 262, in draw_indexed
    glDrawElements(mode, len(indices), index_type, index_array)
  File "/python/.venv/lib/python3.7/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

System:
`pyglet==2.0.dev0` on `macOS 10.15.2`
verified that FFMpeg is installed
verified OpenGL is working for standard Sprite() and Batch.draw() usage.

**Comment by benmoran56** [comment]
Thank you for opening the ticket. 

Could you also see if the `/examples/opengl_core.py` and `/examples/opengl_context.py` examples run properly?

**Comment by kdougan** [comment]
```➜  examples git:(master) ✗ pipenv shell
Launching subshell in virtual environment…
 . /Users/kyle/git/pyglet/examples/.venv/bin/activate
➜  examples git:(master) ✗  . /Users/kyle/git/pyglet/examples/.venv/bin/activate

(examples) ➜  examples git:(master) ✗ python -V
Python 3.7.4
```
----
```(examples) ➜  examples git:(master) ✗ python opengl_core.py
OpenGL Context: 4.1 ATI-3.4.19
/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 'v3f'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 'c3f'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 'v2f'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/graphics/vertexattribute.py:254: UserWarning: Vertex attribute shorthand notation is deprecated: 'v2i'. Please use the actual attribute names as defined in the Shader Program.
  warnings.warn(message)
Traceback (most recent call last):
  File "opengl_core.py", line 97, in <module>
    pyglet.app.run()
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/app/__init__.py", line 106, in run
    event_loop.run(interval)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 177, in run
    timeout = self.idle()
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 238, in idle
    self.clock.call_scheduled_functions(dt)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/clock.py", line 268, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/app/base.py", line 152, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1290, in dispatch_event
    EventDispatcher.dispatch_event(self, *args)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/event.py", line 413, in dispatch_event
    if handler(*args):
  File "opengl_core.py", line 80, in on_draw
    ('c3f', (1, 0.5, 0.2,  1, 0.5, 0.2,  1, 0.5, 0.2, 1, 0.5, 0.2)))
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 262, in draw_indexed
    glDrawElements(mode, len(indices), index_type, index_array)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```
----
```(examples) ➜  examples git:(master)  python opengl_context.py
Traceback (most recent call last):
  File "opengl_context.py", line 21, in <module>
    window = pyglet.window.Window(config=config, visible=False)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/window/__init__.py", line 621, in __init__
    self._create()
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/window/cocoa/__init__.py", line 194, in _create
    self.context.attach(self.canvas)
  File "/Users/kyle/git/pyglet/examples/.venv/lib/python3.7/site-packages/pyglet/gl/cocoa.py", line 291, in attach
    self._nscontext.setView_(canvas.nsview)
AttributeError: 'NoneType' object has no attribute 'setView_'
```

**Comment by kdougan** [comment]
created a fresh virtualenv in the examples folder with only `pyglet` installed for the tests.

**Comment by benmoran56** [comment]
Thanks @kdougan 

I suppose a very simple test app would also crash, but if you could confirm that would be great:

```py

import pyglet

window = pyglet.window.Window()

@window.event
def on_draw():
    window.clear()

pyglet.app.run()
```

In either case, please post the output of `python -m pyglet.info`. 
It may crash halfway through, but lets see how far it gets. I think the main issue is related to context creation on your hardware/graphics adapter, so any info you can share about your machine would also be helpful. 

Thanks!

**Comment by kdougan** [comment]
```➜  test_138 pipenv shell
Launching subshell in virtual environment…
 . /Users/kyle/Documents/python/pyglet/test_138/.venv/bin/activate
➜  test_138  . /Users/kyle/Documents/python/pyglet/test_138/.venv/bin/activate
(test_138) ➜  test_138 python -V
Python 3.7.4
(test_138) ➜  test_138 pipenv lock -r
-i https://pypi.org/simple
pyglet==2.0.dev0
(test_138) ➜  test_138 python main.py
(test_138) ➜  test_138
```
program runs just fine

```(test_138) ➜  test_138 python -m pyglet.info
Platform
------------------------------------------------------------------------------
platform:  Darwin-19.2.0-x86_64-i386-64bit
release:   19.2.0
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.7.4 (default, Sep 11 2019, 21:25:18)
[Clang 10.0.1 (clang-1001.0.46.4)]
sys.maxint: 9223372036854775807
PyObjC not available
os.getcwd(): /Users/kyle/Documents/python/pyglet/test_138

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.dev0
pyglet.compat_platform: darwin
pyglet.__file__: /Users/kyle/Documents/python/pyglet/test_138/.venv/lib/python3.7/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.cocoa.CocoaDisplay object at 0x105b19190>
Traceback (most recent call last):
  File "/Users/kyle/Documents/python/pyglet/test_138/.venv/lib/python3.7/site-packages/pyglet/info.py", line 225, in _try_dump
    func()
  File "/Users/kyle/Documents/python/pyglet/test_138/.venv/lib/python3.7/site-packages/pyglet/info.py", line 102, in dump_window
    print('screens[%d]: %r' % (i, screen))
  File "/Users/kyle/Documents/python/pyglet/test_138/.venv/lib/python3.7/site-packages/pyglet/canvas/base.py", line 160, in __repr__
    return '%s(x=%d, y=%d, width=%d, height=%d)' % self.__class__.__name__, self.x, self.y, self.width, self.height
TypeError: not enough arguments for format string

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.3 MacOSX
glu_info.get_extensions():

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x1075723d0>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.2.2

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL '/System/Library/Frameworks/OpenAL.framework/OpenAL', handle 7fa133cd4a30 at 0x107570190>
Version: 1.1
Extensions:
   ALC_EXT_CAPTURE
   ALC_ENUMERATION_EXT
   ALC_EXT_MAC_OSX
   ALC_EXT_ASA
   ALC_EXT_ASA_DISTORTION
   ALC_EXT_ASA_ROGER_BEEP

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
(test_138) ➜  test_138
```

**Comment by kdougan** [comment]
```Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
```

```Radeon Pro 560X:

  Chipset Model:	Radeon Pro 560X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c2
  ROM Revision:	113-C980AL-075
  VBIOS Version:	113-C97501U-005
  EFI Driver Version:	01.A1.075
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
```

**Comment by benmoran56** [comment]
If you're still watching this, could you let us know if the simple example still crashes with the latest `master` branch code?

**Comment by kdougan** [comment]
The code runs but raises the follow warnings:
```shell
2021-02-01 18:01:38.377 python[5743:28067068] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff66ec85930>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-02-01 18:01:38.378 python[5743:28067068] Warning: Expected min height of view: (<NSButton: 0x7ff64ec37620>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-02-01 18:01:38.381 python[5743:28067068] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff64ec3b090>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2021-02-01 18:01:38.382 python[5743:28067068] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff64edfe0e0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

`python -m piglet.info` output:
```shell
Platform
------------------------------------------------------------------------------
platform:  Darwin-20.2.0-x86_64-i386-64bit
release:   20.2.0
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.7.8 (default, Aug  9 2020, 11:38:29)
[Clang 11.0.3 (clang-1103.0.32.62)]
sys.maxint: 9223372036854775807
objc.__version__: 7.1
os.getcwd(): /Users/kyle/Documents/python

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.dev0
pyglet.compat_platform: darwin
pyglet.__file__: /Users/kyle/Documents/python/.venv/lib/python3.7/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.cocoa.CocoaDisplay object at 0x11ac60350>
screens[0]: CocoaScreen(x=0, y=0, width=3840, height=2160)
screens[1]: CocoaScreen(x=3840, y=784, width=1680, height=1050)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 0
config['green_size'] = 0
config['blue_size'] = 0
config['alpha_size'] = 8
config['depth_size'] = 32
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 2
config['forward_compatible'] = None
config['debug'] = None
context: CocoaContext()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 4.1 ATI-4.2.13
gl_info.get_vendor(): ATI Technologies Inc.
gl_info.get_renderer(): AMD Radeon Pro 560X OpenGL Engine
gl_info.get_extensions():
   GL_APPLE_client_storage
   GL_APPLE_container_object_shareable
   GL_APPLE_flush_render
   GL_APPLE_object_purgeable
   GL_APPLE_rgb_422
   GL_APPLE_row_bytes
   GL_APPLE_texture_range
   GL_ARB_ES2_compatibility
   GL_ARB_blend_func_extended
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_indirect
   GL_ARB_explicit_attrib_location
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_occlusion_query2
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_separate_shader_objects
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_subroutine
   GL_ARB_shading_language_include
   GL_ARB_tessellation_shader
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_gather
   GL_ARB_texture_query_lod
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_storage
   GL_ARB_texture_swizzle
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ATI_texture_mirror_once
   GL_EXT_debug_label
   GL_EXT_debug_marker
   GL_EXT_depth_bounds_test
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_mirror_clamp
   GL_EXT_texture_sRGB_decode
   GL_NV_texture_barrier

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x11debea10>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.3.1

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL '/System/Library/Frameworks/OpenAL.framework/OpenAL', handle 7fd1ccc9cb10 at 0x124c7ec90>
Version: 1.1
Extensions:
   ALC_EXT_CAPTURE
   ALC_ENUMERATION_EXT
   ALC_EXT_MAC_OSX
   ALC_EXT_ASA
   ALC_EXT_ASA_DISTORTION
   ALC_EXT_ASA_ROGER_BEEP

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

**Comment by benmoran56** [comment]
Thanks for the feedback. We'll probably be pushing out another `dev` release of this code soon. 

Regarding the NSTouchbar errors, it looks like Big Sur requires some extra work to be done to support the Touch Bar. It's not yet implemented in pyglet, so the warnings can be safely ignored for the time being.

**Comment by benmoran56** [comment]
A newer dev release was pushed out a few months ago, so I'll close this for now. 
Please keep in mind that pyglet 2.0 is still under development, so lots of issues remain.
