### ISSUE TITLE
OSError is observed when player is destroyed

### ISSUE THREAD

**Issue by t-o-n-y-p** [pyglet/pyglet#141]
Running this sample 
```
import time

from pyglet.media import Player, SourceGroup
from pyglet.media.synthesis import Sine

ANNOUNCEMENT_PLAYER = Player()
ANNOUNCEMENT_INTRO = SourceGroup()
ANNOUNCEMENT_INTRO.add(Sine(duration=0.2, frequency=247))
ANNOUNCEMENT_INTRO.add(Sine(duration=0.2, frequency=294))
ANNOUNCEMENT_INTRO.add(Sine(duration=0.2, frequency=349))
ANNOUNCEMENT_INTRO.add(Sine(duration=0.2, frequency=440))
ANNOUNCEMENT_PLAYER.queue(ANNOUNCEMENT_INTRO)
ANNOUNCEMENT_PLAYER.play()
time.sleep(2)
```
plays the note sequence, but at the end results in
```
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x02E71778>
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyglet-1.5.0-py3.8.egg\pyglet\media\drivers\directsound\interface.py", line 169, in __del__
  File "C:\Users\1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyglet-1.5.0-py3.8.egg\pyglet\media\drivers\directsound\interface.py", line 173, in delete
  File "C:\Users\1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyglet-1.5.0-py3.8.egg\pyglet\com.py", line 138, in _call
OSError: exception: access violation writing 0x00000000
```

Windows 7, Python 3.8.1, latest code from 1.5 branch.

**Comment by chcarmen** [comment]
This issue and #113 are because of the same reason. Resource clearing is improperly handled in Pyglet.

**Comment by benmoran56** [comment]
This was fixed a while ago, but this issue got lost along the way.
