### ISSUE TITLE
Unscheduling an item in pyglet.clock doesn't really seem to unschedule it

### ISSUE THREAD

**Issue by vibrant** [pyglet/pyglet#156]
So I encountered this situation when switching a sprite image from an animation to a single image on the go.  Then the sprite seems to try to render the animation anyway, even though it's not there any longer.  Trying to track it but no success yet:

Traceback (most recent call last):
  File "/Users/wojtek/PycharmProjects/lands/client/main.py", line 13, in <module>
    pyglet.app.run()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/app/__init__.py", line 144, in run
    event_loop.run()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/app/base.py", line 175, in run
    self._run()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/app/base.py", line 187, in _run
    timeout = self.idle()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/app/base.py", line 308, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/clock.py", line 333, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 281, in _animate
    frame = self._animation.frames[self._frame_index]
AttributeError: 'NoneType' object has no attribute 'frames'

**Comment by benmoran56** [comment]
Thanks for opening the ticket. Are you able to show a short code example that illustrates the problem? I can't replicate this on my end.

**Comment by vibrant** [comment]
Tried to replicate outside of my code and didn't manage to do it.

It could have something to do with the fact that I'm running a loop which runs object updates (movement, combat, etc.) using pyglet.clock.schedule_interval, and then I was iterating over a copy of the set of all in game sprites, while modifying that set in the meantime.  And then on_draw was called trying to draw them and perhaps some of them could have been deleted in the meantime because it also made a copy of the sprite set before starting iteration?

**Comment by benmoran56** [comment]
In general, modifying something while you're iterating over it is a bit dangerous. Instead of deleting things during the iteration, how about making a separate list for "dead sprites", and then adding to that list instead of deleting them. You can then deleting all of them at the end, or beginning of your next iteration. 

Just in case you're not, you should also make sure that you're calling `Sprite.delete()` on the Sprites, instead of just `del sprite`.

**Comment by vibrant** [comment]
Yup, made a sprite deletion queue and some other tweaks and it seems to be working.

**Comment by benmoran56** [comment]
Great! I'm glad that fixed it for you.
