### ISSUE TITLE
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40961: b'Invalid Name']: Failed to delete source.

### ISSUE THREAD

**Issue by Fredkiss3** [pyglet/pyglet#164]
I'm making a game engine using `pyglet` as rendering system. I have made a small using it, where the player has to destroy enemies before they get right into him, or he will die.

When an enemy die it should play a `death sound`. but after playing for a while, when you destroy many enemies (i.e play each `death sound`), this exception is frown right to me. Actually to play a sound, i load it, then i play it with a player.

This is my code to play a sound : 

```python

import pyglet

# In order to play all the sounds we must keep references of the players
players = [] 

def play_sound(sound_name, volume=10):
    """
    Code for playing a sound
    """
    global players
    # Load media sound
    sound = pyglet.resource.media(sound_name, streaming=True) # type: pyglet.media.Source

    # Queue and play sound
    player = pyglet.media.Player()
    player.volume = volume / 10
    player.queue(sound)
    player.play()
    
    # Add this player to players in order to keep a reference to it 
    players.append(player)

# Time passed and number of calls
time_passed = 0
num_calls = 0

def main(dt):
    global time_passed, num_calls
    time_passed += dt
    num_calls += 1
    play_sound("death.wav", volume=4)
    
    # After 256 calls, the game crashes
    print(time_passed, num_calls)


if __name__=="__main__":
    pyglet.clock.schedule_interval(main, 0.1)
    pyglet.app.run()

```

My system is `Ubuntu 18.10`
My pyglet version is `pyglet-1.5-maintenance`

**Comment by benmoran56** [comment]
This is something I need to look into. In the mean time, if you have sounds that are played many times, it's recommended to use `StaticSource`s for them. You can get a Static Source by passing `streaming=False` when loading the sound, or wrapping it in a StaticSource instance:
`static_source = StaticSource(source)`

**Comment by DjizzPulpe** [comment]
Hi,
I am currently facing the same issue with the following simple test function:

```python
def test():
    sound = pyglet.resource.media("pad.mp3", streaming=False)
    i = 0

    while True:
        sound.play().volume = 0.1
        i += 1
        print(i)
        time.sleep(0.01)
```
When it reaches 256 iterations (independently of the waiting time), the code stops with the errors:

```
Traceback (most recent call last):
  File "/home/pi/PycharmProjects/death_drum_v0.0/death_drum.py", line 206, in <module>
    main()
  File "/home/pi/PycharmProjects/death_drum_v0.0/death_drum.py", line 201, in main
    test()
  File "/home/pi/PycharmProjects/death_drum_v0.0/death_drum.py", line 150, in test
    sound.play().volume = 0.1
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/codecs/base.py", line 274, in play
    player.play()
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/player.py", line 248, in play
    self._set_playing(True)
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/player.py", line 198, in _set_playing
    self._create_audio_player()
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/player.py", line 364, in _create_audio_player
    self._audio_player = audio_driver.create_audio_player(source, self)
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/adaptation.py", line 66, in create_audio_player
    return OpenALAudioPlayer(self, source, player)
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/adaptation.py", line 125, in __init__
    self.alsource = driver.context.create_source()
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 170, in create_source
    return OpenALSource(self)
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 180, in __init__
    self._check_error('Failed to create source.')
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 76, in _check_error
    error_string=str(error_string.value))
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40965: b'Out of Memory']: Failed to create source.
Exception ignored in: <function OpenALSource.__del__ at 0xa4d51780>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 189, in __del__
    self.delete()
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 195, in delete
    self._check_error('Failed to delete source.')
  File "/home/pi/.local/lib/python3.7/site-packages/pyglet/media/drivers/openal/interface.py", line 76, in _check_error
    error_string=str(error_string.value))
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40961: b'Invalid Name']: Failed to delete source.
```

I hope this will help, pyglet is very simple and the only library able to play sound files that fast so far.

Running on ```Raspberry Pi 4```
System ```Raspbian GNU/Linux 10 (buster)```
Using ```pyglet 2.0.dev0```

**Comment by benmoran56** [comment]
It seems at least that without the pyglet event loop running, the old internal buffers won't be cleared. This example with non-persistant Players is at least working correctly: 
```py
import pyglet


window = pyglet.window.Window()


@window.event
def on_draw():
    window.clear()


sound = pyglet.resource.media("mgs.mp3", streaming=False)
counter = 0


def play_sound(dt):
    global counter, sound
    sound.play().volume = 0.1
    counter += 1
    print(counter)


pyglet.clock.schedule_interval(play_sound, 0.02)
pyglet.app.run()
```
I'm still looking into this.

**Comment by benmoran56** [comment]
@Fredkiss3 I can't get your example to crash. Could you please try again with the latest pyglet release and see if it's still an issue? 

By the way, it's not a good idea to keep all of those player instances indefinitely since the memory usage will slowly grow.

**Comment by Fredkiss3** [comment]
> By the way, it's not a good idea to keep all of those player instances indefinitely since the memory usage will slowly grow.

@benmoran56 , my game crashes if I don't keep a reference to all of those players, I think it is because of Python Garbage Collector 🤔. 

I'll try to upgrade to the latest release and run it again 👍

**Comment by benmoran56** [comment]
You do need to keep a reference to Player instances, or else they will be garbage collected as you said. If you want to play a sound without managing Players, you can simply call `source.play()`, and it will create a temporary player with it's own resource management. Alternatively, you can create a higher level abstraction if you want to have a bit more control. For example, this will reuse a few Players for sound effects, and also create a looping Player for a music track: 
```py
from collections import deque

class AudioPlayer:
    def __init__(self):
        # Create as many Players as you need simultaneous sounds:
        self.sfx_players = deque([pyglet.media.Player() for _ in range(8)])
        self.music_player = pyglet.media.Player()
        self.music_player.loop = True

    def set_volume(self, percentage):
        volume = max(min(1, percentage / 100), 0)
        for player in self.sfx_players:
            player.volume = volume
        self.music_player.volume = volume

    def play(self, source):
        player = self.sfx_players[0]
        player.queue(source=source)
        if not player.playing:
            player.play()
        self.sfx_players.rotate(1)

    def play_music(self, source):
        self.music_player.queue(source=source)
        if not self.music_player.playing:
            self.music_player.play()
        else:
            self.music_player.next_source()
```

**Comment by Fredkiss3** [comment]
@benmoran56 that seems to be a good solution. I'll try it

**Comment by Fredkiss3** [comment]
@benmoran56, Your solution was very helpful.
Do you know How Can I stop, pause and restart a player ?

**Comment by benmoran56** [comment]
You can access the `music_player` attribute on your instance of AudioPlayer. There is no `stop` method; you pause the Player and go to the next Source: 
```py
audio_player = AudioPlayer()
audio_player.music_player.pause()
audio_player.music_player.next_source()
```

**Comment by Fredkiss3** [comment]
Thanks a lot

**Comment by benmoran56** [comment]
No problem! If you're OK, please close the ticket. 

Also, if you use Discord, feel free to drop by our Discord server for general help with pyglet.

**Comment by Fredkiss3** [comment]
Can I have the link ?

**Comment by benmoran56** [comment]
Sure:  https://discord.gg/QXyegWe

**Comment by Fredkiss3** [comment]
Thanks
