### ISSUE TITLE
debugging pyglet on windows, I get a warning/exception related to COM/threading

### ISSUE THREAD

**Issue by ofer1992** [pyglet/pyglet#174]
Hey, I'm using pyglet as a media player for a program I'm writing, and I'm using PyQt5 for the GUI. I was having problems with the program getting stuck when running, and when debugging I got the following error:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\codecs\__init__.py", line 175, in add_default_media_codecs
    add_decoders(wmf)
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\codecs\__init__.py", line 128, in add_decoders
    for decoder in module.get_decoders():
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\codecs\wmf.py", line 887, in get_decoders
    return [WMFDecoder()]
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\codecs\wmf.py", line 833, in __init__
    raise(err)
  File "C:\Users\ofer\miniconda3\lib\site-packages\pyglet\media\codecs\wmf.py", line 831, in __init__
    ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set
Exception ignored in: <function WMFDecoder.__del__ at 0x000001BFF08F9318>
```
If I comment out the guilty line 
```
wmf.py:831 ole32.CoInitializeEx(None, COINIT_MULTITHREADED)
```
the program works fine in debug and regular mode.

The error is reproduced just by running this line in debug
```
import pyglet.media
```

I'm running on Windows 10 with python 3.7.6 and pyglet 1.5.2.

**Comment by caffeinepills** [comment]
You can only have one CoinitializeEx call in an application which sets the thread mode. Any additional calls to change the thread mode will throw an error. My guess is PyQT is calling and setting a differing thread mode on creation, which is why the WMF codec is throwing the error when it tries to do the same. 

I suppose it's an error that we can exception catch, however I have no clue how differing thread modes could affect the decoder.

**Comment by nzjrs** [comment]
Additionally, this causes a second crash at exit (when __del__) gets called. I'd say as this error is relatively harmless for the operation of pyglet it might be worth fixing the error in __del__ anyway

```python
    def __del__(self):
        try:
            self.MFShutdown()
            self.ole32.CoUninitialize()
        except AttributeError:
            # we didn't init correctly but __del__ still gets called
            pass
```

**Comment by caffeinepills** [comment]
Can you test if importing pyglet before pyqt fixes this? Thanks

**Comment by nzjrs** [comment]
FWIW
```
import PyQt5
import pyglet.media
```

and

```
import pyglet.media
import PyQt5
```

both pass.

The error must come from somewhere else in the enormous Pyschopy->wx->Qt dependency stack. In any case the `__del__` fix is correct and harmless IMO.

**Comment by jonathanjfshaw** [comment]
I just updated jupyterlab and now pyglet is crashing with this. Commenting out the line fixes it as @ofer1992 said.
