### ISSUE TITLE
Can I use Pyglet in Colab?

### ISSUE THREAD

**Issue by qo4on** [pyglet/pyglet#177]
I'm trying to use Pyglet in Colab. I did the following:
```
!sudo apt-get update --fix-missing && apt-get -qqq install x11-utils > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install xvfb > /dev/null
!python3 -m pip install -U -qqq moderngl
!python3 -m pip install -U -qqq moderngl-window
!python3 -m pip install -U -qqq pyvirtualdisplay

from pyvirtualdisplay import Display
display = Display(visible=0, size=(960, 540)).start()

import moderngl
ctx = moderngl.create_standalone_context()
buf = ctx.buffer(b'Hello World!')  # allocated on the GPU
buf.read()

b'Hello World!'
```
It printed as expected, but when I run an example I see the error:
```
!python3 /content/moderngl/examples/basic_alpha_blending.py --window pyglet

2020-03-28 10:25:48,312 - moderngl_window - INFO - Attempting to load window class: moderngl_window.context.pyglet.Window
Traceback (most recent call last):
  File "/content/moderngl/examples/basic_alpha_blending.py", line 74, in <module>
    AlphaBlending.run()
  File "/content/moderngl/examples/ported/_example.py", line 21, in run
    mglw.run_window_config(cls)
  File "/usr/local/lib/python3.6/dist-packages/moderngl_window/__init__.py", line 185, in run_window_config
    cursor=show_cursor if show_cursor is not None else True,
  File "/usr/local/lib/python3.6/dist-packages/moderngl_window/context/pyglet/window.py", line 54, in __init__
    config=config,
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 588, in __init__
    config = screen.get_best_config(config)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```
I also tried with another virtual display, but the result is the same:
```
!python3 -m pip install -U -qqq  xvfbwrapper
from xvfbwrapper import Xvfb
display = Xvfb(width=960, height=540).start()

pyglet.window.NoSuchConfigException
```
Can I use Pyglet to get hardware acceleration of Colab GPU?

  [1]: https://github.com/moderngl/moderngl

**Comment by einarf** [comment]
Related to https://github.com/moderngl/moderngl/issues/392

This happens because multisampling is enabled. Disabling multisampling solve the problem. It's probably just mesa software rendering on the server that don't support it.

**Comment by qo4on** [comment]
You mean it's impossible to get hardware rendering in Colab, right?

**Comment by einarf** [comment]
I think it should be possible. You showed examples ealier that indicated things were working just fine 😄 (Except for the `NoSuchConfigException`, but that you resolved).

You don't really need pyglet to do this, That's a bit overkill. standalone context is more than enough.

If you have questions avoid moderngl rendering it should probably be discussed in the other issue:
moderngl/moderngl#392

**Comment by qo4on** [comment]
It's not resolved. I'm still getting this error. I'm trying to run [animation tool](https://github.com/3b1b/manim/tree/shaders/manimlib) which already uses `pyglet` and `moderngl`. It returns the same error `NoSuchConfigException` in Colab. If I understand correctly, it happens because there is no `screen` in Colab.

**Comment by einarf** [comment]
I think this is a problem in the `manimlib` shader branch. It doesn't set the number of samples during window creation. You got `basic_alpha_blending.py --window pyglet --samples 0` running fine, so that points to an issue in `manimlib`. Do they have a configuration option for number of samples somewhere maybe?

**Comment by einarf** [comment]
I changed the default samples to 0 in moderngl-window master : https://github.com/moderngl/moderngl-window

Try to install that and see if it resolves the issue.

**Comment by qo4on** [comment]
Thanks. Unfortunatelly it didn't help.
```
!sudo apt-get update --fix-missing && apt-get -qqq install texlive-full > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install ffmpeg > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install sox > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install libcairo2-dev libjpeg-dev libgif-dev python3-dev libffi-dev > /dev/null
!python3 -m pip install -U -qqq argparse
!python3 -m pip install -U -qqq colour
!python3 -m pip install -U -qqq numpy
!python3 -m pip install -U -qqq Pillow
!python3 -m pip install -U -qqq progressbar
!python3 -m pip install -U -qqq scipy
!python3 -m pip install -U -qqq tqdm
!python3 -m pip install -U -qqq opencv-python
!python3 -m pip install -U -qqq pycairo
!python3 -m pip install -U -qqq pydub

!sudo apt-get update --fix-missing && apt-get -qqq install x11-utils > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install xvfb > /dev/null
!python3 -m pip install -U -qqq moderngl
!python3 -m pip install -U -qqq moderngl-window
!python3 -m pip install -U -qqq mapbox-earcut
!python3 -m pip install -U -qqq pyvirtualdisplay

RESTART RUNTIME
!git clone -qqq --single-branch --branch shaders https://github.com/3b1b/manim.git > /dev/null

%cd /content/manim

from pyvirtualdisplay import Display
display = Display(visible=0, size=(960, 540))
display.start()

from manimlib.imports import *

!python3 -m manim example_scenes.py WarpSquare

Media will be written to ./media/. You can change this behavior with the --media_dir flag.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/manim/manim.py", line 5, in <module>
    manimlib.main()
  File "/content/manim/manimlib/__init__.py", line 11, in main
    scenes = manimlib.extract_scene.main(config)
  File "/content/manim/manimlib/extract_scene.py", line 104, in main
    scenes = get_scenes_to_render(all_scene_classes, config)
  File "/content/manim/manimlib/extract_scene.py", line 72, in get_scenes_to_render
    scene = scene_class(**scene_kwargs)
  File "/content/manim/manimlib/scene/scene.py", line 44, in __init__
    self.window = Window(self, **self.window_config)
  File "/content/manim/manimlib/window.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/moderngl_window/context/pyglet/window.py", line 54, in __init__
    config=config,
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 588, in __init__
    config = screen.get_best_config(config)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```

**Comment by einarf** [comment]
I don't see you installing moderngl-window from master branch here?

I think you should also consiering opening an issue in the manim project and link to the isses you created in mdoerngl and pyglet. I don't really know how Colab works, but suspect the best solution would be for manim to support a headless window backend in this instance.

**Comment by qo4on** [comment]
It's not working.
```
!sudo apt-get update --fix-missing && apt-get -qqq install texlive-full > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install ffmpeg > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install sox > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install libcairo2-dev libjpeg-dev libgif-dev python3-dev libffi-dev > /dev/null
!python3 -m pip install -U -qqq argparse
!python3 -m pip install -U -qqq colour
!python3 -m pip install -U -qqq numpy
!python3 -m pip install -U -qqq Pillow
!python3 -m pip install -U -qqq progressbar
!python3 -m pip install -U -qqq scipy
!python3 -m pip install -U -qqq tqdm
!python3 -m pip install -U -qqq opencv-python
!python3 -m pip install -U -qqq pycairo
!python3 -m pip install -U -qqq pydub

!sudo apt-get update --fix-missing && apt-get -qqq install x11-utils > /dev/null
!sudo apt-get update --fix-missing && apt-get -qqq install xvfb > /dev/null
!python3 -m pip install -U -qqq moderngl
!python3 -m pip install -qqq git+https://github.com/moderngl/moderngl-window.git > /dev/null
!python3 -m pip install -U -qqq mapbox-earcut
!python3 -m pip install -U -qqq pyvirtualdisplay

%cd /content/manim

from pyvirtualdisplay import Display
display = Display(visible=0, size=(960, 540)).start()

from manimlib.imports import *

!python3 -m manim example_scenes.py WarpSquare

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/manim/manim.py", line 5, in <module>
    manimlib.main()
  File "/content/manim/manimlib/__init__.py", line 11, in main
    scenes = manimlib.extract_scene.main(config)
  File "/content/manim/manimlib/extract_scene.py", line 104, in main
    scenes = get_scenes_to_render(all_scene_classes, config)
  File "/content/manim/manimlib/extract_scene.py", line 72, in get_scenes_to_render
    scene = scene_class(**scene_kwargs)
  File "/content/manim/manimlib/scene/scene.py", line 44, in __init__
    self.window = Window(self, **self.window_config)
  File "/content/manim/manimlib/window.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/moderngl_window/context/pyglet/window.py", line 56, in __init__
    config=config,
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py", line 588, in __init__
    config = screen.get_best_config(config)
  File "/usr/local/lib/python3.6/dist-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```
Can you suggest me how to setup a headless window backend with with `moderngl-window`?

**Comment by einarf** [comment]
It's mentioned in docs:
https://moderngl-window.readthedocs.io/en/stable/guide/window_guide.html (You need to use the `.headless.Window` backend)

I also linked the `custom_config*` examples earlier : https://github.com/moderngl/moderngl-window/tree/master/examples.  These can be copy pasted to test headless if you remove the input and window events (they do nothing in headless mode).

Anyway. I think this is a Manim + moderngl-window issue, so maybe close this issue and instead discuss it in the right projects.

**Comment by qo4on** [comment]
Ok, thanks.
