### ISSUE TITLE
Offscreen/server side rendering issue

### ISSUE THREAD

**Issue by rudrapoudel** [pyglet/pyglet#202]
I am having problem on remote server side rendering on Ubuntu 16.04, pyglet 1.5.0,

**Minimum Code**
```
import pyglet
import numpy as np

image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
arr = np.fromstring(image_data.get_data(), dtype=np.uint8, sep='')

print(type(arr))
print(arr.shape)
print(arr)
```

**Expected**
```
<class 'numpy.ndarray'>
(4,)
[  0   0   0 255]
```

**Remote Script Execution Command**
`xvfb-run -s "-screen 0 1400x900x24" python debug-gym.py`
Or,
`xvfb-run -a -s "-screen 0 1400x900x24" python debug-gym.py`

Output either,
```
Traceback (most recent call last):
  File "debug-pyglet.py", line 4, in <module>
    image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
  File "/home/rpoudel/miniconda3/envs/py35-w/lib/python3.5/site-packages/pyglet/image/__init__.py", line 2035, in get_image_data
    buffer = (GLubyte * (len(self.format) * self.width * self.height))()
ValueError: Array length must be >= 0, not -244212822997920
```

Or,
```
<class 'numpy.ndarray'>
(0,)
[]
```

**Comment by benmoran56** [comment]
I tried this and it works as expected for me: 
```py
<class 'numpy.ndarray'>
(4,)
[  0   0   0 255]
```
I have `xorg-server-xvfb-1.20.8-2-x86_64` installed on my machine. The issue could be with either with xvfb, or with the driver stack on the machine you are remoting into.

**Comment by rudrapoudel** [comment]
Thanks @benmoran56, my above excepted output was also produced on an Ubuntu server with version 18.04 which also has Xorg version 1.20.x.. But not working in Ubuntu 16, in which currently you can install only up to Xorg 1.19.x (ruling out self rebuild option).

Does this means we must need Xorg >=1.20.x? aka Ubuntu >=18?

**Comment by benmoran56** [comment]
I don't use xvfb myself, but it would make sense that the older version has issues. Unfortunately I don't have any way to confirm that at the moment.
