### ISSUE TITLE
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None" in Linux (Manjaro).

### ISSUE THREAD

**Issue by retrosnob** [pyglet/pyglet#206]
Happens immediately I try to import Window from pyglet.window.

**Comment by benmoran56** [comment]
Are you able to post the output of `python -m pyglet.info`? 
It sounds like an issue with the graphics stack. Can you also paste the output of:
`glxinfo |grep OpenGL`

**Comment by retrosnob** [comment]
Thanks for getting back to me. I should tell you that I have three displays, but the problem happens whether or not they are connected.

python -m pyglet.info
```
release:   4.19.113-1-MANJARO
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130]
sys.maxint: 9223372036854775807
os.getcwd(): /home/justin/Dropbox/jr/py/pyglet_games/snake

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.5.2
pyglet.compat_platform: linux
pyglet.__file__: /home/justin/.local/lib/python3.8/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_x11'] = False
pyglet.options['graphics_vbo'] = True
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['darwin_cocoa'] = True
pyglet.options['search_local_libs'] = True

pyglet.window
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/info.py", line 225, in _try_dump
    func()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/info.py", line 97, in dump_window
    import pyglet.window
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1891, in <module>
    gl._create_shadow_window()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 573, in __init__
    display = pyglet.canvas.get_display()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

pyglet.gl.glu_info
------------------------------------------------------------------------------
/home/justin/.local/lib/python3.8/site-packages/pyglet/gl/glu_info.py:123: UserWarning: No GL context created yet.
  warnings.warn('No GL context created yet.')
glu_info.get_version(): 0.0.0
glu_info.get_extensions():
/home/justin/.local/lib/python3.8/site-packages/pyglet/gl/glu_info.py:148: UserWarning: No GL context created yet.
  warnings.warn('No GL context created yet.')

pyglet.gl.glx_info
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/info.py", line 225, in _try_dump
    func()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/info.py", line 148, in dump_glx
    window = pyglet.window.Window(visible=False)
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 573, in __init__
    display = pyglet.canvas.get_display()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/justin/.local/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

pyglet.media
------------------------------------------------------------------------------
error: failed to expand CURIE `xsd:float'
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x7fa9ff5ee040>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: n4.2.2

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 55b0eb48a000 at 0x7fa9ff5e6b50>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```
glxinfo | grep OpenGL
`Error: unable to open display `

**Comment by benmoran56** [comment]
If `glxinfo` doesn't work, it means it's a driver related issue. `pyglet` is not yet Wayland native, so you'll need to have the xorg stack installed if you're using a Wayland based system. In that case XWayland is used.  If that's not it, then it means it's something else related to OpenGL.

**Comment by retrosnob** [comment]
Thanks for getting back to me. I'm using XFCE on Manjaro. Doesn't seem to be Wayland. Any ideas how I might proceed?
```
$ loginctl show-session 2 -p Type
Type=x11
```

**Comment by retrosnob** [comment]
Graphics card is Intel HD Graphics 620, which claims to support OpenGL 4.4.

**Comment by benmoran56** [comment]
Is this a remote session by any chance? If so that might be the issue. 

If it's a local session, it really seems that the graphics driver stack isn't fully installed. On a system with Xorg, `glxinfo` should at least run and give you the driver details. Even if it's only software rending due to lack of OpenGL drivers, you should still be getting something. The `unable to open display` message is a strong indication that something's incomplete. Maybe xorg-server needs to be reconfigured, or the correct `xf86-video-XXXX` driver needs to be installed.  

For what it's worth, pyglet does work fine on Arch based systems under both X and Wayland (with XWayland) as I run Arch myself on several machines.

**Comment by retrosnob** [comment]
Not a remote session. I do seem to remember having some problems with updating graphics card drivers a year or so back so perhaps I did something wrong there. I'll tinker about and see what happens. Thanks for trying to help.

**Comment by benmoran56** [comment]
No worries. Even though you're on Manjaro, give the Arch Linux wiki a look. It has pretty detailed information about getting the right drivers installed during installation.
