### ISSUE TITLE
undefined symbol: av_packet_free

### ISSUE THREAD

**Issue by AntiSol** [pyglet/pyglet#235]
Hi,

Thanks for pyglet, it looks like a useful framework.
I was just having a look around to get acquainted with it but I'm having a problem with ffmpeg.
Maybe the version of ffmpeg I have installed is older than you're expecting? I'm running ubuntu 16.04 and I have ffmpeg 2.8.15 installed.
I did 'pip install pyglet', then I downloaded examples/media_player.py from the repo. Then I ran
'./media_player.py /path/to/file.mkv' but it gives me the following output:
````
Traceback (most recent call last):
  File "media_player.py", line 66, in <module>
    from pyglet.media import buffered_logger as bl
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/__init__.py", line 180, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/__init__.py", line 196, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 389, in <module>
    avcodec.av_packet_free.argtypes = [POINTER(POINTER(AVPacket))]
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56: undefined symbol: av_packet_free
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/__init__.py", line 180, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/__init__.py", line 196, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/usr/local/lib/python3.5/dist-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 389, in <module>
    avcodec.av_packet_free.argtypes = [POINTER(POINTER(AVPacket))]
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56: undefined symbol: av_packet_free
````
This happens no matter what media file I try to play (audio, video, different formats, etc).
I had a look at the ffmpeg download page to see if I can upgrade to a newer version, but 2.8.15 is the latest version they have in the repos and I'd rather not upgrade outside of the package management system. I'm not sure what I should try next? Any ideas would be helpful. 

Hopefully I haven't missed something obvious. Thanks for your time.

**Comment by benmoran56** [comment]
Thanks for opening the ticket. Unfortunately 2.8.15 is not supported. The FFmpeg decoder requires the newer 4.x release. 
https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#ffmpeg-installation

If you want to stick to the package manager, the easiest solution would be to add a PPA such as this one: 
https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4
(I haven't personally tested that PPA). 
PPAs are easy enough to remove in case you have trouble with some other applications relying on older FFmpeg:
https://askubuntu.com/questions/307/how-can-ppas-be-removed#310

If you prefer you can compile the standalone FFmpeg utility **so**s and place them directly in your `project/libs/` folder. From there you would use the `pyglet.options['search_local_libs']` option as described in the documentation.

**Comment by AntiSol** [comment]
Hi, thanks for the reply :)

That explains it, and your response is really great with the wrt the available options, ppas and compiling the libs myself. Thanks!

Looking at it again I do see you mention in the documentation:
````
 You must choose the shared build for the targeted OS with the architecture similar to the Python interpreter.

This means that the major version must be 4.X. 
````

Obviously I missed that. You may want to consider rearranging the documentation slightly to separate the requirement for v4.x out from the rest of the text and/or to make it a bit more prominent. If it had been a heading, or listed under the requirements / installation section at https://pyglet.readthedocs.io/en/latest/programming_guide/installation.html I might have noticed and might not have bugged you by opening a ticket. ;)

I also feel that the "this means that the major version must be 4.x" doesn't really follow - what means that the minimum version is 4.x? the fact that I need to download for the appropriate architecture? I feel like maybe there's a sentence missing there.

This is just a suggestion for your consideration,  it's no big deal either way. 

Thanks very much for your time :)
