### ISSUE TITLE
Modifying Label or Batch from another Thread causes Error

### ISSUE THREAD

**Issue by finn307** [pyglet/pyglet#244]
I experienced some problems when using threads and wrote these two test scripts to figure out if there could be a problem in general. It seems like this to me.

Here are the two test scripts and the error-message proues by each one:

_Label:_
```
import pyglet
import threading

window = pyglet.window.Window()

label_val = 0
label = pyglet.text.Label('0', x=100, y=100)


def increase():
    global label_val
    label_val += 1
    label.text = str(label_val)


@window.event
def on_draw():
    window.clear()
    label.draw()


@window.event
def on_key_press(symbol, modifiers):
    thread = threading.Thread(target=increase)
    thread.start()


pyglet.app.run()
```
_-> gives following error-message:_
```

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Finn/Data/PythonProjects/_tests/TicTacToeOnline/test.py", line 13, in increase
    label.text = str(label_val)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\__init__.py", line 289, in text
    self.document.text = text
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\document.py", line 294, in text
    self.insert_text(0, text)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\document.py", line 425, in insert_text
    self.dispatch_event('on_insert_text', start, text)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\layout.py", line 1045, in on_insert_text
    self._init_document()
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\layout.py", line 1034, in _init_document
    self._update()
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\layout.py", line 957, in _update
    lines = self._get_lines()
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\layout.py", line 933, in _get_lines
    glyphs = self._get_glyphs()
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\text\layout.py", line 1076, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\font\base.py", line 386, in get_glyphs
    self.glyphs[c] = glyph_renderer.render(c)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\font\win32.py", line 465, in render
    glyph = self.font.create_glyph(image)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\font\base.py", line 345, in create_glyph
    glyph = texture.fit(image)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\font\base.py", line 246, in fit
    region.blit_into(image, 0, 0, 0)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\image\__init__.py", line 1730, in blit_into
    self.owner.blit_into(source, x + self.x, y + self.y, z + self.z)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\image\__init__.py", line 1622, in blit_into
    glBindTexture(self.target, self.id)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\gl\lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'Der Vorgang ist ung\xfcltig.'
```
_Batch:_
```
import pyglet
import threading

window = pyglet.window.Window()

batch = pyglet.graphics.Batch()


def increase():
    batch.add(2, pyglet.gl.GL_LINES, None,
              ('v2i', (100, 100, 200, 100)),
              ('c3B', (255, 255, 255) * 2))


@window.event
def on_draw():
    window.clear()
    batch.draw()


@window.event
def on_key_press(symbol, modifiers):
    thread = threading.Thread(target=increase)
    thread.start()


pyglet.app.run()
```  
_-> gives following error-message:_
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\__init__.py", line 449, in _get_domain
    domain = domain_map[key]
KeyError: (('v2i', 'c3B'), 1, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Finn/Data/PythonProjects/_tests/TicTacToeOnline/test2.py", line 12, in increase
    ('c3B', (255, 255, 255) * 2))
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\__init__.py", line 365, in add
    domain = self._get_domain(False, mode, group, formats)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\__init__.py", line 455, in _get_domain
    domain = vertexdomain.create_domain(*formats)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexdomain.py", line 134, in create_domain
    return VertexDomain(attribute_usages)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexdomain.py", line 185, in __init__
    usage=usage, vbo=vbo)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 110, in create_mappable_buffer
    return MappableVertexBufferObject(size, target, usage)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 384, in __init__
    super(MappableVertexBufferObject, self).__init__(size, target, usage)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 299, in __init__
    glGenBuffers(1, id)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\gl\lib_wgl.py", line 103, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\gl\lib.py", line 60, in MissingFunction
    raise MissingFunctionException(name, requires, suggestions)
pyglet.gl.lib.MissingFunctionException: glGenBuffers is not exported by the available OpenGL driver.  VERSION_1_5 is required for this functionality.

Exception ignored in: <function VertexDomain.__del__ at 0x000001CD8BB45CA8>
Traceback (most recent call last):
  File "C:\Users\Finn\Data\PythonProjects\_tests\TicTacToeOnline\venv\lib\site-packages\pyglet\graphics\vertexdomain.py", line 232, in __del__
    for attribute in self.attributes:
AttributeError: 'VertexDomain' object has no attribute 'attributes'

Process finished with exit code -1
```
_Using: Pyglet 1.5.7, Python 3.7.8_

I also tested both versions without using a thread to ensure there is no other error.
Having the ability to modify displayed data from another thread would be great and really helpful!

**Comment by DoAltPlusF4** [comment]
I don't think this is an issue with pyglet, and more OpenGL itself (the graphics library pyglet uses).

I would recommend that you schedule the batch/group adjustments using pyglet.clock so that they run on the main thread or the same thread as the batch creation.

**Comment by DoAltPlusF4** [comment]
Label with Scheduling: 
```py
import pyglet
import threading

window = pyglet.window.Window()

label_val = 0
label = pyglet.text.Label('0', x=100, y=100)


def increase():
    global label_val
    label_val += 1
    def modify(dt):
        label.text = str(label_val)
    pyglet.clock.schedule_once(modify, 0)


@window.event
def on_draw():
    window.clear()
    label.draw()


@window.event
def on_key_press(symbol, modifiers):
    thread = threading.Thread(target=increase)
    thread.start()


pyglet.app.run()
```

**Comment by DoAltPlusF4** [comment]
Batch with Scheduling:
```py
import pyglet
import threading

window = pyglet.window.Window()

batch = pyglet.graphics.Batch()


def increase():
    def modify(dt):
        batch.add(2, pyglet.gl.GL_LINES, None,
                  ('v2i', (100, 100, 200, 100)),
                  ('c3B', (255, 255, 255) * 2))
    pyglet.clock.schedule_once(modify, 0)


@window.event
def on_draw():
    window.clear()
    batch.draw()


@window.event
def on_key_press(symbol, modifiers):
    thread = threading.Thread(target=increase)
    thread.start()


pyglet.app.run()
```

**Comment by finn307** [comment]
Ok, than I'll do it like you have shown. Thanks for your answer!

**Comment by DoAltPlusF4** [comment]
@finn307 remember that the effect wont take place until the next tick, I forgot to mention this earlier

**Comment by matanster** [comment]
Thank you, this was very illustrative. 

That said wouldn't using a thread (which is not the main thread) undo some consistency guarantees that you get in the main thread's event loop though? namely the atomicity of event loop callback executions or the stability of its update/draw callback rate?
