### ISSUE TITLE
Import Error: Can't find framework %s." % path

### ISSUE THREAD

**Issue by akarsh1995** [pyglet/pyglet#274]
When I try to run `from pyglet.gl import *`

The code line 262 tries to find OpenGL inside the directory `/System/Library/Frameworks/OpenGL.framework`. 
https://github.com/pyglet/pyglet/blob/d563b7a001506758a77fde035c22c786476d0093/pyglet/lib.py#L262
The function `return None` which in turn `raise ImportError("Can't find framework %s." % path) # on line 283`

-----
**System Information**

OS: Mac OS Big Sur Public 11.0 Beta (20A5354i).

```sh
Darwin Akarshs-MacBook-Pro.local 20.0.0 Darwin Kernel Version 20.0.0: Fri Aug 14 00:25:13 PDT 2020; root:xnu-7195.40.44.151.1~4/RELEASE_X86_64 x86_64
```

Tree structure of the dir `/System/Library/Frameworks/OpenGL.framework` in my system. 
```sh
 akarshjain@Akarshs-MacBook-Pro  /System/Library/Frameworks/OpenGL.framework  tree 
.
├── Libraries -> Versions/Current/Libraries
├── Resources -> Versions/Current/Resources
└── Versions
    ├── A
    │   ├── Libraries
    │   │   ├── 3425AMD
    │   │   │   ├── CVMCompiler
    │   │   │   └── libCoreVMClient.mono.dylib
    │   │   ├── 3600
    │   │   │   ├── CVMCompiler
    │   │   │   └── libCoreVMClient.mono.dylib
    │   │   ├── CVMCompiler
    │   │   ├── CVMServer
    │   │   ├── DumpGPURestart
    │   │   ├── ReportGPURestart
    │   │   ├── libGLVMPlugin.dylib
    │   │   ├── libGLVMPlugin31001.dylib
    │   │   ├── libGLVMPlugin3802.dylib
    │   │   └── libGLVMPlugin3902.dylib
    │   ├── Resources
    │   │   ├── BridgeSupport
    │   │   │   └── OpenGL.bridgesupport
    │   │   ├── CVMSPlugin.exp
    │   │   ├── CVMSPluginAll.exp
    │   │   ├── CVMSPluginNoExec.exp
    │   │   ├── GLByteCodes.arm64.bc
    │   │   ├── GLByteCodes.x86_64.bc
    │   │   ├── GLEngine.bundle
    │   │   │   └── GLEngine
    │   │   ├── GLRendererFloat.bundle
    │   │   │   └── GLRendererFloat
    │   │   ├── Info.plist
    │   │   ├── cvmsConfig.plist
    │   │   └── version.plist
    │   └── _CodeSignature
    │       └── CodeResources
    └── Current -> A

```

**Comment by benmoran56** [comment]
I don't have a Mac to test this on, but there is this comment under "Known Issues" for the Big Sur beta:

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

I don't know if this is the issue or not, but might be worth looking into. `pyglet.lib` could be modified to return the fully formed path, even though it doesn't find anything.

**Comment by akarsh1995** [comment]
> I don't have a Mac to test this on, but there is this comment under "Known Issues" for the Big Sur beta:
> 
> > New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)
> 
> I don't know if this is the issue or not, but might be worth looking into. `pyglet.lib` could be modified to return the fully formed path, even though it doesn't find anything.

Most likely it's going to be the same in stable Big Sur release. So the issue should be addressed, I guess.

Is there any hack to solve this issue as of now ?

**Comment by elliotwaite** [comment]
> I don't know if this is the issue or not, but might be worth looking into. `pyglet.lib` could be modified to return the fully formed path, even though it doesn't find anything.

I tried changing this (in `pyglet/gl/lib_agl.py`):
```
gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')
agl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/AGL.framework')
```
To this:
```
gl_lib = '/System/Library/Frameworks/OpenGL.framework/OpenGL'
agl_lib = '/System/Library/Frameworks/AGL.framework/AGL'
```
But now I get a new error:
```
pyglet.gl.lib.MissingFunctionException: glGetString is not exported by the available OpenGL drive
```
Stack trace:
```
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 243, in <module>
    import pyglet.window
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1897, in <module>
    gl._create_shadow_window()
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 648, in __init__
    self._create()
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/window/cocoa/__init__.py", line 197, in _create
    self.context.attach(self.canvas)
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/cocoa.py", line 293, in attach
    self.set_current()
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/cocoa.py", line 301, in set_current
    super(CocoaContext, self).set_current()
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/base.py", line 333, in set_current
    gl_info.set_active_context()
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/gl_info.py", line 91, in set_active_context
    self.vendor = asstr(cast(glGetString(GL_VENDOR), c_char_p).value)
  File "/Users/elliotwaite/miniconda3/lib/python3.7/site-packages/pyglet/gl/lib.py", line 60, in MissingFunction
    raise MissingFunctionException(name, requires, suggestions)
pyglet.gl.lib.MissingFunctionException: glGetString is not exported by the available OpenGL driver.
```

**Comment by ebolotin6** [comment]
I am facing the same issue. Using the official release of macOS Big Sur.

**Comment by Francoisgoujon** [comment]
I'm also facing the same issue using the official release of macOS Big Sur. 

I'm trying to run env.render() from Gym OpenAI environments but I get this error :

```
Traceback (most recent call last):
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/pyglet/lib.py", line 279, in load_framework
    raise ImportError("Can't find framework %s." % path)
ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pallet.py", line 222, in <module>
    env.render()
  File "/Users/francoisgoujon/RL_Pallet/gym_pallet/envs/pallet_env.py", line 142, in render
    from gym.envs.classic_control import rendering
  File "/Users/francoisgoujon/RL_Pallet/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 32, in <module>
    ''')
ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
```

I checked /System/Library/Frameworks/OpenGL.framework and everything seems to be good in the folder. 
Can't find any solutions..

**Comment by Francoisgoujon** [comment]
Just found a quick fix : go into pyglet/lib.py file and look for the `find_framework(path)` function. Then comment the body of the function and just return the path to OpenGL.framework : 
```
def find_framework(path):
        """Implement runtime framework search as described by:

        http://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkBinding.html
        """
        return '/System/Library/Frameworks/OpenGL.framework/OpenGL'
```

**Comment by benmoran56** [comment]
We have a pull request open to fix this: 
https://github.com/pyglet/pyglet/pull/284

I've just been waiting to get confirmation that it doesn't break older OSX versions. If anyone here has access to previous releases, and can test it, then we can get that merged in.

**Comment by benmoran56** [comment]
Also, If anyone wants to test but needs help, please let me know!

**Comment by ebolotin6** [comment]
Hi, I volunteer to test this. I have two machines: one runs macOS 11.0.1 (Big Sur) and the other 10.15.7 (Catalina). 

Do you have any specific instructions for me to test?

**Comment by garyguo1998** [comment]
> I am facing the same issue. Using the official release of macOS Big Sur.

Me, too

**Comment by einarf** [comment]
This works fine for me on Catalina 10.15.7

**Comment by MichaelFeng1997** [comment]
> Just found a quick fix : go into pyglet/lib.py file and look for the `find_framework(path)` function. Then comment the body of the function and just return the path to OpenGL.framework :
> 
> ```
> def find_framework(path):
>         """Implement runtime framework search as described by:
> 
>         http://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkBinding.html
>         """
>         return '/System/Library/Frameworks/OpenGL.framework/OpenGL'
> ```

produce new error for me

**Comment by benmoran56** [comment]
I've merged in the fix from Jerekshoe, which will be in the next point release. My understanding is that this should fix things ONLY for the system Python in Big Sur. Other Python releases will need to wait for upstream CPython fixes. 

@ebolotin6 sorry for not getting back to you sooner, but luckily some others have been able to test.

**Comment by romiller872** [comment]
Recently updated to macOS BigSur and facing similar problems:

ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.

and 

ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
    
I'm pretty new to this stuff so I'm having a hard time fixing these problems.
Can anyone help me?

**Comment by benmoran56** [comment]
@romiller872 Can you post the full traceback?

**Comment by romiller872** [comment]
> @romiller872 Can you post the full traceback?
Thanks for the quick reply.
The full traceback is this:

[
  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 279, in load_framework
    raise ImportError("Can't find framework %s." % path)

ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/romiller/Documents/7. Semester/HiWi Keffi/Beispiele/MountainCar_DQN/dqn_MountainCar.py", line 291, in <module>
    env.render()   # animate mountaincar

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/core.py", line 233, in render
    return self.env.render(mode, **kwargs)

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/mountain_car.py", line 78, in render
    from gym.envs.classic_control import rendering

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    raise ImportError('''

ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'

](url)

**Comment by romiller872** [comment]
> @romiller872 Can you post the full traceback?
Thanks for your quick reply.
this is the full traceback I get:

`
  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 279, in load_framework
    raise ImportError("Can't find framework %s." % path)

ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/romiller/Documents/7. Semester/HiWi Keffi/Beispiele/MountainCar_DQN/dqn_MountainCar.py", line 291, in <module>
    env.render()   # animate mountaincar

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/core.py", line 233, in render
    return self.env.render(mode, **kwargs)

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/mountain_car.py", line 78, in render
    from gym.envs.classic_control import rendering

  File "/Users/romiller/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    raise ImportError('''

ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
    `

**Comment by geekstor** [comment]
I have also been trying to fix these errors while trying to render in Gym and I found that two fixes are needed: 

1) Changing the find_framework function in lib.py in site-packages/pyglet to the following (as mentioned above): 

`def find_framework(path):
        return '/System/Library/Frameworks/OpenGL.framework/OpenGL'` 

As @MichaelFeng1997 says, a different error then appears when trying to load things from the AppKit framework: 

`ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found`

2) Changing the first line of APPLICATION KIT (line 197) of site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py to the following then fixes the remaining error and I have Gym rendering now working!:

`appkit = cdll.LoadLibrary('/System/Library/Frameworks/AppKit.framework/AppKit')`

It seems that this change in loading from dynamic libraries is affecting many repos., but the fixes aren't too bad.

Hope that helps anyone with the same problem!

**Comment by ebolotin6** [comment]
> I've merged in the fix from Jerekshoe, which will be in the next point release. My understanding is that this should fix things ONLY for the system Python in Big Sur. Other Python releases will need to wait for upstream CPython fixes.
> 
> @ebolotin6 sorry for not getting back to you sooner, but luckily some others have been able to test.

Thanks @benmoran56! Yes, I think the key takeaway for me is that I will need to wait for upstream CPython fixes, as I am not using system Python in Big Sur.

**Comment by cosmir17** [comment]
@ebolotin6 If you can't wait, you can do what 'geekstor' said. This worked for me on Big Sur.
You probably need to run 'XQuartz' while you run your Python program.

**Comment by benmoran56** [comment]
Hardcoding the path can work for the time being, but once the CPython fixes make their way out pyglet should work again without any hacks (point release due out soon). Lets leave this issue open until that starts happening. 

If anyone wants to check if their Python is working, try this simple test: 
```py
import ctypes.util
path = ctypes.util.find_library('ssl')
print(f'Library path: {path}')
```
If it returns `None`, it doesn't have the fix.
Currently, only the OSX **system bundled** Python is working at the moment. 

For reference, the CPython issue can be found here:   https://bugs.python.org/issue41100

**Comment by ulfarsson** [comment]
If I run the code snipped you posted @benmoran56 I get
```
Library path: /usr/lib/libssl.dylib
```
However, when running
```python
from pyglet.gl import *
```
I get the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/usr/local/lib/python3.9/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/usr/local/lib/python3.9/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')
  File "/usr/local/lib/python3.9/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])
  File "/usr/local/lib/python3.9/site-packages/pyglet/lib.py", line 279, in load_framework
    raise ImportError("Can't find framework %s." % path)
ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.
```
I'm running this on macOS Big Sur with Python3 from Homebrew
```
Python 3.9.0 (default, Nov 14 2020, 10:50:03)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
```

**Comment by benmoran56** [comment]
@ulfarsson Make sure to update to the latest pyglet release (v1.5.10).

```py
import pyglet
print(pyglet.version)
```

**Comment by ulfarsson** [comment]
Thanks! Didn't realize that was out on PyPI. It now seems to work for me, but still throws a weird message
```python
>>> from pyglet.gl import *
2020-11-16 07:51:49.131 Python[46073:514505] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/2v/xbyy0mfx3rqfw2w9y_1kf2kr0000gp/T/org.python.python.savedState
```

**Comment by jerekshoe** [comment]
@ulfarsson I believe that message is normal. I've always had it at least

**Comment by benmoran56** [comment]
pyglet v1.5.11 was just released. This contains additional fallbacks for locating the libraries. Could everyone that is still having trouble give it a try, and let us know how it goes?

**Comment by ebolotin6** [comment]
Works like a charm!!!! Early-adopter hell might be over for the time being. Thank you!!

**Comment by ulfarsson** [comment]
Works for me!

**Comment by peircej** [comment]
Well done y'all on getting this fixed quick! 🚀

**Comment by cosmir17** [comment]
It works for me without any hack 🥇 👍

**Comment by benmoran56** [comment]
Thanks for the feedback everyone. I'll close this for now, but please feel free to follow up if you have any other issues.

**Comment by bernakabadayi** [comment]
worked for me, thanks a lot!

**Comment by vorg-san** [comment]
On macos Bigsur 11.1, after upgrading to pyglet==1.5.11, when running openai's gym env.render() I get the error: 

`File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 234, in <module>
    from .cocoa import CocoaConfig as Config
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/gl/cocoa.py", line 44, in <module>
    from pyglet.canvas.cocoa import CocoaCanvas
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 102, in <module>
    from pyglet.canvas.cocoa import CocoaDisplay as Display
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/canvas/cocoa.py", line 41, in <module>
    from pyglet.libs.darwin.cocoapy import CGDirectDisplayID, quartz, cf
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
    from .cocoapy import *
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 32, in <module>
    from .runtime import objc, send_message, send_super
  File "/Users/dangab/Envs/tensorflow_macos/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 133, in <module>
    objc.class_getMethodImplementation_stret.restype = c_void_p
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1045f9aa0, class_getMethodImplementation_stret): symbol not found`

**Comment by xuhao121** [comment]
> 

I have the same problem as above, but I have no property to change the file in another computer, can anyone tell me is there any solution to solve this?
