### ISSUE TITLE
"ValueError: Can only assign sequence of same size" when changing circle's visible attribute

### ISSUE THREAD

**Issue by harrrson** [pyglet/pyglet#293]
When i try to change 'visible' attribute of Circle instance, i have traceback:

_Traceback (most recent call last):
  File "/data/Atom projekty/AI samochodzik/main.py", line 33, in <module>
    random_dot.visible = False
  File "/home/piotr/venv-TF-samochodzik/lib/python3.8/site-packages/pyglet/shapes.py", line 307, in visible
    self._update_position()
  File "/home/piotr/venv-TF-samochodzik/lib/python3.8/site-packages/pyglet/shapes.py", line 417, in _update_position
    self._vertex_list.vertices[:] = vertices
ValueError: Can only assign sequence of same size
[Finished in 0.466s]_

Class declaration:
_main.py_
```
random_dot = pyglet.shapes.Circle(x=50,
                                  y=50,
                                  radius=30,
                                  batch=batch_car,
                                  group=foreground)
random_dot.visible = False
```
pyglet version is 1.5.8

**Comment by LennyPhoenix** [comment]
Can confirm this:
```py
>>> import pyglet
>>> window = pyglet.window.Window()
>>> batch = pyglet.graphics.Batch()
>>> @window.event
... def on_draw():
...     window.clear()
...     batch.draw()
...
>>> group = pyglet.graphics.Group()
>>> circle = pyglet.shapes.Circle(x=50, y=50, radius=30, batch=batch, group=group)
>>> circle.visible = False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lenny\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\shapes.py", line 307, in visible
    self._update_position()
  File "C:\Users\Lenny\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\shapes.py", line 417, in _update_position
    self._vertex_list.vertices[:] = vertices
ValueError: Can only assign sequence of same size
```
Ill take a look and see what could be causing this.

**Comment by LennyPhoenix** [comment]
Can confirm this:
```py
>>> import pyglet
>>> window = pyglet.window.Window()
>>> batch = pyglet.graphics.Batch()
>>> @window.event
... def on_draw():
...     window.clear()
...     batch.draw()
...
>>> group = pyglet.graphics.Group()
>>> circle = pyglet.shapes.Circle(x=50, y=50, radius=30, batch=batch, group=group)
>>> circle.visible = False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lenny\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\shapes.py", line 307, in visible
    self._update_position()
  File "C:\Users\Lenny\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\shapes.py", line 417, in _update_position
    self._vertex_list.vertices[:] = vertices
ValueError: Can only assign sequence of same size
```
Ill take a look and see what could be causing this.

**Comment by LennyPhoenix** [comment]
This problem should now be solved, let me know if it still appears to be broken.

**Comment by benmoran56** [comment]
This fix is in the latest release. Thanks Lenny!
