### ISSUE TITLE
take snapshot broken with latest pillow

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#297]
Take snapshot broken with latest pillow; to repro add to noisy.py's on_key_press handler the lines
```python
    elif symbol == key.RETURN:
        pyglet.image.get_buffer_manager().get_color_buffer().save("snapshot.png")
```

Run, press SPACE to add a ball and RETURN to take a snapshot; app does not crash but it dont take the snapshot and emits the traceback
```
(3.7.7) D:\dev\pyglet_pillow>python noisy.py
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\window\win32\__init__.py", line
665, in f
    result = event_handler(msg, wParam, lParam)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\window\win32\__init__.py", line
736, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\window\__init__.py", line 1330,
in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\event.py", line 418, in dispatch
_event
    if handler(*args):
  File "noisy.py", line 104, in on_key_press
    pyglet.image.get_buffer_manager().get_color_buffer().save("snapshot.png")
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\image\__init__.py", line 505, in
 save
    encoder.encode(self, file, filename)
  File "d:\dev\cocos-testcmp\work\pyglet\pyglet\image\codecs\pil.py", line 139,
in encode
    image_from_fn = getattr(Image, "frombytes", getattr(Image, "fromstring"))
  File "D:\dev\cocos-testcmp\work\pys\3.7.7\lib\site-packages\PIL\Image.py", lin
e 62, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'fromstring'
```
win7
py 3.7.7
pyglet 1.4.11 (and 1.3.0)
pillow 8.0.1
Can not test with pyglet 1.5 because #296 

with pillow==7.2.0 , the last 7.x , it works normal: snapshot taken and no traceback.

**Comment by ccanepa** [comment]
I can fix it by replacing in `pyglet\image\codecs\pil.py`, PILImageEncoder.encode, the line
```python
        image_from_fn = getattr(Image, "frombytes", getattr(Image, "fromstring"))
```
with
```python
        try:
            image_from_fn = getattr(Image, "frombytes")
        except AttributeError:
            image_from_fn = getattr(Image, "fromstring")            
```
(patch inspired by PR #295 , notice that here Image uses uppercase I)

**Comment by benmoran56** [comment]
Hi @ccanepa,

v1.5.9 was released which contains these fixes.
Let me know if you still see any issues, but I 
think we got them all.

**Comment by ccanepa** [comment]
No issues here, thanks.

**Comment by benmoran56** [comment]
Great! I'll close this for now. 
Thanks for opening the ticket.
