### ISSUE TITLE
Calling play() in rapid succession on a synthesizer object throws ctypes.ArgumentError

### ISSUE THREAD

**Issue by SirGnip** [pyglet/pyglet#299]
Calling `.play()` on a synthesizer object in rapid succession causes exception.

- Python 3.7.3
- Pyglet: 1.5.8
- OS: WIndows 10 Home (1909)
- `print(pyglet.media.get_audio_driver())` returns `pyglet.media.drivers.directsound.adaptation.DirectSoundDriver`

Repro:

```
import pyglet

class SynthTest(pyglet.window.Window):
    def __init__(self):
        super(SynthTest, self).__init__()
        self.sound = pyglet.media.synthesis.Sine(0.5, frequency=440)

    def on_key_press(self, symbol, modifiers):
        self.sound.play()

if __name__ == '__main__':
    window = SynthTest()
    pyglet.app.run()
```

Run the snippet above and tap a single key.  You will hear the sine wave, as expected.  Tap the key again after the sound is complete.  You hear the sound again.  Now, tap the key twice (to attempt to play a second sound before the first one is complete).  The app exists with this exception:

```
Traceback (most recent call last):
  File "C:/cache/repo/soloud_try/pyg_min2.py", line 16, in <module>
    pyglet.app.run()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 173, in _check_refill
    self.refill(write_size)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 183, in refill
    self.write(audio_data, length)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 304, in write
    ctypes.memmove(write_ptr.audio_ptr_1, audio_data.data, write_ptr.audio_length_1.value)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

I threw a quick debug print in `adaptation.py` in `DirectSoundAudioPlayer.write()` right before the `ctypes.memmove` call:

```print(type(audio_data), type(audio_data.data))```

...and when I launch the app and mash keys repeatedly, I get this output (followed by the exception above)

```
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'list'>
```

I also found that if wrap the Sine object in a `StaticSource`, I can play the sound as rapidly as I want:

```self.sound = pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.5, frequency=440))```

Is it expected to be able to repeatedly call `.play()` on a synthesizer object, even before other play() calls complete?  Or, am I simply seeing expected behavior and need to wrap the synthesizer object in `StaticSource`?  The [Audio Synthesis docs](https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#audio-synthesis) state "The waveforms you create with the synthesis module can be played like any other loaded sound."

I am very new to Pyglet and its audio handling, so apologies if this is a basic question.

**Comment by caffeinepills** [comment]
From what you are printing the data ends up changing to a list when it should be a ctypes array. I am not too familiar with synthesis myself, but there may be a bug somewhere there. The audio data is slowly consumed by the DirectSound driver. Could you do me a favor and try the 1.5 maintenance branch? There is a new Window audio driver there, just wondering if it's any better or you encounter any issues there.

**Comment by SirGnip** [comment]
I cloned the repo, checked out the `pyglet-1.5-maintenance` branch, made a venv, did `pip install -e .` and then ran the repo script above again.  When I tap a key the first time, I hear no audio and get this exception:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\cache\repo\pyglet\pyglet\window\win32\__init__.py", line 712, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\cache\repo\pyglet\pyglet\window\win32\__init__.py", line 783, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\cache\repo\pyglet\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\cache\repo\pyglet\pyglet\event.py", line 422, in dispatch_event
    self._raise_dispatch_exception(event_type, args, getattr(self, event_type), exception)
  File "C:\cache\repo\pyglet\pyglet\event.py", line 476, in _raise_dispatch_exception
    raise exception
  File "C:\cache\repo\pyglet\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "repro.py", line 9, in on_key_press
    self.sound.play()
  File "C:\cache\repo\pyglet\pyglet\media\codecs\base.py", line 265, in play
    player.play()
  File "C:\cache\repo\pyglet\pyglet\media\player.py", line 249, in play
    self._set_playing(True)
  File "C:\cache\repo\pyglet\pyglet\media\player.py", line 201, in _set_playing
    self._audio_player.prefill_audio()
  File "C:\cache\repo\pyglet\pyglet\media\drivers\xaudio2\adaptation.py", line 318, in prefill_audio
    self.refill_source_player()
  File "C:\cache\repo\pyglet\pyglet\media\drivers\xaudio2\adaptation.py", line 210, in refill_source_player
    x2_buffer = self._xa2_driver.create_buffer(audio_data)
  File "C:\cache\repo\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 341, in create_buffer
    buff.pAudioData = data
TypeError: incompatible types, c_short_Array_22400 instance instead of LP_c_char instance
```

**Comment by benmoran56** [comment]
@SirGnip Could you give it another try with the 1.5-maintenance branch? 
There might be a flag you need to pass to pip so that it updates, instead of using the cached version.

**Comment by benmoran56** [comment]
I made a small change to the synthesis module so that it explicitly returns `bytes` in all cases.

**Comment by SirGnip** [comment]
I pulled the newest code from pyglet-1.5-maintenance this morning into my local pyglet repo.  I then did `pip uninstall pyglet` and `pip install -e. `.  When I ran my repro script again, I heard sound when tapping keys.  When I mashed the keys repeatedly, I heard sound again and no exceptions.
The repro script as written wouldn't trigger two Sine waves at the same time (one had to finish before a new one could start).  I think this is expected behavior?  Simply wrapping the `Sine()` constructor in a `StaticSource()` allowed me to trigger multiple copies.
So, looks good on my side.  Thanks for looking into this!

**Comment by benmoran56** [comment]
Great, glad that fixed it. With regards to the playback behavior, that's expected. Wrapping in a StaticSource is the way to go, for things you'll be playing multiple times. Instantiating a brand new source each time is also an option, but that wastes CPU cycles for calculating the wave forms. 

The fix will be in the next point release. I'll close this now, but feel free to reopen it or make a new ticket if you see any other issues.
