### ISSUE TITLE
Rapid calls to .play() on a synthesizer object throws ctypes.ArgumentError

### ISSUE THREAD

**Issue by SirGnip** [pyglet/pyglet#300]
Calling `.play()` on a synthesizer object in rapid succession causes exception.

- Python 3.7.3
- Pyglet: 1.5.8
- OS: WIndows 10 Home (1909)
- `print(pyglet.media.get_audio_driver())` returns `pyglet.media.drivers.directsound.adaptation.DirectSoundDriver`

Repro:

```
import pyglet

class SynthTest(pyglet.window.Window):
    def __init__(self):
        super(SynthTest, self).__init__()
        self.sound = pyglet.media.synthesis.Sine(0.5, frequency=440)

    def on_key_press(self, symbol, modifiers):
        self.sound.play()

if __name__ == '__main__':
    window = SynthTest()
    pyglet.app.run()
```

Run the snippet above and tap a single key.  You will hear the sine wave, as expected.  Tap the key again after the sound is complete.  You hear the sound again.  Now, tap the key twice (to attempt to play a second sound before the first one is complete).  The app exists with this exception:

```
Traceback (most recent call last):
  File "C:/cache/repo/soloud_try/pyg_min2.py", line 16, in <module>
    pyglet.app.run()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\app\base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 173, in _check_refill
    self.refill(write_size)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 183, in refill
    self.write(audio_data, length)
  File "C:\cache\repo\soloud_try\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 304, in write
    ctypes.memmove(write_ptr.audio_ptr_1, audio_data.data, write_ptr.audio_length_1.value)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

I threw a quick debug print in `adaptation.py` in `DirectSoundAudioPlayer.write()` right before the `ctypes.memmove` call:

```print(type(audio_data), type(audio_data.data))```

...and when I launch the app and mash keys repeatedly, I get this output (followed by the exception above)

```
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'pyglet.media.synthesis.c_short_Array_22400'>
<class 'pyglet.media.codecs.base.AudioData'> <class 'list'>
```

I also found that if wrap the Sine object in a `StaticSource`, I can play the sound as rapidly as I want:

```self.sound = pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.5, frequency=440))```

Is it expected to be able to repeatedly call `.play()` on a synthesizer object, even before other play() calls complete?  Or, am I simply seeing expected behavior and need to wrap the synthesizer object in `StaticSource`?  The [Audio Synthesis docs](https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#audio-synthesis) state "The waveforms you create with the synthesis module can be played like any other loaded sound."

I am very new to Pyglet and its audio handling, so apologies if this is a basic question.

**Comment by SirGnip** [comment]
My browser page went stale and I accidentally submitted this twice.  This is a dupe of https://github.com/pyglet/pyglet/issues/299
