### ISSUE TITLE
macOS Touch Bar warning

### ISSUE THREAD

**Issue by ebolotin6** [pyglet/pyglet#315]
I am receiving the following warning when I render in OpenAI gym:

```
2020-11-21 20:55:19.522 python3[24131:283512] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fe5980e7480>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2020-11-21 20:55:19.522 python3[24131:283512] Warning: Expected min height of view: (<NSButton: 0x7fe5987aaab0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2020-11-21 20:55:19.525 python3[24131:283512] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fe5987adce0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2020-11-21 20:55:19.526 python3[24131:283512] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fe5987b5a80>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

I am using a Macbook Pro with a Touch Bar. The warning seems to indicate that a window with a height greater than 30 is opening in the Touch Bar. This warning does not occur on my other Macbook Pro that does not have a Touch Bar. The code I am running is:

```
import gym
import numpy as np

env = gym.make('CartPole-v1')

for _ in range(10):
    observation = env.reset()
    done = False

    while not done:
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)

env.close()

```

I am not sure if this warning has to do with pyglet, but it only occurs when rendering.

Other info:
* macOS 11.0.1 (Big Sur) 
* Python 3.8.3
* pyglet 1.5.11

**Comment by benmoran56** [comment]
Could you try a pyglet-only example, and see if it has the same message? Such as the `hello_world.py` file in the `examples` folder in the repo. 

I see that there are a few reports around Github for other projects with the same error, but didn't see any resolutions.

**Comment by ebolotin6** [comment]
Sure, will check this out and get back to you.

**Comment by ebolotin6** [comment]
I ran hello_world.py from /examples and am running into the following error:

```
Traceback (most recent call last):
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyglettest.py", line 3, in <module>
    window = pyglet.window.Window()
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1888, in <module>
    from pyglet.window.cocoa import CocoaWindow as Window
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/window/cocoa/__init__.py", line 44, in <module>
    from pyglet.canvas.cocoa import CocoaCanvas
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 102, in <module>
    from pyglet.canvas.cocoa import CocoaDisplay as Display
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/canvas/cocoa.py", line 41, in <module>
    from pyglet.libs.darwin.cocoapy import CGDirectDisplayID, quartz, cf
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
    from .cocoapy import *
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 37, in <module>
    from .cocoalibs import *
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py", line 19, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/Users/ebolotin/opt/miniconda3/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
```

Thoughts?

**Comment by benmoran56** [comment]
Hmm, that's pretty strange, especially since pyglet was working as part of Gym. It seems like something strange with the pyglet installation, or potentially the environment.

**Comment by Alexcornila** [comment]
apparently this is a BigSur issue

**Comment by ebolotin6** [comment]
> apparently this is a BigSur issue

Yeah I think so too... Will close this for now.

**Comment by paaguti** [comment]
It will go away if you compile your native code with a modern-enough <regexp>Xcode (Command Lines Tools)?</regexp> package
