### ISSUE TITLE
Text Input (examples/text/text_input.py) example, is showing a Key Error

### ISSUE THREAD

**Issue by Original-Coding-Cult** [pyglet/pyglet#318]
Running the code of examples/text/text_input.py returns the following error. I was running this in Visual Studio Code, but this error also came while running in Repl.it

```
Traceback (most recent call last):
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\__init__.py", line 449, in _get_domain
    domain = domain_map[key]
KeyError: (('vertices2i', 'colors4Bn'), 4, True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\...\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\...\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\...\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\...\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\...\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\...\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\...\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\...\textFielder.py", line 145, in <module>
    window = Window(resizable=True)
  File "c:\...\textFielder.py", line 60, in __init__
    TextWidget('This is a tset', 200, 100, self.width - 210, self.batch),
  File "c:\...\textFielder.py", line 38, in __init__
    self.rectangle = Rectangle(x - pad, y - pad, x + width + pad, y + height + pad, batch)
  File "c:\...\textFielder.py", line 16, in __init__
    self.vertex_list = batch.add_indexed(4, pyglet.gl.GL_TRIANGLES, None,
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\__init__.py", line 395, in add_indexed
    domain = self._get_domain(True, mode, group, formats)
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\__init__.py", line 453, in _get_domain
    domain = vertexdomain.create_indexed_domain(*formats)
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\vertexdomain.py", line 145, in create_indexed_domain
    attribute_usages = [create_attribute_usage(f) for f in attribute_usage_formats]
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\vertexdomain.py", line 145, in <listcomp>
    attribute_usages = [create_attribute_usage(f) for f in attribute_usage_formats]
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\vertexdomain.py", line 113, in create_attribute_usage
    attribute = vertexattribute.create_attribute(attribute_format)
  File "C:\...\Programs\Python\Python38\lib\site-packages\pyglet\graphics\vertexattribute.py", line 239, in create_attribute
    assert match, 'Invalid attribute format %r' % format
AssertionError: Invalid attribute format 'vertices2i'
```

**Comment by jason-bowen-zheng** [comment]
That's very easy! You should replace `vertices2i` with `v2i`, `colors4Bn` with `c4B`.

It's just two different versions of pyglet.
