### ISSUE TITLE
Issue since I updated to Mac OS Big Sur

### ISSUE THREAD

**Issue by StealthyNiffler** [pyglet/pyglet#324]
I recently upgraded my os to Big Sur and since then, none of my pyglet programs works. Everyone returns this error, and 
I am having a hard time searching the web for a solution. I would be very thankful if someone could help me. 
Thanks in advance!

```Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Cbin/lissajous", line 16, in <module>
    window = pyglet.window.Window()
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1888, in <module>
    from pyglet.window.cocoa import CocoaWindow as Window
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/window/cocoa/__init__.py", line 44, in <module>
    from pyglet.canvas.cocoa import CocoaCanvas
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 102, in <module>
    from pyglet.canvas.cocoa import CocoaDisplay as Display
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/canvas/cocoa.py", line 41, in <module>
    from pyglet.libs.darwin.cocoapy import CGDirectDisplayID, quartz, cf
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
    from .cocoapy import *
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 37, in <module>
    from .cocoalibs import *
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py", line 19, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/user/anaconda3/envs/ph/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found```

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 

Firstly, make sure you're on the latest pyglet release (1.5.11), since there were some important fixes in there for Big Sur. 

Also give it another try with the system Python, and see if there is any difference.

**Comment by StealthyNiffler** [comment]
I already have the 1.5.11 version of pyglet installed. When I use my pre installed python ```/usr/bin/python3``` I can suddenly run a few of my pyglet applications (only those that don't use any library that are installed in my anaconda environment).
However they still return a bunch of warnings. Do you have any idea how to fix that and why it isn't working inside my 
anaconda environment (I already reinstalled anaconda3 but nothing changed)?

```2020-12-08 12:49:04.889 Python[1363:52576] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/cg/_nhmpmjn73qg19b_76y4yf5m0000gn/T/org.python.python3.savedState

2020-12-08 12:49:05.045 Python[1363:52576] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fd2fe34d730>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

2020-12-08 12:49:05.045 Python[1363:52576] Warning: Expected min height of view: (<NSButton: 0x7fd2ffe180f0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

2020-12-08 12:49:05.049 Python[1363:52576] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fd2ffe1b5c0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

2020-12-08 12:49:05.050 Python[1363:52576] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fd2ffe31860>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.```

**Comment by benmoran56** [comment]
There are several Python issues still remaining in Big Sur, requiring upstream patches to CPython. The system version of Python that is shipped with OSX contains some custom patches apparently, and it seems like upstream CPython is working of fixes. It would have been nice if Apple would have just sent the patches upstream, but oh well. 

I don't use Anaconda myself, but I think you just need to wait for updates. Most likely whenever the next point release of CPython is out. 

For your last error, I would just ignore that for now since it's not fatal. This seems to occur on other applications and programming languages as well, so it doesn't seem to be pyglet specific.

**Comment by benmoran56** [comment]
I'll close this for now, but please feel free to reopen it if you want to follow up.

**Comment by peircej** [comment]
I've tested on pyglet 1.5.23 using stock Python 3.8 as well as conda 3.8 and the issue persists. It seems to be something to do with dispatch_events. Here's a minimal example to get the error. This code:
```python
import pyglet
win = pyglet.window.Window()
win.dispatch_events()
print(pyglet.version)
```
results in:
```
2022-04-27 17:31:55.138 python[88156:5056560] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff61be942e0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
1.5.23
2022-04-27 17:31:55.139 python[88156:5056560] Warning: Expected min height of view: (<NSButton: 0x7ff61beef650>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-04-27 17:31:55.140 python[88156:5056560] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff61bef2d80>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2022-04-27 17:31:55.141 python[88156:5056560] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff61bed9170>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

If you do `win.flip()` instead of `win.dispatch_events()` there is no error. Beyond that I'm rather stuck. I'm not keen to dig around further in pyglet's events dispatchers! 😬

**Comment by peircej** [comment]
My apologies @benmoran56 I was referring to the second message, from @StealthyNiffler which doesn't look like the same issue as the original post. Would you prefer I open a new issue for this thing with the `Expected min height of view` warning?
