### ISSUE TITLE
MacOS Big Sur: AttributeError: 'NoneType' object has no attribute 'get_joysticks'

### ISSUE THREAD

**Issue by mihir-chauhan** [pyglet/pyglet#344]
Hello!

I have updated to MacOS Big Sur and when I run a .exe that I compiled from PyInstaller for a python script, it gives the following error:

```
Traceback (most recent call last):
  File "site-packages/pyglet/__init__.py", line 334, in __getattr__
AttributeError: 'NoneType' object has no attribute 'get_joysticks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 6, in <module>
  File "ftc/rc.py", line 48, in main
  File "site-packages/pyglet/__init__.py", line 340, in __getattr__
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pyglet/input/__init__.py", line 173, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pyglet/input/darwin_hid.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py", line 200, in <module>
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found
[2484] Failed to execute script cli
```

Before, I updated on the same computer, it worked perfectly fine. 

Could you please help me find a solution? Thank you!

**Comment by benmoran56** [comment]
Hello, 

Apple changed some Python specific things in Big Sur (particularly how ctypes finds system libraries), so you'll need to rebuild your program with a recent Python and pyglet release.

**Comment by mihir-chauhan** [comment]
Thanks @benmoran56 for the speedy response! I will try that out and let you know if all goes well :)

**Comment by mihir-chauhan** [comment]
Thanks @benmoran56 it works now.

**Comment by benmoran56** [comment]
Great!
