### ISSUE TITLE
2.x changes documentation ?

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#357]
where can I find api changes documentation for the 2.x release ? seems some users already pulled 2.0dev and I think something is broken regarding opengl stuff like this:

```
Error creating test polygon. Full text of error:

Full text of error:
Traceback (most recent call last):
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/__init__.py", line 499, in _get_domain
    domain = domain_map[key]
KeyError: (('v2i', 'c3B'), 7, False, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xantares/projects/brainworkshop/brainworkshop.pyw", line 4670, in <module>
    test_polygon = batch.add(4, GL_QUADS, None, ('v2i', (
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/__init__.py", line 413, in add
    domain = self._get_domain(False, mode, group, formats)
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/__init__.py", line 505, in _get_domain
    domain = vertexdomain.create_domain(shader_program, *formats)
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/vertexdomain.py", line 131, in create_domain
    attribute_usages = [create_attribute_usage(shader_program, f)
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/vertexdomain.py", line 131, in <listcomp>
    attribute_usages = [create_attribute_usage(shader_program, f)
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/vertexdomain.py", line 113, in create_attribute_usage
    attribute = vertexattribute.create_attribute(shader_program, attribute_format)
  File "/home/xantares/.local/lib/python3.9/site-packages/pyglet/graphics/vertexattribute.py", line 225, in create_attribute
    assert attribute_meta, f"No '{name}' attribute found in {shader_program}.\n"\
AssertionError: No 'v' attribute found in ShaderProgram(id=3).
Valid attibutes are: {'vertices': Attribute('vertices', program=3, location=0, count=4, format=f), 'colors': Attribute('colors', program=3, location=1, count=4, format=f), 'tex_coords': Attribute('tex_coords', program=3, location=2, count=2, format=f)}.
```

**Comment by einarf** [comment]
2.x is not really finalized yet. There are no `QL_QUADS` in 2.0 and we refer to `vertices2i` instead of `v2i`.

Pyglet 2.0 will definitely not be compatible with pyglet 1.x.x projects out of the box. Users should not pull this release. There are only pre-releases on PyPI so unless you `pip install --pre` they can be avoided. I think `python setup.py install` might do this by default still? The other option is `pip install .`
