### ISSUE TITLE
Issue on GLX

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#395]
I have met this issue recently but I couldn't find any solution online.

When I import `pyglet.gl`, this error will raise:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Minecraft-in-python/Minecraft/minecraft/__main__.py", line 3, in <module>
    from minecraft.start import *
  File "/root/Minecraft-in-python/Minecraft/minecraft/start.py", line 13, in <module>
    import minecraft.utils.tests
  File "/root/Minecraft-in-python/Minecraft/minecraft/utils/tests.py", line 6, in <module>
    from pyglet.gl import gl_info
  File "/usr/local/lib/python3.9/dist-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/usr/local/lib/python3.9/dist-packages/pyglet/window/__init__.py", line 1909, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python3.9/dist-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/window/__init__.py", line 596, in __init__
    config = screen.get_best_config(template_config)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/canvas/base.py", line 192, in get_best_config
    configs = self.get_matching_configs(template)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/canvas/xlib.py", line 220, in get_matching_configs
    configs = template.match(canvas)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/gl/xlib.py", line 58, in match
    have_13 = info.have_version(1, 3)
  File "/usr/local/lib/python3.9/dist-packages/pyglet/gl/glx_info.py", line 83, in have_version
    raise GLXInfoException('pyglet requires an X server with GLX')
pyglet.gl.glx_info.GLXInfoException: pyglet requires an X server with GLX
```

Can you add some tips on which lib we should install on Linux?

**Comment by jason-bowen-zheng** [comment]
I'm using debian, `Linux 3.18.31-perf-g46f6132-01558-g873422d #2 SMP PREEMPT Thu Jan 3 19:20:13 CST 2019 aarch64 GNU/Linux`

**Comment by benmoran56** [comment]
You just need a running X server. On debian, the package should just be called `xorg`, plus the appropriate drivers for your particular graphics card. 

Is this a phone?  If it's something like Termux, then pyglet won't work because there is no way to create a full OpenGL context.

**Comment by jason-bowen-zheng** [comment]
> Is this a phone?
Yes, but not right. The debian based on `proot`, It can work well before.

**Comment by benmoran56** [comment]
In that case, you might try the debian wiki: 
https://wiki.debian.org/Xorg

You will also need graphics drivers with OpenGL 2.0 support (Not OpenGL ES). 
pyglet has not been tested in these environments, so we don't have any instructions.

**Comment by jason-bowen-zheng** [comment]
Can I disable the `pyglet.glx` when `pyglet.gl` load?

**Comment by benmoran56** [comment]
Unfortunately no, because GLX is required to use OpenGL. 

Usually, if you install some desktop environment, Xorg will be installed as well.

**Comment by jason-bowen-zheng** [comment]
Maybe you should give me a list about what libs should be installed when we use pyglet.

**Comment by benmoran56** [comment]
We don't have a list. Linux simply requires a working Xorg server, and OpenGL graphics drivers (capable of OpenGL 2.0). 
Every distribution is different, so you have to rely on the distribution documentation.

**Comment by jason-bowen-zheng** [comment]
Oh, I see.

Another question: When pyglet2.0 will release?

**Comment by benmoran56** [comment]
There is no firm date yet, but we're getting closer. 
You can already install dev releases from PyPi. 
```py
pip install --user pyglet==2.0.dev5
```
Most high-level things are working (sprites, shapes, text). However, internals may change before release.

**Comment by jason-bowen-zheng** [comment]
I can use pyglet on Termux(with proot):
![Screenshot_2021-06-15-18-38-11](https://user-images.githubusercontent.com/58848782/122039379-38ecc280-ce09-11eb-9626-8150ea3bc4f1.png)
