### ISSUE TITLE
traceback when updating Label.text

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#41]
with this pure pyglet script

```python
# file _pyglet_label.py
from __future__ import division, print_function, unicode_literals

import pyglet

window = pyglet.window.Window(640, 480)

x0 = window.width // 2
y0 = window.height // 2

t=0.0
color = (255, 255, 0, 255)
font = pyglet.font.load("", 36, bold=True)
strings = ["fps   60 minfps   %d" % 27, "fps   60 minfps   %d" % 42]

label = pyglet.text.Label("", font, color=color, x=10, y=10)

@window.event
def on_draw():
    window.clear()
    label.draw()

def update(dt):
    global t
    label.text = strings[int(t % 1.99)]
    t += dt

pyglet.clock.schedule_interval(update, 1 / 30.)
pyglet.app.run()
```
got a crash with traceback

```
(py-cocos) E:\dev\cocos2019\test>python _pyglet_label.py
Traceback (most recent call last):
  File "_pyglet_label.py", line 29, in <module>
    pyglet.app.run()
  File "e:\dev\pyglet-2019\pyglet\app\__init__.py", line 144, in run
    event_loop.run()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 175, in run
    self._run()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 187, in _run
    timeout = self.idle()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 308, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "e:\dev\pyglet-2019\pyglet\clock.py", line 327, in call_scheduled_functio
ns
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "_pyglet_label.py", line 25, in update
    label.text = strings[int(t % 1.99)]
  File "e:\dev\pyglet-2019\pyglet\text\__init__.py", line 294, in text
    self.document.text = text
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 300, in text
    self.insert_text(0, text)
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 431, in insert_text
    self.dispatch_event('on_insert_text', start, text)
  File "e:\dev\pyglet-2019\pyglet\event.py", line 403, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler, exception)
  File "e:\dev\pyglet-2019\pyglet\event.py", line 466, in _raise_dispatch_except
ion
    raise exception
  File "e:\dev\pyglet-2019\pyglet\event.py", line 400, in dispatch_event
    if handler(*args):
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1045, in on_insert_text
    self._init_document()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1034, in _init_document
    self._update()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 957, in _update
    lines = self._get_lines()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 933, in _get_lines
    glyphs = self._get_glyphs()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1069, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 614, in get_font_runs
    ft = self.get_font(dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 624, in get_font
    bold=bool(bold), italic=bool(italic), dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\font\__init__.py", line 137, in load
    font = _font_class(name, size, bold=bold, italic=italic, dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 493, in __init__
    super(GDIPlusFont, self).__init__(name, size, bold, italic, dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 234, in __init__
    self.logfont = self.get_logfont(name, size, bold, italic, dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 266, in get_logfont
    logfont.lfFaceName = asbytes(name)
  File "e:\dev\pyglet-2019\pyglet\compat.py", line 79, in asbytes
    return bytes(s)
TypeError: cannot convert 'GDIPlusFont' object to bytes
Exception ignored in: <function GDIPlusFont.__del__ at 0x00000000067DB1E0>
Traceback (most recent call last):
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 533, in __del__
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 248, in __del__
AttributeError: 'GDIPlusFont' object has no attribute 'hfont'
```
win7 64.bits, python 3.7

pyglet:
commit 58dfdb6314fc900cfbba6355b79bb09e718a41c9 master github
Author: Benjamin Moran
Date: Fri Aug 9 09:43:50 2019 +0900

Discovered while testing cocos, https://github.com/los-cocos/cocos/issues/326

**Comment by ccanepa** [comment]
disregard this, called with bad params. sorry
