### ISSUE TITLE
can't run pyglet on WSL

### ISSUE THREAD

**Issue by originalsurfmex** [pyglet/pyglet#44]
Hi I can't run pyglet on WSL (Windows 10).  Pygame works fine so I know it's not a display or GL issue.  The same errors come up with both pyglet 3.0 and 4.1

This is the error I get when using both pyglet on its own and also with python arcade which uses pyglet:

```
Traceback (most recent call last):
  File "/.local/lib/python3.6/site-packages/pyglet/__init__.py", line 353, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/timer.py", line 47, in <module>
    window = pyglet.window.Window(fullscreen=True)
  File "/.local/lib/python3.6/site-packages/pyglet/__init__.py", line 359, in __getattr__
    __import__(import_name)
  File "/.local/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1889, in <module>
    gl._create_shadow_window()
  File "/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 209, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/.local/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/.local/lib/python3.6/site-packages/pyglet/window/__init__.py", line 642, in __init__
    self._create()
  File "/.local/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 264, in _create
    self.context.attach(self.canvas)
  File "/.local/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 349, in attach
    self.set_current()
  File "/.local/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 354, in set_current
    super(XlibContext13, self).set_current()
  File "/.local/lib/python3.6/site-packages/pyglet/gl/base.py", line 333, in set_current
    gl_info.set_active_context()
  File "/.local/lib/python3.6/site-packages/pyglet/gl/gl_info.py", line 96, in set_active_context
    self.vendor = asstr(cast(glGetString(GL_VENDOR), c_char_p).value)
  File "/.local/lib/python3.6/site-packages/pyglet/gl/lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
```

**Comment by benmoran56** [comment]
The error message indicates that an OpenGL context can't be created. OpenGL is not available out of the box with WSL, so this is expected. You might be able to get it to work by following the advice posted here: 
https://github.com/Microsoft/WSL/issues/2855
Pygame does not use OpenGL, so its not a direct comparison in this case. 

Can I ask why you're trying to run pyglet in Linux mode under Windows, instead of natively?

**Comment by originalsurfmex** [comment]
Thanks for the help there.  I was using X410 which surprisingly doesn't seem to support OpenGL.  VcXsrv does seem to work really well though.

Next I'll check in with the python arcade devs to see about some errors there.

I was using msys2 but have moved to WSL this week.  WSL still gives me a unix heavy environment but with much more speed and fluidity than msys2 or cygwin.  For professional reasons my main OS needs to be windows but for certain things I prefer to work in a unix/linux environment.  It all boils down to how much I use emacs and even though it works on windows it works so much better on linux.

**Comment by benmoran56** [comment]
Glad you got it working.

That's a good reason!
