### ISSUE TITLE
Bug report: The program crashes on MacOS, when I press and hold the keys on the keyboard, it appears randomly

### ISSUE THREAD

**Issue by ChrisChou-freeman** [pyglet/pyglet#447]
Hi, i find some issue, the program crashes  when I press and hold the keys on the keyboard, it appears randomly

my computer is MacOS M1 version

the crashes log down below.
```Traceback (most recent call last):
  File "/Users/chrischou/GameStudio/PyCityHunter/main.py", line 55, in <module>
    app.run()
  File "/Users/chrischou/Library/Python/3.9/lib/python/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/Users/chrischou/Library/Python/3.9/lib/python/site-packages/pyglet/app/base.py", line 170, in run
    platform_event_loop.step(timeout)
  File "/Users/chrischou/Library/Python/3.9/lib/python/site-packages/pyglet/app/cocoa.py", line 147, in step
    event_type = event.type()
  File "/Users/chrischou/Library/Python/3.9/lib/python/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1009, in __getattr__
    raise AttributeError('ObjCInstance %s has no attribute %s' % (self.objc_class.name, name))
AttributeError: ObjCInstance b'__NSSingleObjectArrayI' has no attribute b'type'
```
hope it helps😄

**Comment by ChrisChou-freeman** [comment]
I found the factor that triggered this bug. As long as I keep sliding the image left and right (press and hold the left and right buttons to move the image), I will find that the image has dropped frames, and then it will crash and exit soon.

**Comment by benmoran56** [comment]
Thanks for opening the ticket.
If possible, can you show a small code example that will trigger the issue?

**Comment by ChrisChou-freeman** [comment]
> Thanks for opening the ticket.
> If possible, can you show a small code example that will trigger the issue?

Hi, it’s me. Yesterday I raised the problem of gaps in two pictures in help1 in discord. That code（GameExample.zip） is the code that triggers the bug.

**Comment by ChrisChou-freeman** [comment]
For convenience, I put it on GitHub
https://github.com/ChrisChou-freeman/PygletGameExample

**Comment by caffeinepills** [comment]
According to https://developer.apple.com/documentation/appkit/nsapplication/1428485-nexteventmatchingmask, where the event comes from (as well as `send_super` function)

It should only return a `NSEvent` which is guaranteed to have a `type`. `NSSingleObjectArrayI` isn't even mentioned anywhere in the current code base.

**Comment by caffeinepills** [comment]
This should be fixed with the new alternate event loop. If the problem occurs again, let us know with the latest pyglet and a new ticket.

**Comment by qiffang** [comment]
` File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/window/cocoa/__init__.py", line 49, in __init__
    super().__init__(width, height, caption, resizable, style, fullscreen, visible, vsync, file_drops, display,
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/window/__init__.py", line 536, in __init__
    config = screen.get_best_config(config)
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/canvas/base.py", line 162, in get_best_config
    configs = self.get_matching_configs(template)
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/canvas/cocoa.py", line 59, in get_matching_configs
    return template.match(canvas)
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/gl/cocoa.py", line 184, in match
    pixel_format = NSOpenGLPixelFormat.alloc().initWithAttributes_(attrsArray)
  File "/Users/qifangfang/anaconda3/envs/easymocap/lib/python3.9/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1109, in __getattr__
    raise AttributeError('ObjCInstance %s has no attribute %s' % (self.objc_class.name, name))`

**Comment by pushfoo** [comment]
@qiffang Can you try with `pyglet==2.0.17`
