### ISSUE TITLE
example "gui/widgets"'s text entry widgets not working

### ISSUE THREAD

**Issue by shenjackyuanjie** [pyglet/pyglet#487]
# pyglet version: github version(clone from this reponstry and update at 6:20)

![image](https://user-images.githubusercontent.com/54507071/136862292-973e8dbf-6168-46f3-95e0-373ff626e9f7.png)

i can't type in any words or things into it
other widgets in this examples works well
---------
also example `text/text_input` will get's some unexcpet movement
text select have some issues
![image](https://user-images.githubusercontent.com/54507071/136862525-4f2e20c1-576c-42d1-a748-876499bd49af.png)
![image](https://user-images.githubusercontent.com/54507071/136862586-9abd2712-8ed1-4939-9acb-6ac60b75491b.png)

does the class `caret` have some issues?

**Comment by shenjackyuanjie** [comment]
now `widgets.py` can't run
`text_input.py`(in text) it's text entry can use
but still have issue on inputing line

**Comment by shenjackyuanjie** [comment]
```
"C:\Program Files\Python38\python38.exe" D:/githubs/pyglet-main/examples/gui/widgets.py
Traceback (most recent call last):
  File "D:/githubs/pyglet-main/examples/gui/widgets.py", line 77, in <module>
    frame.add_widget(text_entry)
  File "D:\githubs\pyglet-main\pyglet\gui\frame.py", line 79, in add_widget
    widget.update_groups(self._order)
  File "D:\githubs\pyglet-main\pyglet\gui\widgets.py", line 475, in update_groups
    self._layout.group = Group(order=order + 2, parent=self._user_group)
AttributeError: can't set attribute

进程已结束，退出代码为 1

```
`widgets.py` error message

**Comment by shenjackyuanjie** [comment]
fixed！
