### ISSUE TITLE
Window buttons on mac cause python/pyglet to crash

### ISSUE THREAD

**Issue by olehermanse** [pyglet/pyglet#5]
**Description:** The window buttons (close, minimize, full screen) cause python to crash in various ways. (Segmentation fault, Recursion Error, Abort Trap, Illegal Instruction).

**Pyglet version(s):** 1.4.1

**Python version(s):** 3.7

**OS:** OS X 10.14.5 (Seems to only affect newer Macbooks)

**Related tickets:** [bitbucket #199](https://bitbucket.org/pyglet/pyglet/issues/199/attempting-to-resize-or-close-pyglet) [bitbucket #229](https://bitbucket.org/pyglet/pyglet/issues/229/closing-window-causes-a-crash-on-mac-os)

**Minimal example:**

```python3
import pyglet

pyglet.window.Window(resizable=True)

pyglet.app.run()
```

**Output 1 (close):**

```
$ python3 example.py 
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1120, in objc_method
    args = convert_method_arguments(encoding, args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1000, in convert_method_arguments
    new_args.append(ObjCInstance(a))
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 921, in __new__
    if not isinstance(object_ptr, c_void_p):
RecursionError: maximum recursion depth exceeded while calling a Python object
Segmentation fault: 11
$ 
```

**Output 2 (minimize):**

```
$ python3 example.py 
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1120, in objc_method
    args = convert_method_arguments(encoding, args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1000, in convert_method_arguments
    new_args.append(ObjCInstance(a))
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 921, in __new__
    if not isinstance(object_ptr, c_void_p):
RecursionError: maximum recursion depth exceeded while calling a Python object
Illegal instruction: 4
$ 
```

**Comment by einarf** [comment]
I cannot reproduce this on my macbook at least (10.14.5 Mojave).

Tested with:
```bash
# Current master
-e git+https://github.com/pyglet/pyglet.git@32e6bdf578db062c11ec4599365896e89f44ee32#egg=pyglet
# From PyPI
pyglet==1.4.1
# Python version
Python 3.7.3
```

**Comment by olehermanse** [comment]
@einarf Thanks for testing. For me, it happens consistently, on my new macbook, but I didn't use to have the problem on the old one. I'll test more and try to narrow it down.

**Comment by einarf** [comment]
Weird. It's at least conistent considering I did my tests on a 2013 macbook pro (old stuff!) :)

**Comment by benmoran56** [comment]
@einarf Your Mac is old but should still be 64 bit, right?

**Comment by einarf** [comment]
Definitely. Pretty decent specs still

```
Processor Name:              Intel Core i7
Processor Speed:             2,7 GHz
Number of Processors:	     1
Total Number of Cores:       4
L2 Cache (per Core):         256 KB
L3 Cache:                    6 MB
Hyper-Threading Technology:  Enabled
Memory:	                     16 GB
Graphics/Display:            NVIDIA GeForce GT 650M
```

**Comment by Berstad** [comment]
I was able to reproduce this issue on my 2018 Macbook Pro 15 inch w/ touchbar. Got the same output as @olehermanse when minimizing and closing. Also, manually resizing the window by dragging causes a segfault with the same output as closing.

Pyglet version(s): 1.4.1
Python version(s): 3.7.3
OS: macOS 10.14.5

**Comment by einarf** [comment]
We had a pretty long session last night trying to find the root cause. The newer macbooks are indeed sending different data in some events and the current cocoa wrapper is not equipped to deal with it. @olehermanse is testing out PyCocoa now (more recent project).

**Comment by olehermanse** [comment]
@Berstad Thank you for reproducing.

[cocoa-python](https://github.com/phillip-nguyen/cocoa-python) and [PyCocoa](https://github.com/mrJean1/PyCocoa) are not as compatible as I'd hoped, and their commit history is not great, but I'm still working on it.

**Comment by olehermanse** [comment]
In an effort to understand the problem better, I tried printing stack traces:

**Decorator stacktrace:**

```
  File "examples/hello_world.py", line 4, in <module>
    window = pyglet.window.Window()
  File "/usr/local/lib/python3.7/site-packages/pyglet/__init__.py", line 359, in __getattr__
    __import__(import_name)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1873, in <module>
    from pyglet.window.cocoa import CocoaWindow as Window
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/__init__.py", line 60, in <module>
    from .pyglet_window import PygletWindow, PygletToolWindow
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 44, in <module>
    class PygletWindow_Implementation(object):
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 63, in PygletWindow_Implementation
    @PygletWindow.method(b'@'+NSUIntegerEncoding+b'@@B')
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1115, in method
    tb = ''.join(traceback.format_stack())
```
(Last line is the traceback I added)

Recursive stack trace:

```
  File "examples/hello_world.py", line 20, in <module>
    pyglet.app.run()
  File "/usr/local/lib/python3.7/site-packages/pyglet/app/__init__.py", line 144, in run
    event_loop.run()
  File "/usr/local/lib/python3.7/site-packages/pyglet/app/base.py", line 175, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/pyglet/app/base.py", line 188, in _run
    platform_event_loop.step(timeout)
  File "/usr/local/lib/python3.7/site-packages/pyglet/app/cocoa.py", line 153, in step
    self.NSApp.sendEvent_(event)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785, in __call__
    return self.method(self.objc_id, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 755, in __call__
    result = f(objc_id, self.selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 72, in nextEventMatchingMask_untilDate_inMode_dequeue_
    mask, date, mode, dequeue, argtypes=[NSUInteger, c_void_p, c_void_p, c_bool])
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 499, in send_super
    result = objc.objc_msgSendSuper(byref(super_struct), selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 72, in nextEventMatchingMask_untilDate_inMode_dequeue_
    mask, date, mode, dequeue, argtypes=[NSUInteger, c_void_p, c_void_p, c_bool])
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 499, in send_super
    result = objc.objc_msgSendSuper(byref(super_struct), selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 72, in nextEventMatchingMask_untilDate_inMode_dequeue_
    mask, date, mode, dequeue, argtypes=[NSUInteger, c_void_p, c_void_p, c_bool])
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 499, in send_super
    result = objc.objc_msgSendSuper(byref(super_struct), selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 72, in nextEventMatchingMask_untilDate_inMode_dequeue_
    mask, date, mode, dequeue, argtypes=[NSUInteger, c_void_p, c_void_p, c_bool])
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 499, in send_super
    result = objc.objc_msgSendSuper(byref(super_struct), selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/window/cocoa/pyglet_window.py", line 72, in nextEventMatchingMask_untilDate_inMode_dequeue_
    mask, date, mode, dequeue, argtypes=[NSUInteger, c_void_p, c_void_p, c_bool])
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 499, in send_super
    result = objc.objc_msgSendSuper(byref(super_struct), selector, *args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1132, in objc_method
```

**Comment by olehermanse** [comment]
I guess the best way to focus is to understand:

- [nextEventMatchingMask](https://github.com/pyglet/pyglet/blob/0c1186f99f2cce8c54de6222a5e3a8aa364cc3bc/pyglet/window/cocoa/pyglet_window.py#L71)
- [PygletWindow method decorator](https://github.com/pyglet/pyglet/blob/0c1186f99f2cce8c54de6222a5e3a8aa364cc3bc/pyglet/libs/darwin/cocoapy/runtime.py#L1109), [as invoked here](https://github.com/pyglet/pyglet/blob/0c1186f99f2cce8c54de6222a5e3a8aa364cc3bc/pyglet/window/cocoa/pyglet_window.py#L63)

**Comment by olehermanse** [comment]
It's worth noting that in the "normal" crash:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1120, in objc_method
    args = convert_method_arguments(encoding, args)
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1000, in convert_method_arguments
    new_args.append(ObjCInstance(a))
  File "/usr/local/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 921, in __new__
    if not isinstance(object_ptr, c_void_p):
RecursionError: maximum recursion depth exceeded while calling a Python object
Segmentation fault: 11
olehermanse@OHMBP pyglet $ 
```

The last line, `if not isinstance(object_ptr, c_void_p):`, is not that important, it's kind of arbitrary. I was confused why isinstance would recurse / throw a recursion error, but it's just a simple function, the recursionerror is thrown because the stack is exhausted, it can't call any other function, this just happens to be the function attempted.

**Comment by benmoran56** [comment]
Right, that's makes sense.

**Comment by olehermanse** [comment]
By adding some more prints, I understand a little bit more:

```
calling nextEventMatchingMask(<ObjCInstance 0x109c96910: b'PygletWindow' at 140253884364016>, 17179869184, <ObjCInstance 0x10b44c550: b'__NSDate' at 140253881864336>, <ObjCInstance 0x10b44c990: b'__NSCFConstantString' at 140735709825224>, True)
receiver: <ObjCInstance 0x109c96910: b'PygletWindow' at 140253884364016>
selName: nextEventMatchingMask:untilDate:inMode:dequeue:
superclass: c_void_p(140253882060592)
super_struct: <pyglet.libs.darwin.cocoapy.runtime.OBJC_SUPER object at 0x10b44fd40>
selector: c_void_p(140734157906392)
restype: <class 'ctypes.c_void_p'>
argtypes: [<class 'ctypes.c_ulong'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_bool'>]

calling nextEventMatchingMask(<ObjCInstance 0x109c96910: b'PygletWindow' at 140253884364016>, 17179869184, <ObjCInstance 0x10b44c550: b'__NSDate' at 140253881864336>, <ObjCInstance 0x10b44c990: b'__NSCFConstantString' at 140735709825224>, True)
receiver: <ObjCInstance 0x109c96910: b'PygletWindow' at 140253884364016>
selName: nextEventMatchingMask:untilDate:inMode:dequeue:
superclass: c_void_p(140253882060592)
super_struct: <pyglet.libs.darwin.cocoapy.runtime.OBJC_SUPER object at 0x10b44fdd0>
selector: c_void_p(140734157906392)
restype: <class 'ctypes.c_void_p'>
argtypes: [<class 'ctypes.c_ulong'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_void_p'>, <class 'ctypes.c_bool'>]
```

When you click the close button, [`PygletWindow.nextEventMatchingMask_untilDate_inMode_dequeue_`](https://github.com/pyglet/pyglet/blob/8ee1ad2e87deeb9fc7140b18f3a1c076c1d93399/pyglet/window/cocoa/pyglet_window.py#L64) is called. This has some special logic for handling resize, and then it tries to call the same method in superclass - NSWindow. The function used to call a method in superclass is called `send_super`. There seems to be a bug in `send_super` (or the data it uses), it instead calls the method in PygletWindow again, causing infinite recursion. If I add a print statement after the [`send_super` call](https://github.com/pyglet/pyglet/blob/8ee1ad2e87deeb9fc7140b18f3a1c076c1d93399/pyglet/window/cocoa/pyglet_window.py#L71) I can see that none of them terminate, they just keep calling the method in the subclass (PygletWindow).

**Comment by olehermanse** [comment]
This comment is also interesting:

```
    # When the window is being resized, it enters into a mini event loop that
    # only looks at mouseDragged and mouseUp events, blocking everything else.
    # Among other things, this makes it impossible to run an NSTimer to call the
    # idle() function in order to update the view during the resize.  So we
    # override this method, called by the resizing event loop, and call the
    # idle() function from here.  This *almost* works.  I can't figure out what
    # is happening at the very beginning of a resize event.  The NSView's
    # viewWillStartLiveResize method is called and then nothing happens until
    # the mouse is dragged.  I think NSApplication's nextEventMatchingMask_etc
    # method is being called instead of this one.  I don't really feel like
    # subclassing NSApplication just to fix this.  Also, to prevent white flashes
    # while resizing, we must also call idle() from the view's reshape method.
```

It seems the author didn't fully understand why sometimes a different (class) method was called than the intended.

**Comment by benmoran56** [comment]
Is it possible to prevent the crash just by disabling the super call, for a start?

**Comment by olehermanse** [comment]
Just commenting out the send_super part cause the program to hang forever.

Commenting out the whole _nextEventMatchingMask method fixes the close button, but resize is still broken.

Commenting out both `PygletView.setFrameSize_`, as well as `PygletWindow.nextEventMatchingMask_untilDate_inMode_dequeue_` works surprisingly well. Both closing and resizing works, except on_resize event's are not dispatched, so all my resize logic doesn't work. (But the NSView actually resizes).

**Comment by benmoran56** [comment]
Ahh interesting! After resizing, are you able to manually query the window and framebuffer sizes?

**Comment by r1chardj0n3s** [comment]
FWIW I had the issue reported here with the system Python 2.7.9 but I just installed latest Python 2.7.16 (I'm testing out an old game that's not py3k compatible) and no longer have the issue.
I install using pyenv, FWIW.

**Comment by olehermanse** [comment]
> Ahh interesting! After resizing, are you able to manually query the window and framebuffer sizes? 

@benmoran56 I guess that would be possible, but then we don't get the events, we would have to poll for the changes, which is not a great fix, IMO.

**Comment by olehermanse** [comment]
I forked cocoa-python here:

https://github.com/olehermanse/cocoa-python

And reproduced the issue, with a quite small example:

```
# Example of using ctypes with Cocoa to create an NSWindow with
# an application menu item for quitting.

import sys
from cocoapy import *

NSWindow = ObjCClass('NSWindow')
NSApplication = ObjCClass('NSApplication')
NSMenu = ObjCClass('NSMenu')
NSMenuItem = ObjCClass('NSMenuItem')
NSAutoreleasePool = ObjCClass('NSAutoreleasePool')

class MyWindow_Implementation(object):
    MyWindow = ObjCSubclass('NSWindow', 'MyWindow')

    @MyWindow.method(b'@'+NSUIntegerEncoding+b'@@B')
    def nextEventMatchingMask_untilDate_inMode_dequeue_(self, mask, date, mode, dequeue):

        print(f"nextEventMatchingMask({mask}, {date}, {mode}, {dequeue})")

        event = send_super(self, 'nextEventMatchingMask:untilDate:inMode:dequeue:',
                           mask, date, mode, dequeue, argtypes=[c_uint, c_void_p, c_void_p, c_bool])
        print("send_super returned")

        if event.value is None:
            ret = 0
        else:
            ret = event.value
        print("return value: " + str(ret))
        return ret

MyWindow = ObjCClass('MyWindow')

def create_window():
    print('creating window')
    frame = NSMakeRect(100, 100, 300, 300)
    window = MyWindow.alloc().initWithContentRect_styleMask_backing_defer_(
        frame,
        NSTitledWindowMask | NSClosableWindowMask | NSMiniaturizableWindowMask | NSResizableWindowMask,
        NSBackingStoreBuffered,
        0)
    window.setTitle_(get_NSString("My Awesome Window"))
    window.makeKeyAndOrderFront_(None)
    return window

def create_autorelease_pool():
    pool = NSAutoreleasePool.alloc().init()
    return pool

def application_run():
    app = NSApplication.sharedApplication()
    create_autorelease_pool()
    create_window()
    app.run()  # never returns

######################################################################

if __name__ == '__main__':
    application_run()
```

https://github.com/olehermanse/cocoa-python/commit/dc536717f0dcf9f008108a882ccb0955135160eb

So, there are many other examples where `send_super()` from cocoa-python works, however, in this example it doesn't. When you call send_super, it seems to call `MyWindow.nextEventMatchingMaskUntilDate` instead of `NSWindow.nextEventMatchingMaskUntilDate`.

**Note:** I thought `setFrameSize` had the same problem as `nextEventMatchingMaskUntilDate`, but that is just because it calls `nextEventMatchingMaskUntilDate` internally.

**Comment by RyanSchaefer** [comment]
I am still experiencing this issue on 3.8 and there is no pythonw with the latest version of python which is causing issues

**Comment by eterevsky** [comment]
I have no idea how Cocoa or ObjC works, but here's a dirty hack of cocoapy that makes window operations work:

```py
def send_super(receiver, selName, *args, **kwargs):
    if hasattr(receiver, '_as_parameter_'):
        receiver = receiver._as_parameter_
    superclass = get_superclass_of_object(receiver)
    superduperclass = c_void_p(objc.class_getSuperclass(superclass))
    if superduperclass.value is not None:
        superclass = superduperclass
    super_struct = OBJC_SUPER(receiver, superclass)
```

**Comment by benmoran56** [comment]
Thank you very much for this.  It's been a frustrating issue since it doesn't affect everyone's Mac, so hopeful we can get confirmation from additional affected users.

**Comment by olehermanse** [comment]
Fixed in: https://github.com/pyglet/pyglet/pull/194
