### ISSUE TITLE
"list changed size during iteration" exception when scheduling and unscheduling functions

### ISSUE THREAD

**Issue by tomhaines** [pyglet/pyglet#558]
Pyglet 1.5.21
Python 3.9.2

I am using the following code snippet to fire events to signify when a user starts and stops spinning a physical rotary encoder to "tune" a dial in a radio simulation. The rotary encoder ```rotate``` event sets ```tuning = True``` dispatching one ```on_tuning_start``` event, and after a brief timeout, a scheduled function sets ```tuning = False``` which dispatches one ```on_tuning_stop``` event. If the ```tuning``` property is set to ```True``` during this timeout window, I unschedule the timeout function and reset it to ensure only one start and stop event fires while the user is actively turning the rotary encoder. This could cause the functino to be scheduled and unscheduled several dozen times a second as the user turns the rotary encoder.

This works a vast majority of the time, but every once in a great while, it causes an exception. My guess is that it may create a race condition in Pyglet where unscheduling or scheduling functions while the list is being iterated is causing an exception.

```python
import pyglet

class Tuner(pyglet.event.EventDispatcher)
  def __init__(self) :
    self._is_tuning = False

  @property
  def tuning(self) :
    return self._is_tuning

  @tuning.setter
  def tuning(self, now_tuning) :
    clock.unschedule(self._tuning_timer_timeout) # unschedule any pending timeout
    if now_tuning == False :
      self.dispatch_event("on_tuning_stop")
    elif self._is_tuning == False and now_tuning == True : # The user has begun turning the dial
      self.dispatch_event("on_tuning_start")
    
    if now_tuning == True:
      self.dispatch_event("on_tuning")
      clock.schedule_once(self._tuning_timer_timeout, self._tuning_delay) #start a scheduled function to signify a timeout
      
    self._is_tuning = now_tuning
  
  #if the timer runs out, they've stopped tuning the dial
  def _tuning_timer_timeout(self,dt) :
    self.tuning = False
```

```
Traceback (most recent call last):
  File "/home/pi/Documents/Radiolux/Radiolux/radiolux.py", line 286, in <module>
    main()
  File "/home/pi/Documents/Radiolux/Radiolux/radiolux.py", line 89, in main
    pyglet.app.run()
  File "/home/pi/Documents/Radiolux/Radiolux/pyglet/app/__init__.py", line 107, in run
    event_loop.run()
  File "/home/pi/Documents/Radiolux/Radiolux/pyglet/app/base.py", line 169, in run
    timeout = self.idle()
  File "/home/pi/Documents/Radiolux/Radiolux/pyglet/app/base.py", line 239, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/pi/Documents/Radiolux/Radiolux/pyglet/clock.py", line 280, in call_scheduled_functions
    item = heappushpop(interval_items, item)
RuntimeError: list changed size during iteration
```

**Comment by benmoran56** [comment]
Thanks for opening the ticket. 
Are you using threading anywhere in your program?
If not, is it possible to make a small standalone example that might trigger the crash if left running?

**Comment by tomhaines** [comment]
I am using threading, but I am not scheduling or unscheduling any events inside of threads.

**Comment by benmoran56** [comment]
Hi, are you able to make a small standalone example?
