### ISSUE TITLE
Multiple errors when running examples

### ISSUE THREAD

**Issue by illuzioner** [pyglet/pyglet#57]
PyGlet looks like it could be useful for me, but I'm worried about the stability of the project since I'm encountering errors on your own examples.  If it's a simple fix, great!  Otherwise ...

Here are some of the errors I've gotten:

`> python .\game\version4\asteroid.py
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 641, in f
    result = event_handler(msg, wParam, lParam)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 712, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 1330, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\event.py", line 416, in dispatch_event
    if handler(*args):
  File "D:\Downloads\sourceCode\pyglet-1.3.0\examples\game\version4\game\player.py", line 56, in on_key_press
    self.fire()
  File "D:\Downloads\sourceCode\pyglet-1.3.0\examples\game\version4\game\player.py", line 63, in fire
    ship_radius = self.image.width / 2
AttributeError: 'NoneType' object has no attribute 'width'`

and 

`K> python .\video.py E:\Media\Audio\quickBrownFox2b\quickBrownFox2b.mp4
Traceback (most recent call last):
  File ".\video.py", line 74, in <module>
    pyglet.app.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\app\__init__.py", line 144, in run
    event_loop.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\app\base.py", line 175, in run
    self._run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\app\base.py", line 187, in _run
    timeout = self.idle()
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\app\base.py", line 314, in idle
    window.dispatch_event('on_draw')
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 1330, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyglet\event.py", line 416, in dispatch_event
    if handler(*args):
  File ".\video.py", line 72, in on_draw
    player.get_texture().blit(0, 0)
AttributeError: 'NoneType' object has no attribute 'blit'`

and 

`OK> python .\media_info.py E:\Media\Audio\quickBrownFox2b\quickBrownFox2b.mp4
Traceback (most recent call last):
  File ".\media_info.py", line 87, in <module>
    print_avbin_info()
  File ".\media_info.py", line 21, in print_avbin_info
    from pyglet.media import have_avbin
ImportError: cannot import name 'have_avbin' from 'pyglet.media' (D:\ProgramData\Anaconda3\lib\site-packages\pyglet\media\__init__.py)`

and 

`OK> python .\game\version5\asteroid.py
Traceback (most recent call last):
  File ".\game\version5\asteroid.py", line 19, in <module>
    counter = pyglet.clock.ClockDisplay()
AttributeError: module 'pyglet.clock' has no attribute 'ClockDisplay'`

These are all different errors too, which makes me worry.  Do these all have one simple fix or are they multiple issues?

**Comment by benmoran56** [comment]
I have tried all of these examples, and they work on my machine. 

From your tracebacks, it looks like you're on an older version of pyglet. I can see "pyglet-1.3.0" in your first traceback, which is quite old and full of bugs. Please give it another try on the latest 1.4.4 release.

**Comment by illuzioner** [comment]
I see.  That's good to know.  I was using the link here:
https://pyglet.readthedocs.io/en/stable/programming_guide/installation.html#running-the-examples
to download the examples.  Looks like that link needs to be update.

**Comment by benmoran56** [comment]
Thanks for bringing that to our attention. pyglet recently migrated from Bitbucket, and those links were missed.

We're working on refreshing the documentation theme, and have also fixed the links. It's not yet default, but will be soon. Please let us know if you see any other issues.

https://pyglet.readthedocs.io/en/latest/
