### ISSUE TITLE
FFmpeg 5 backport in stable branch

### ISSUE THREAD

**Issue by xantares** [pyglet/pyglet#603]
for those who update to ffmpeg 5.x, can we expect #580 be backported in the stable 1.5.x branch ?

**Comment by caffeinepills** [comment]
Yes, I believe these will be backported along with other fixes in the next 1.5 release.

**Comment by xantares** [comment]
cool! reopening as a remainder then

**Comment by Woolwit** [comment]
Continue to have an issue playing ogg files with pyglet. 
```
% pip3.10 show pyglet
Name: pyglet
Version: 1.5.24
Summary: Cross-platform windowing and multimedia library
Home-page: http://pyglet.readthedocs.org/en/latest/
Author: Alex Holkner
Author-email: Alex.Holkner@gmail.com
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: 
Required-by: 

% which python3.10
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

% which ffmpeg
/usr/local/bin/ffmpeg

% ffmpeg --version
ffmpeg version 5.0-tessus

% ffplay Concert.ogg #plays fine

% python3.10
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyglet.info
>>> pyglet.info.dump_ffmpeg()
FFmpeg not available.
```

**Comment by benmoran56** [comment]
```py
>>> pyglet.info.dump_ffmpeg()
FFmpeg not available.
```
The FFmpeg libraries are not being found, so it's then trying (and failing) on other codecs. 
Try creating an instance of the FFmpegDecoder manually, so that you can see the error message: 
```py
>>> import pyglet
>>> import pyglet.media.codecs
>>> 
>>> pyglet.media.codecs.ffmpeg.FFmpegDecoder()
FFmpegDecoder('.mp3', '.ogg')
```
You will need to have a `shared` build of FFmpeg (--enable-shared), that matches the bitrate of your Python interpreter.
If you only need Ogg support, and not video, you may want to use the optional PyOgg interface: 
https://pyglet.readthedocs.io/en/latest/programming_guide/media.html#pyogg

**Comment by Woolwit** [comment]
I'm on an M1 ARM Mac Mini. I believe the ffmpeg is shared (other apps/processes are finding it). (I only saw --enable-shared as part of Windows ffmpeg installation).

```
>>> import pyglet
>>> import pyglet.media.codecs
>>> 
>>> pyglet.media.codecs.ffmpeg.FFmpegDecoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyglet.media.codecs' has no attribute 'ffmpeg'
```
My python and ffmpeg are both 64 bit.
```

 % file /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64
- Mach-O 64-bit executable arm64]
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 (for architecture arm64):	Mach-O 64-bit executable arm64

% file /usr/local/bin/ffmpeg
/usr/local/bin/ffmpeg: Mach-O 64-bit executable x86_64
```
The use case is facilitating ogg playback in another program that uses pyglet for that purpose.
Can play a wav file fine, but get the error with the ogg.

```
>>> import pyglet
>>> 
>>> music = pyglet.resource.media('Concert.wav')
>>> music.play()
2022-05-15 22:34:14.910 Python[3097:231511] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/7p/_xj9hlhs7d1bndz44mljbm1c0000gn/T/org.python.python.savedState
<pyglet.media.player.Player object at 0x101720ee0>
>>> music = pyglet.resource.media('Concert.ogg')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/wave.py", line 58, in __init__
    self._wave = wave.open(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 509, in open
    return Wave_read(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 163, in __init__
    self.initfp(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
```

**Comment by benmoran56** [comment]
The shared version of ffmpeg includes the standalone libraries for other applications to use. For instance: 
'avcodec', 'avformat', 'avutil', 'swresample', 'swscale'

Try with the extra import line: 
```py
import pyglet
import pyglet.media.codecs
import pyglet.media.codecs.ffmpeg
pyglet.media.codecs.ffmpeg.FFmpegDecoder()
```

One other thought:
FFmpeg on OSX, as far as I'm aware, does not have pre-build arm binaries available for download. For that reason, only the x86_64 build of Python will be able to interface with the x64_64 FFmpeg that is installed. If using the `arm64` Python interpreter, it won't be able to load them. You can check which Python interpreter you're using with the `platform` module: 
```py
import platform

platform.platform()
platform.architecture()
# etc
```
If all you need is Ogg support, the PyOgg module is probably an easier choice. I'm not positive that PyOgg works on M1 Macs, but it should be easy to try if you have Homebrew installed.

**Comment by Woolwit** [comment]
Wild... no luck. 
```
% pip3.10 show pyogg
Name: PyOgg
Version: 0.6.14a1
Summary: Xiph.org's Ogg Vorbis, Opus and FLAC for Python
Home-page: https://github.com/Zuzu-Typ/PyOgg
Author: Zuzu_Typ
Author-email: zuzu.typ@gmail.com
License: BSD 3-clause "New" or "Revised"
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: 
Required-by: 

>>> import pyglet
>>> import pyglet.media.codecs
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:19: UserWarning: PyOgg determined the ogg/vorbis libraries were not available.
  warnings.warn("PyOgg determined the ogg/vorbis libraries were not available.")
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:22: UserWarning: PyOgg determined the flac library was not available.
  warnings.warn("PyOgg determined the flac library was not available.")
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:25: UserWarning: PyOgg determined the opus libraries were not available.
  warnings.warn("PyOgg determined the opus libraries were not available.")
>>> 
```

**Comment by Woolwit** [comment]
Did get those previously...
```
brew list --versions libogg opus opusfile libopusenc libvorbis flac
flac 1.3.4
libogg 1.3.5
libopusenc 0.2.1
libvorbis 1.3.7
opus 1.3.1
opusfile 0.12
```
Still seeing ("PyOgg determined the opus libraries were not available.")
But the wav file playing fine.
```
>>> import pyglet
>>> import pyogg
>>> sound = pyglet.media.load('Concert.ogg')
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:19: UserWarning: PyOgg determined the ogg/vorbis libraries were not available.
  warnings.warn("PyOgg determined the ogg/vorbis libraries were not available.")
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:22: UserWarning: PyOgg determined the flac library was not available.
  warnings.warn("PyOgg determined the flac library was not available.")
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/pyogg.py:25: UserWarning: PyOgg determined the opus libraries were not available.
  warnings.warn("PyOgg determined the opus libraries were not available.")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/wave.py", line 58, in __init__
    self._wave = wave.open(file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 509, in open
    return Wave_read(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 163, in __init__
    self.initfp(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/__init__.py", line 142, in load
    raise first_exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/__init__.py", line 132, in load
    loaded_source = decoder.decode(file, filename, streaming)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/wave.py", line 105, in decode
    return WaveSource(filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyglet/media/codecs/wave.py", line 60, in __init__
    raise WAVEDecodeException(e)
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id
>>> sound = pyglet.media.load('Concert.wav')
>>> sound.play()
2022-05-16 11:14:45.221 Python[3191:36611] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/7p/_xj9hlhs7d1bndz44mljbm1c0000gn/T/org.python.python.savedState
<pyglet.media.player.Player object at 0x100908a90>
>>> 
```

**Comment by benmoran56** [comment]
I would guess that Homebrew is installing x86_64 versions, but you're using the arm64 Python interpreter. Can you check using the platform module, like I mentioned earlier?

**Comment by Woolwit** [comment]
It seems like this is the version of Homebrew (as determined by location of files) that associates with arm64 Macs.
(I hope you're not getting the sense that I know what I'm doing here ;-) Just trying to follow along.) 

```
>>> platform.machine()
'arm64'
>>> platform.platform()
'macOS-12.3.1-arm64-arm-64bit'
>>> platform.processor()
'arm'
>>> 

% which brew
/opt/homebrew/bin/brew
% brew --version
Homebrew 3.4.11
Homebrew/homebrew-core (git revision a312614ba6f; last commit 2022-05-16)
```
