### ISSUE TITLE
Error getting joysticks in 2.0.dev15

### ISSUE THREAD

**Issue by pvcraven** [pyglet/pyglet#607]
Try running this code with 2.0.dev15 on Windows:

```py
import pyglet

from pyglet.image.atlas import Allocator

joysticks = pyglet.input.get_joysticks()
```

I get this error:

```
Traceback (most recent call last):
  File "C:\Users\craven\projects\arcade\test.py", line 5, in <module>
    joysticks = pyglet.input.get_joysticks()
  File "C:\Users\craven\projects\arcade\venv_3.10\lib\site-packages\pyglet\input\directinput.py", line 266, in get_joysticks
    [_create_joystick(device) for device in get_devices(display)]
  File "C:\Users\craven\projects\arcade\venv_3.10\lib\site-packages\pyglet\input\directinput.py", line 233, in get_devices
    _xinput_devices = get_xinput_guids()
  File "C:\Users\craven\projects\arcade\venv_3.10\lib\site-packages\pyglet\input\xinput.py", line 284, in get_xinput_guids
    ole32.CoInitialize(None)
  File "_ctypes/callproc.c", line 993, in GetResult
OSError: [WinError -2147417850] Cannot change thread mode after it is set
```

Removing the Allocator import allows the program to run without error.

This happens on 2.0.dev15 and 2.0.dev14 but not 2.0.dev13 by my tests.

**Comment by benmoran56** [comment]
Hey Paul, 
Could you try it again with the latest from master?

**Comment by pvcraven** [comment]
That program works with the latest from master.

I now get errors when running Arcade programs like this:

```
ModuleNotFoundError: No module named 'pyglet.com'
Traceback (most recent call last):
  File "C:\Users\craven\projects\arcade\tests\test_examples\run_all_examples.py", line 62, in <module>
    all_examples()
  File "C:\Users\craven\projects\arcade\tests\test_examples\run_all_examples.py", line 59, in all_examples
    run_examples(indices_in_range, index_skip_list)
  File "C:\Users\craven\projects\arcade\tests\test_examples\run_all_examples.py", line 46, in run_examples
    subprocess.call(cmd, shell=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "C:\Program Files\Python310\lib\subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "C:\Program Files\Python310\lib\subprocess.py", line 1485, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
```
I do not know if the error is on the pyglet side or the Arcade side yet.

**Comment by benmoran56** [comment]
That one was on the pyglet side. Could you try it again with the latest push? I think we got them all now :)

**Comment by pvcraven** [comment]
YES! Everything seems to run now. Thank you very much!!!

**Comment by benmoran56** [comment]
Great! I just pushed out a dev16 release.
Going to close this now.
