### ISSUE TITLE
FFmpeg 4.x not working anymore since 1.5.24

### ISSUE THREAD

**Issue by fladd** [pyglet/pyglet#608]
Steps to reproduce:

1. Take a system (tested on Windows 10) that does not have FFmpeg installed
2. Download and extract the following ZIP archive: [pyglet_1.5.24_ffmpeg4_error.zip](https://github.com/pyglet/pyglet/files/8711429/pyglet_1.5.24_ffmpeg4_error.zip)
3. Install pyglet 1.5.24
4. Run the file `ffmpeg_error.py` --> Error (see below)
5. Install pyglet 1.5.23
6. Run the file `ffmpeg_error.py` --> No error

The error you get with 1.5.24 is:
```
Traceback (most recent call last):
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\lib.py", line 143, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "C:\Users\flokra\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\flokra\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-57' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\flokra\Documents\GitHub\zap\zap\ffmpeg_error.py", line 20, in <module>
    from pyglet.media.codecs.ffmpeg import *
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\media\codecs\ffmpeg.py", line 50, in <module>
    from .ffmpeg_lib import *
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\media\codecs\ffmpeg_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\media\codecs\ffmpeg_lib\libavcodec.py", line 46, in <module>
    from . import libavutil
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\media\codecs\ffmpeg_lib\libavutil.py", line 47, in <module>
    avutil = pyglet.lib.load_library(
  File "C:\Users\flokra\Documents\GitHub\zap\venv\lib\site-packages\pyglet\lib.py", line 162, in load_library
    raise ImportError("Unexpected error loading library %s: %s" % (name, str(o)))
ImportError: Unexpected error loading library avutil-57: Could not find module 'avutil-57' (or one of its dependencies). Try using the full path with construc
tor syntax.
```

**Comment by einarf** [comment]
I'm guessing 1.5 also needs this fix : https://github.com/pyglet/pyglet/commit/ae642e3da08ecbaf7b3a227bc0ac40c419fed056

**Comment by fladd** [comment]
It seems that the error is in `lib.py` line 162, where it throws this exception when `o.winerror` is not 126. I checked, and when it cannot find the library, `o.winerror` is `None` here, and that is why it doesn't keep on looking for the next in the list.

**Comment by benmoran56** [comment]
I backported the fix from the master branch to 1.5. Could you try it with the latest 1.5-maintenance branch? If that works, I can ready a point release.

**Comment by fladd** [comment]
Is there any time frame on a new release? I am wondering whether I should hold back a new ZAP release or not :-)

**Comment by benmoran56** [comment]
I just pushed out a 1.5.26 release, which contains the fixes.

**Comment by fladd** [comment]
Nice, thanks!

**Comment by weerdy15** [comment]
Probably, this should be closed?

**Comment by benmoran56** [comment]
Yes, thanks!
