### ISSUE TITLE
libGL error: MESA-LOADER: failed to open iris

### ISSUE THREAD

**Issue by AkgunOnur** [pyglet/pyglet#627]
Hey guys,
The following problem occurs while attempting to perform `from pyglet.gl import *`. I believe the issue is due to a driver and library incompatibility. The operating system is Ubuntu 22.04, and the graphics card is an Nvidia Rtx 3060.
Some folks, as far as I could tell, solved a similar problem by installing a different version of pyglet. As a result, I installed various pyglet versions, including 1.5.17, 1.5.18, 1.5.19, and 1.5.-maintenance.None of them were successful.
What should I do in this situation? 

Thanks in advance

```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/onur/miniconda3/envs/gpu/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 615, in __init__
    context = config.create_context(gl.current_context)
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/onur/.local/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

**Comment by einarf** [comment]
Try running this and check the output :
```
LIBGL_DEBUG=verbose python your_script.py
```
It can be so many different things.

**Comment by AkgunOnur** [comment]
Hey @einarf ,
Thanks for your answer. I got the following output
```
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/onur/.drirc: No such file or directory.
libGL: using driver i915 for 6
```

**Comment by benmoran56** [comment]
Looks like the NVidia drivers are not installed properly.
If you have `mesa-utils` installed, you can get more information with:
```sh
glxinfo |grep OpenGL
```

**Comment by benmoran56** [comment]
Just to add, the `MESA-LOADER` messages are from the OS. You might find the following thread useful:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3477

**Comment by AkgunOnur** [comment]
Hey @benmoran56 ,
When I type `glxinfo | grep OpenGL` I get the following information. My laptop has 2 GPUs, Nvidia and Intel. I installed the recommended Nvidia driver, which is 510. As far as I can see, OpenGL thinks that main GPU is the Intel one. How can I fix this?

```
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) Graphics (ADL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by benmoran56** [comment]
Unfortunately I probably can't help much, as I don't own any Nvidia hardware.
I would guess it's one of two issues: 
1. The NVidia driver is not completely installed, or was overwritten by some OS update
2. The NVidia card needs to be specifically enabled in the BIOS

Using NVidia on Ubuntu is a pretty common case, so you can probably
find a solution over on one of the Ubuntu support forums.

**Comment by AkgunOnur** [comment]
@benmoran56 thank you for help. As you indicated, the issue directly relates to enabling Nvidia card as the primary gpu card.
It should be accomplished with the commands `sudo prime-select nvidia` and `reboot`. Now when I execute `glxinfo | grep OpenGL` the following information is returned and I no longer receive opengl errors: 

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 510.73.05
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 510.73.05
OpenGL shading language version string: 4.60 NVIDIA
```

**Comment by benmoran56** [comment]
Great! 
And thanks for following up with your solution, in case others have the same issue.
