### ISSUE TITLE
gl.xlib.destroy() ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by dizcza** [pyglet/pyglet#65]
OpenAI Gym uses pyglet to render views. During the unittests, closing gym environment triggers pyglet `window.close()`. Here is the traceback

```python
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7f4d65363128>>
Traceback (most recent call last):
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 152, in __del__
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 71, in close
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/home/dizcza/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
```

I noticed, the penultimate line is 
```
        gl.glFlush()  # needs to be in try/except?
```
So maybe it indeed needs try-catch block.

Travis build log: https://travis-ci.org/dizcza/gym-ultrasonic/builds/589577922

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. Judging from the error message, it looks like something is being called after the pyglet context has been destroyed. Even though the error might appear at one place, it's not something we can account for in pyglet. Putting try/except around glFlush would just mask the symptom.

**Comment by dizcza** [comment]
Well, it's not a big deal. It occurs during the unit tests only and silently ignored. I thought you might want to know it. You can close the issue, if you think it's not a problem of pyglet.

**Comment by benmoran56** [comment]
It looks like the `__del__` methods in the gym Viewer classes are calling `window.close()`, but it's likely that the pyglet windows have already been destroyed by garbage collection. That would explain things.  I'm fairly certain this is not a pyglet specific issue. 

It would probably make the most sense in this case to add a try/except to the Viewer classes in the gym rendering module. I've also seen some old (closed) issues for OpenAI Gym that have similar errors and workarounds posted. In any case, adding try/except to the Viewer classes would probably be a good move in case the user is doing something they shouldn't. 

Thank you for opening the ticket, and please don't hesitate to do so again if you see something that looks like a bug. I'll close this for now, but feel free to reopen it if you need more information on my suggestions.
