### ISSUE TITLE
OSError: exception: access violation - with RenderDoc

### ISSUE THREAD

**Issue by szabolcsdombi** [pyglet/pyglet#661]
Hi,
I am using pyglet as my default window for the zengl examples.
When I try to run my examples with RenderDoc I get the following exception:

```
Traceback (most recent call last):
  File "D:\Programming\zengl\examples\crate.py", line 11, in <module>
    window = Window()
  File "D:\Programming\zengl\examples\window.py", line 122, in __init__
    self._wnd = PygletWindow(*size)
  File "D:\Programming\zengl\examples\window.py", line 80, in __init__
    super().__init__(width=width, height=height, config=config, vsync=True)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyglet\window\win32\__init__.py", line 136, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyglet\window\__init__.py", line 658, in __init__
    self._create()
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyglet\window\win32\__init__.py", line 297, in _create
    self.context.attach(self.canvas)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyglet\gl\win32.py", line 231, in attach
    self._context = wgl.wglCreateContext(canvas.hdc)
OSError: exception: access violation reading 0x0000000000000020
```

I have:

- pyglet 1.5.26
- renderdoc v1.21 (98a93408)

(both at the latest version)

Running this file from vscode works like a charm. The problem only happens when Renderdoc executes my script.

![image](https://user-images.githubusercontent.com/11232402/181924344-d5324bf0-1381-494b-90ed-8939c8307c13.png)

**Comment by szabolcsdombi** [comment]
The fault is caused by RenderDoc what I just updated right before running my code with it.

With RenderDoc v1.21 I also get pygame broken (code that worked a few days ago) with RenderDoc v1.20

```
pygame 2.1.0 (SDL 2.0.16, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00001ffc (most recent call first):
  File "D:\Programming\zengl\examples\example_project\window.py", line 13 in __init__
  File "D:\Programming\zengl\examples\example_project\main.py", line 9 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, zengl, pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, pygame.fastevent, pygame._freetype (total: 41)
```

Indeed rolling back to RenderDoc v1.20 the pygame example works as before, but the one using pyglet gets a white screen.
The code is actually stuck in `_dwmaip.DwmFlush()`.

![image](https://user-images.githubusercontent.com/11232402/181925056-31d87c0c-fc4d-4c0b-89e0-ad96ca09c2d4.png)

I expect this to be another bug from RenderDoc.

I close this issue now and reopen it if neccessary. I suspect this bug also comes from RenderDoc.
