### ISSUE TITLE
XA2SourceVoice exception while close the arcade app

### ISSUE THREAD

**Issue by simonchih** [pyglet/pyglet#669]
## Bug Report
After I close the arcade app window (d44.py), I get the excepiton of XA2SourceVoice.__del__

## System Info
OS:Windows 11 x64
Python 3.9 x64

### Actual behavior:
Arcade app window is closed, but output excepiton below:
```py
C:\simon\del44>py d44.py
Exception ignored in: <function XA2SourceVoice.__del__ at 0x00000295DE6EBDC0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 401, in __del__
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 411, in destroy
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 997, in GetResult
OSError: [WinError -562308112] Windows Error 0xde7bdbf0
Exception ignored in: <function XA2SourceVoice.__del__ at 0x00000295DE6EBDC0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 401, in __del__
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 411, in destroy
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 997, in GetResult
OSError: [WinError -562309136] Windows Error 0xde7bd7f0
Exception ignored in: <function XA2SourceVoice.__del__ at 0x00000295DE6EBDC0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 401, in __del__
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 411, in destroy
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 997, in GetResult
OSError: [WinError -562339072] Windows Error 0xde7b6300
Exception ignored in: <function XA2SourceVoice.__del__ at 0x00000295DE6EBDC0>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 401, in __del__
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\media\drivers\xaudio2\interface.py", line 411, in destroy
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 997, in GetResult
OSError: [WinError -562340096] Windows Error 0xde7b5f00
```
### Expected behavior:
No any exception.

### Steps to reproduce/example code:
1. Run d44.py at below link. ( Need copy "images" and "sounds" before running.)
[https://gitlab.com/movep/del44/-/blob/master/d44.py](https://gitlab.com/movep/del44/-/blob/master/d44.py)
2. Play a while. (Maybe score greater than 100.)
Note: See [README.md](https://gitlab.com/movep/del44/-/blob/master/README.md) for details.
4. Close the app window.
==> Get exception on console.

### Where is it located?
[https://gitlab.com/movep/del44](https://gitlab.com/movep/del44)

### What is wrong with it? How can it be improved?
Solve the exception, thanks in advance.

**Comment by benmoran56** [comment]
Hi, 

This is probably caused by using the `time` module to sleep. It's better to avoid that, because it will interfere with pyglet's event loop.
The error message looks like the audio source has already been garbage collected. See if this suppresses the message:
```py
import pyglet.media.drivers.xaudio2.interface


def my_del(self):
    try:
        self.destroy()
    except OSError:
        pass


pyglet.media.drivers.xaudio2.interface.XA2SourceVoice.__del__ = my_del
```

**Comment by caffeinepills** [comment]
I couldn't reproduce this on Windows 10.
