### ISSUE TITLE
DirectWrite: Kenney Future Narrow.tt not loading

### ISSUE THREAD

**Issue by einarf** [pyglet/pyglet#731]
In Arcade we load the Keynney font pack. However, one font don't seem to be registered. I've double checked that the name is actually matching. The other ttf files seems to load just fine.

`font_not_loading.py`

```py
import pyglet

pyglet.font.add_file('Kenney Future Narrow.ttf')

window = pyglet.window.Window()
label = pyglet.text.Label(
    'Hello, world!',
    font_name='Kenney Future Narrow',
    font_size=36,
    x=window.width // 2,
    y=window.height // 2,
    anchor_x='center',
    anchor_y='center'
)

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

Traceback
```
Traceback (most recent call last):
  File "font_not_loading.py", line 6, in <module>
    label = pyglet.text.Label(
            ^^^^^^^^^^^^^^^^^^
  File "pyglet\text\__init__.py", line 481, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "pyglet\text\document.py", line 596, in set_style
    return super().set_style(0, len(self.text), attributes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\text\document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "pyglet\event.py", line 415, in dispatch_event
    if handler(*args):
       ^^^^^^^^^^^^^^
  File "pyglet\text\layout.py", line 1497, in on_style_text
    self._init_document()
  File "pyglet\text\layout.py", line 1461, in _init_document
    self._update()
  File "pyglet\text\layout.py", line 1375, in _update
    lines = self._get_lines()
            ^^^^^^^^^^^^^^^^^
  File "pyglet\text\layout.py", line 1352, in _get_lines
    glyphs = self._get_glyphs()
             ^^^^^^^^^^^^^^^^^^
  File "pyglet\text\layout.py", line 1502, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\text\document.py", line 605, in get_font_runs
    ft = self.get_font(dpi=dpi)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\text\document.py", line 615, in get_font
    return font.load(font_name, font_size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\font\__init__.py", line 152, in load
    font = _font_class(name, size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyglet\font\directwrite.py", line 1923, in __init__
    assert self._collection is not None, "Font: {} not found in loaded or system font collection.".format(name)
AssertionError: Font: Kenney Future Narrow not found in loaded or system font collection.
```

Fonts are found here : https://github.com/pythonarcade/arcade/tree/development/arcade/resources/fonts/ttf

**Comment by einarf** [comment]
Closing this. It's a variant of the "Kenney Future" font.
