### ISSUE TITLE
Multiple windows are not working under Windows

### ISSUE THREAD

**Issue by szabolcsdombi** [pyglet/pyglet#750]
**Describe the bug**

On windows creating two identical windows fail.

The `wgl.wglShareLists` call is redundant for a `Win32ARBContext` as `wglext_arb.wglCreateContextAttribsARB` is already doing the share making `wgl.wglShareLists` fail.

**How To Reproduce**

```py
import pyglet

pyglet.options['shadow_window'] = False
pyglet.options['debug_gl'] = False


class Window(pyglet.window.Window):
    def __init__(self, width, height):
        config = pyglet.gl.Config(
            major_version=4,
            minor_version=5,
            forward_compatible=True,
            double_buffer=False,
            depth_size=0,
            samples=0,
        )
        super().__init__(width=width, height=height, config=config, vsync=True)

    def on_resize(self, width, height):
        pass

    def on_draw(self):
        self.switch_to()
        pyglet.gl.glClearColor(0.0, 0.0, 0.5, 1.0)
        pyglet.gl.glClear(pyglet.gl.GL_COLOR_BUFFER_BIT)

    def update(self):
        self.flip()
        self.dispatch_events()
        return self.alive


wnd1 = Window(512, 512)
wnd2 = Window(512, 512)

pyglet.app.run()
```

traceback

```
Traceback (most recent call last):
  File "d:\Programming\zengl\.vscode\share.py", line 34, in <module>
    wnd2 = Window(512, 512)
           ^^^^^^^^^^^^^^^^
  File "d:\Programming\zengl\.vscode\share.py", line 17, in __init__
    super().__init__(width=width, height=height, config=config, vsync=True)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\window\win32\__init__.py", line 138, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\window\__init__.py", line 613, in __init__
    self._create()
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\window\win32\__init__.py", line 295, in _create
    self.context.attach(self.canvas)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\gl\win32.py", line 290, in attach
    super(Win32ARBContext, self).attach(canvas)
  File "C:\Users\Szabi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\gl\win32.py", line 237, in attach
    raise gl.ContextException('Unable to share contexts.')
pyglet.gl.ContextException: Unable to share contexts.
```

Temporary solution in pyglet\gl\win32.py, line 237:

```py
    def attach(self, canvas):
        super(Win32Context, self).attach(canvas)

        if not self._context:
            self.config._set_pixel_format(canvas)
            self._context = wgl.wglCreateContext(canvas.hdc)

        share = self.context_share
        if share:
            if not share.canvas:
                raise RuntimeError('Share context has no canvas.')
            # if not wgl.wglShareLists(share._context, self._context):
            #     raise gl.ContextException('Unable to share contexts.')
```

**Comment by caffeinepills** [comment]
This is a known issue with certain graphics cards.  

Comment out this line: https://github.com/pyglet/pyglet/blob/master/pyglet/window/__init__.py#L617

Then call it yourself on both windows after both are created.

**Comment by jaitaiwan** [comment]
Hey folks, what should a longer-term solution look like? If it's something easy enough I could perhaps create a PR for it.

**Comment by pushfoo** [comment]
> until it is resolved

If it's something broken in drivers for older cards and the manufacturers won't fix it, should we add one of the following?

* an option in `pyglet.options`
* a keyword argument for `Window`?

Example:
```python
windows = [Window(512, 512, create_projection = False) for _ in range(3)]

for window in windows:
   window._create_projection()
```

**Comment by caffeinepills** [comment]
This should be resolved in master branch.
