### ISSUE TITLE
GLException: (0x502): Invalid operation due to calling Sprite() before Window()

### ISSUE THREAD

**Issue by razermackham** [pyglet/pyglet#761]
Window() must be called before Sprite(), otherwise user gets an obtuse error.
```python
Traceback (most recent call last):
  File "test_window_order.py", line 30, in <module>
    pyglet.app.run()
  File "/usr/local/lib/python3.10/dist-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/app/base.py", line 186, in run
    timeout = self.idle()
  File "/usr/local/lib/python3.10/dist-packages/pyglet/app/base.py", line 247, in idle
    self.clock.call_scheduled_functions(dt)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/clock.py", line 262, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/app/base.py", line 153, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/usr/local/lib/python3.10/dist-packages/pyglet/window/__init__.py", line 1363, in dispatch_event
    super().dispatch_event(*args)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "test_window_order.py", line 18, in on_draw
    sprite.draw()
  File "/usr/local/lib/python3.10/dist-packages/pyglet/sprite.py", line 820, in draw
    self._vertex_list.draw(GL_TRIANGLES)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/graphics/vertexdomain.py", line 276, in draw
    self.domain.draw_subset(mode, self)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/graphics/vertexdomain.py", line 491, in draw_subset
    self.vao.bind()
  File "/usr/local/lib/python3.10/dist-packages/pyglet/graphics/vertexarray.py", line 58, in bind
    glBindVertexArray(self._id)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.
```
It would be great if this kind of "mistake" could be caught, and a better error message displayed to the end user. 
At a minimum, I think it should be documented/noted here:
https://pyglet.readthedocs.io/en/latest/programming_guide/image.html#sprites

**System Information:**
```
Platform
------------------------------------------------------------------------------
platform:  Linux-5.15.0-58-generic-x86_64-with-glibc2.35
release:   5.15.0-58-generic
machine:   x86_64

 <...>

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.3
pyglet.compat_platform: linux
```

**How To Reproduce**
```python
import argparse
import pyglet

def call_sprite_first(image):
    # breaks
    sprite = pyglet.sprite.Sprite(img=image)
    window = pyglet.window.Window()
    setup_draw_event(window, sprite)

def call_window_first(image):
    # works
    window = pyglet.window.Window()
    sprite = pyglet.sprite.Sprite(img=image)
    setup_draw_event(window, sprite)

def setup_draw_event(window, sprite):
    @window.event
    def on_draw():
        window.clear()
        sprite.draw()

if __name__ == '__main__':
    # replace your image here
    image = pyglet.image.load('redsquare.png')
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--fix', action='store_true', 
        help='add "-f" to "fix" the issue')
    args = parser.parse_args()
    if args.fix:
        call_window_first(image)
    else:
        call_sprite_first(image)
        
    pyglet.app.run()
```

**Comment by caffeinepills** [comment]
This isn't a bug per-se, but normal behavior. You cannot make or bind any resources in OpenGL before a context is created (which is done during Window creation).

The only way I can see this being caught to be printed in a more user friendly message would be to add more checks to all GL calls, but this would degrade performance.

I do agree it should be mentioned in the docs though. We can certainly add it there.

**Comment by caffeinepills** [comment]
This should be resolved now because the shadow window shares resources and a bug was fixed.
