### ISSUE TITLE
pyglet.text.Label does not work

### ISSUE THREAD

**Issue by dendardians** [pyglet/pyglet#765]
I really ilke pyglet, but i  currently can't add any text to my program because ```pyglet.text.Label``` does not work.

Here is the code example:
```
import pyglet

window = pyglet.window.Window(width=900, height=700)
pygletBatch = pyglet.graphics.Batch()

label = pyglet.text.Label('hello world', font_name='Arial', font_size=35,
    x=300, y=300, anchor_x='center', anchor_y='center', batch=pygletBatch)

@window.event
def on_draw():
	window.clear()
	pygletBatch.draw()
	
pyglet.app.run()
```

A window appear, then closed and throw an error like this:
```
Traceback (most recent call last):
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\pyglet_test1\main.py", line 7, in <module>
    label = pyglet.text.Label('hello world', font_name='Arial', font_size=35, x=300, y=300, anchor_x='center', anchor_y='center', batch=pygletBatch)
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\__init__.py", line 444, in __init__
    super().__init__(doc, x, y, z, width, height, anchor_x, anchor_y, multiline, dpi, batch, group, rotation)
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\__init__.py", line 241, in __init__
    super().__init__(document, width, height, multiline, dpi, batch, group)

  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 939, in __init__
    self.document = document
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 990, in document
    self._init_document()
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 1462, in _init_document
    self._update()
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 1376, in _update
    lines = self._get_lines()
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 1353, in _get_lines
    glyphs = self._get_glyphs()
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\layout.py", line 1503, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\document.py", line 570, in get_font_runs
    ft = self.get_font(dpi=dpi)
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\text\document.py", line 580, in get_font
    return font.load(font_name, font_size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\font\__init__.py", line 117, in load
    font = _font_class(name, size, bold=bold, italic=italic, stretch=stretch, dpi=dpi)
  File "D:\zzApps\Documents\py_apps\cv_apps\apps_1\py\lib\site-packages\pyglet\font\directwrite.py", line 2096, in __init__
    self._write_factory.GetSystemFontFallback(byref(self._fallback))
AttributeError: 'IDWriteFactory' object has no attribute 'GetSystemFontFallback'
```
I tried to copy the font (.ttf) file into project directory, but the result is still same.

My system is Windows 8.1, Python 3.10 and pyglet 2.0.4.

Thank you.

**Comment by caffeinepills** [comment]
I think I see the issue. Can you try my branch here: https://github.com/caffeinepills/pyglet/tree/dw_8_1 and see if it's fixed? Thanks

**Comment by jason-bowen-zheng** [comment]
By the way, an error was raised like this:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\__main__.py", line 26, in start
    game.add_scene("minecraft:start", StartScene)
  File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\scene\__init__.py", line 52, in add_scene
    self.__scenes[name] = scene(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\scene\start.py", line 43, in __init__
    self._singleplayer_btn = Button(resource_pack.get_translation(
  File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\gui\widget\button.py", line 27, in __init__
    self._label = ColorLabel(self._text, color="white" if enable else "gray", align="center", anchor_x="center", anchor_y="center",
  File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\gui\widget\label.py", line 39, in __init__
    Label(text=text, x=x, y=y, z=0, color=colors["fg"], **kwargs))
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\__init__.py", line 446, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 561, in set_style
    return super().set_style(0, len(self.text), attributes)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 470, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\event.py", line 380, in dispatch_event
    if handler(*args):
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1498, in on_style_text
    self._init_document()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1462, in _init_document
    self._update()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1376, in _update
    lines = self._get_lines()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1353, in _get_lines
    glyphs = self._get_glyphs()
  File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1510, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 2317, in get_glyphs
    glyph = self._render_layout_glyph(text_buffer, i, formatted_clusters)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 2194, in _render_layout_glyph
    glyph = self._glyph_renderer.render_using_layout(text_buffer[text_index:text_index + text_length])
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 1924, in render_using_layout
    glyph = self.font.create_glyph(image)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\base.py", line 298, in create_glyph
    glyph = self.texture_bin.add(
  File "C:\Program Files\Python38\lib\site-packages\pyglet\font\base.py", line 178, in add
    return atlas.add(img, border)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\image\atlas.py", line 182, in add
    self.texture.blit_into(img, x+border, y+border, 0)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\image\__init__.py", line 1341, in blit_into
    source.blit_to_texture(self.target, self.level, x, y, z)
  File "C:\Program Files\Python38\lib\site-packages\pyglet\image\__init__.py", line 813, in blit_to_texture
    glTexSubImage2D(target, level,
OSError: exception: access violation reading 0x0000000005A33D98
```

The OS is windows7, with python 3.8 and pyglet 2.0.4.

**Comment by dendardians** [comment]
@caffeinepills

**Comment by dendardians** [comment]
@caffeinepills , two thumbs up!thank you very much, it works now

**Comment by dendardians** [comment]
@caffeinepills two thumbs up, it works now! Thank you very much.

**Comment by caffeinepills** [comment]
Thanks for testing. glad it works! Next release of Pyglet we will add these fixes in.

**Comment by caffeinepills** [comment]
> By the way, an error was raised like this:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\__main__.py", line 26, in start
>     game.add_scene("minecraft:start", StartScene)
>   File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\scene\__init__.py", line 52, in add_scene
>     self.__scenes[name] = scene(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\scene\start.py", line 43, in __init__
>     self._singleplayer_btn = Button(resource_pack.get_translation(
>   File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\gui\widget\button.py", line 27, in __init__
>     self._label = ColorLabel(self._text, color="white" if enable else "gray", align="center", anchor_x="center", anchor_y="center",
>   File "C:\Users\Administrator\Desktop\mcpy\Minecraft\minecraft\gui\widget\label.py", line 39, in __init__
>     Label(text=text, x=x, y=y, z=0, color=colors["fg"], **kwargs))
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\__init__.py", line 446, in __init__
>     self.document.set_style(0, len(self.document.text), {
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 561, in set_style
>     return super().set_style(0, len(self.text), attributes)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\document.py", line 470, in set_style
>     self.dispatch_event('on_style_text', start, end, attributes)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\event.py", line 380, in dispatch_event
>     if handler(*args):
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1498, in on_style_text
>     self._init_document()
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1462, in _init_document
>     self._update()
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1376, in _update
>     lines = self._get_lines()
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1353, in _get_lines
>     glyphs = self._get_glyphs()
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\text\layout.py", line 1510, in _get_glyphs
>     glyphs.extend(font.get_glyphs(text[start:end]))
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 2317, in get_glyphs
>     glyph = self._render_layout_glyph(text_buffer, i, formatted_clusters)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 2194, in _render_layout_glyph
>     glyph = self._glyph_renderer.render_using_layout(text_buffer[text_index:text_index + text_length])
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\font\directwrite.py", line 1924, in render_using_layout
>     glyph = self.font.create_glyph(image)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\font\base.py", line 298, in create_glyph
>     glyph = self.texture_bin.add(
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\font\base.py", line 178, in add
>     return atlas.add(img, border)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\image\atlas.py", line 182, in add
>     self.texture.blit_into(img, x+border, y+border, 0)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\image\__init__.py", line 1341, in blit_into
>     source.blit_to_texture(self.target, self.level, x, y, z)
>   File "C:\Program Files\Python38\lib\site-packages\pyglet\image\__init__.py", line 813, in blit_to_texture
>     glTexSubImage2D(target, level,
> OSError: exception: access violation reading 0x0000000005A33D98
> ```
> 
> The OS is windows7, with python 3.8 and pyglet 2.0.4.

This is not related to the current issue. Looks like a driver issue, but post a new issue with pyglet.info dump and a way to replicate the issue. Thanks
