### ISSUE TITLE
Label does not work

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#767]
Error was found when I tried to migrating [this project](https://github.com/Minecraft-in-python/Minecraft) to pyglet 2.0:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test\Minecraft\minecraft\__main__.py", line 26, in start
    game.add_scene("minecraft:start", StartScene)
  File "C:\Users\Administrator\Desktop\test\Minecraft\minecraft\scene\__init__.py", line 52, in add_scene
    self.__scenes[name] = scene(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\test\Minecraft\minecraft\scene\start.py", line 47, in __init__
    self._options_btn = Button(resource_pack.get_translation("text.start_scent.options"),
  File "C:\Users\Administrator\Desktop\test\Minecraft\minecraft\gui\widget\button.py", line 27, in __init__
    self._label = ColorLabel(self._text, color="white" if enable else "gray", align="center", anchor_x="center", anchor_y="center",
  File "C:\Users\Administrator\Desktop\test\Minecraft\minecraft\gui\widget\label.py", line 39, in __init__
    Label(text=text, x=x, y=y, color=colors["fg"], **kwargs))
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\__init__.py", line 446, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\document.py", line 561, in set_style
    return super().set_style(0, len(self.text), attributes)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\document.py", line 470, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\event.py", line 380, in dispatch_event
    if handler(*args):
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\layout.py", line 1498, in on_style_text
    self._init_document()
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\layout.py", line 1462, in _init_document
    self._update()
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\layout.py", line 1376, in _update
    lines = self._get_lines()
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\layout.py", line 1353, in _get_lines
    glyphs = self._get_glyphs()
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\text\layout.py", line 1510, in _get_glyphs
    glyphs.extend(font.get_glyphs(text[start:end]))
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\font\directwrite.py", line 2331, in get_glyphs
    glyph = self._glyph_renderer.render_single_glyph(self.font_face, indice, advances[i], offsets[i],
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\font\directwrite.py", line 1882, in render_single_glyph
    glyph = self.font.create_glyph(image)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\font\base.py", line 298, in create_glyph
    glyph = self.texture_bin.add(
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\font\base.py", line 178, in add
    return atlas.add(img, border)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\image\atlas.py", line 182, in add
    self.texture.blit_into(img, x+border, y+border, 0)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\image\__init__.py", line 1341, in blit_into
    source.blit_to_texture(self.target, self.level, x, y, z)
  File "C:\Users\Administrator\Desktop\test\lib\site-packages\pyglet\image\__init__.py", line 813, in blit_to_texture
    glTexSubImage2D(target, level,
OSError: exception: access violation reading 0x0000000005BEE348
```
The [out.txt](https://github.com/pyglet/pyglet/files/10637453/out.txt) contains output from `pyglet.info`.

But in some cases program render wrong instead raise error:
![shot](https://user-images.githubusercontent.com/58848782/216874709-458cfa7b-ff59-4a87-a0aa-51b24351141e.png)

The right-bottom label seems work for I set `bold` to `True`.

**Comment by caffeinepills** [comment]
Can you try a basic example here:
```py
import pyglet

window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

pyglet.app.run()
```

Let me know if you still are crashing with this.

**Comment by jason-bowen-zheng** [comment]
The basic exaple perform well, maybe there are other reasons cause the error.

I have a question: should `pyglet.gl.gl_info.get_version()` return the same value on the same computer.
> `(3, 3)` was found while running `python -m pyglet.info` and `(4, 5)` was shown when a program ran.

**Comment by benmoran56** [comment]
pyglet only requests a 3.3 context, but the drivers are free to return a higher version. 
Generally speaking, an OpenGL context from 3.3+ is forward compatible. This shouldn't cause any issue.

**Comment by jason-bowen-zheng** [comment]
Thank for your answer.

It seems that the strange condition was caused by OpenGL and what is the meaning of `exception: access violation reading <addr>`?

**Comment by caffeinepills** [comment]
I noticed your label  text may be using some translation. Could you try using the direct text and font causing the issue in the simple example?

**Comment by caffeinepills** [comment]
After testing your example, it loads just fine without errors. Windows 7 VM, Python 3.8.

![image](https://user-images.githubusercontent.com/17804711/217072971-f966fdbc-044b-4744-8ab4-e39993354ffd.png)

I would try reinstalling your graphics drivers. Other than that, it appears to be a machine issue, not a pyglet issue.

You could also force legacy GDI font renderer if that machine is having problems. 
```py
import python
pyglet.options["win32_gdi_font"] = True
```

**Comment by jason-bowen-zheng** [comment]
Thanks for the explanation, but it seems not work.

The whole program perform well under pyglet 1.5+, but have problems when migrate to pyglet 2.0.

Is there only one solution to reinstall the driver?

**Comment by shenjackyuanjie** [comment]
> Thanks for the explanation, but it seems not work.
> 
> The whole program perform well under pyglet 1.5+, but have problems when migrate to pyglet 2.0.
> 
> Is there only one solution to reinstall the driver?

witch problem you mean?
你说的是那个OS error吗？
OSerror根据我的观察（我这里的pyglet项目）重启终端/电脑之后就会解决

**Comment by jason-bowen-zheng** [comment]
@shenjackyuanjie 若阁下说的是OSError，那我已尝试多次，该错误会不定时少量引发（我可能要换一台电脑了）。

不过这个情况很显然是字体渲染的错误，我会尝试不依赖字体文件来渲染文字（mojang的做法）
![pic](https://user-images.githubusercontent.com/58848782/216874709-458cfa7b-ff59-4a87-a0aa-51b24351141e.png)

**Comment by shenjackyuanjie** [comment]
> @shenjackyuanjie 若阁下说的是OSError，那我已尝试多次，该错误会不定时少量引发（我可能要换一台电脑了）。
> 
> 不过这个情况很显然是字体渲染的错误，我会尝试不依赖字体文件来渲染文字（mojang的做法） 
OS error确实是这个样子的，我这里也时不时会有

**Comment by caffeinepills** [comment]
If even the old GDI renderer is not working, then that computer may not properly support OpenGL 3.3 which is what Pyglet 2.0 requires.

**Comment by caffeinepills** [comment]
Closing as no further input from user.
