### ISSUE TITLE
OpenAL Adaptation/MediaThreads exceptions and errors

### ISSUE THREAD

**Issue by kitscribe** [pyglet/pyglet#836]
Hello!

I don't know is that a bug or not, but anyway there is an issue .

There are three `pyglet.media.Player` classes in my app: the first one plays common sound track and the other two should play shooting sounds when the "LCTRL" or "RCTRL" is pressed.

I load these sounds with the code below:
```python
pyglet.resource.path = [os.path.join(os.path.dirname(__file__), "../resources")]
pyglet.resource.reindex()

plane_sound = pyglet.media.StaticSource(pyglet.resource.media("plane.wav"))
shooting_sound = pyglet.media.StaticSource(pyglet.resource.media("gun.wav")) # I also tried to make a list (one sound per player)
```

I initialized the main player near the main window and execute `play` method:
```python
# create plane sound
plane_noise = pyglet.media.Player()
plane_noise.loop = True
plane_noise.volume = consts.PLANE_NOISE_VOL
plane_noise.queue(resources.plane_sound)
plane_noise.play()
```

Within the `BasePlane` class I initialize a player instance as well:
```python
class BasePlane(pyglet.sprite.Sprite):
    order_group = pyglet.graphics.Group(1)

    def __init__(self, is_flipped: bool, idx: int, *args, **kwargs):
        ...
        self.shooting_noise = pyglet.media.Player()
        self.shooting_noise.loop = True
        self.shooting_noise.volume = consts.SHOOT_NOISE_VOL
        self.shooting_noise.queue(resources.shooting_sound)

    # here how I start the player
    def _play_shoot_sound(self):
        if self.is_shooting:
            self.shooting_noise.play()
        else:
            self.shooting_noise.pause()

    def shoot(self):
        self._play_shoot_sound()
        self._spawn_bullet()

    # I call this method every frame
    def on_update(self, dt):
        self.move_forward(dt)
        self.shoot()
```

But if two `Plane`s started to shoot the same time, then, after a few frames (less than a second, maybe - two) I started to get lots of exceptions. The main player (named `plane_noise`) stop playing and the application can even crash.

Here are some examples of the traceback I'm getting:
```
Exception in thread Thread-1 (_thread_run):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 41, in _thread_run
    self.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 120, in run
    filled = player.refill_buffer()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 236, in refill_buffer
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._update_play_cursor()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 195, in _update_play_cursor
    assert self._check_cursors()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    assert self._buffer_cursor <= self._play_cursor
AssertionError
```
```
Exception in thread Thread-1 (_thread_run):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 41, in _thread_run
    self.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 120, in run
    filled = player.refill_buffer()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 236, in refill_buffer
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._update_play_cursor()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 188, in _update_play_cursor
    self._handle_processed_buffers()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 200, in _handle_processed_buffers
    processed = self.alsource.unqueue_buffers()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/interface.py", line 250, in unqueue_buffers
    self._check_error('Failed to unqueue buffers from source.')
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/interface.py", line 37, in _check_error
    raise OpenALException(message=message,
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40963: b'Invalid Value']: Failed to unqueue buffers from source.
```

**Note, that this time the application has crashed with exit code(1)**
```
Traceback (most recent call last):
  File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 57, in <module>
Exception in thread Thread-1 (_thread_run)    pyglet.app.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/__init__.py", line 76, in run
:
    event_loop.run(interval)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
Traceback (most recent call last):
    item.func(now - item.last_ts, *item.args, **item.kwargs)  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

  File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 52, in update
    obj.on_update(dt)
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 96, in on_update
    super().on_update(dt)    self.run()
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 55, in on_update

  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self.shoot()
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 50, in shoot
    self._target(*self._args, **self._kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 41, in _thread_run
    self._play_shoot_sound()
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 29, in _play_shoot_sound
    self.run()    self.shooting_noise.play()

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 120, in run
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 216, in play
    filled = player.refill_buffer()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 238, in refill_buffer
    self._set_playing(True)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 168, in _set_playing
    self._refill(write_size)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 257, in _refill
    self._audio_player.prefill_audio()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 365, in prefill_audio
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._queue_audio_data(audio_data, length)
    self._update_play_cursor()  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 289, in _queue_audio_data

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 195, in _update_play_cursor
    self._update_write_cursor(audio_data, length)
    assert self._check_cursors()  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 296, in _update_write_cursor

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    assert self._check_cursors()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    assert self._buffer_cursor <= self._play_cursor
AssertionError    assert self._buffer_cursor <= self._play_cursor

AssertionError
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1
```

Am I doing something wrong or what's the problem?

**Comment by caffeinepills** [comment]
I am not sure as we haven't had anyone report this issue before. Is it possible your sounds are getting garbage collected? Make sure you are storing them in a list somewhere. Can you provide information through `python -m pyglet.info`

You can make them static sources through the resource loader: `plane_sound = pyglet.resource.media("plane.wav", streaming=False)` although your method should work just fine unless there is an issue.

**Comment by kitscribe** [comment]
@caffeinepills 

>  Is it possible your sounds are getting garbage collected? Make sure you are storing them in a list somewhere

I have all the resources stored in the `resources.py` file which is imported in the `main.py`

`resources.py`
```python
from code.utils import load_image_pair
import pyglet
import os

RESOURCES_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "../resources"))
pyglet.resource.path = [RESOURCES_PATH]
pyglet.resource.reindex()

plane_sound = pyglet.media.StaticSource(pyglet.resource.media("plane.wav"))
shooting_sound = pyglet.media.StaticSource(pyglet.resource.media("gun.wav"))

bullet_images = load_image_pair("bullet.png")
plane_images = [
    load_image_pair("airplane1.png"),
    load_image_pair("airplane2.png")
]
```
I tried to set the flag `streaming` to False and to save the pointer on the audio inside the instance of the `BasePlane` class, but it had no effect

`main.py`
```python
from code import plane, consts, resources
import pyglet

...
```

> Can you provide information through python -m pyglet.info
```
Platform
------------------------------------------------------------------------------
platform:  Linux-5.10.0-22-amd64-x86_64-with-glibc2.31
release:   5.10.0-22-amd64
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.10.10 (main, Apr 30 2023, 19:02:05) [GCC 10.2.1 20210110]
sys.maxint: 9223372036854775807
os.getcwd(): /home/kitscribe/projects/airplane_multiplayer

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.7
pyglet.compat_platform: linux
pyglet.__file__: /home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7f20e3f0db70>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f20e3f0db70>, x=0, y=0, width=1920, height=1080, xinerama=False)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: XlibContext(id=139779243548128, share=XlibContext(id=139779239897376, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 6)
gl_info.get_vendor(): AMD
gl_info.get_renderer(): AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.40.0, 5.10.0-22-amd64, LLVM 11.0.1)

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_multisample
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_libglvnd
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_INTEL_swap_event
glx_info.get_client_vendor(): Mesa Project and SGI
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_multithread_makecurrent
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync
glx_info.get_extensions():
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x7f20e3f0ec20>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg version: 4.3.6-0+deb11u1

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 55e0b4c46fd0 at 0x7f20e3f98820>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFT_device_clock
   ALC_SOFT_HRTF
   ALC_SOFT_loopback
   ALC_SOFT_output_limiter
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

### Here are few of my traceback with the description (including my debug printing)

1) The game stopped to play `plane_noise` sound, but continued executing `shootin_noise` (no crash)
```
Exception in thread Thread-1 (_thread_run):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 41, in _thread_run
    self.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 120, in run
    filled = player.refill_buffer()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 236, in refill_buffer
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._update_play_cursor()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 195, in _update_play_cursor
    assert self._check_cursors()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    assert self._buffer_cursor <= self._play_cursor
AssertionError
Player 1 hit enemy! Health left: 95.33970071803239
Player 1 hit enemy! Health left: 91.71045208151727
Player 1 hit enemy! Health left: 87.72954161739109
Player 1 hit enemy! Health left: 83.4485877098196
Player 1 hit enemy! Health left: 79.09632339036015
Player 1 hit enemy! Health left: 73.81404721727505
Player 0 hit enemy! Health left: 95.9748687495657
Player 0 hit enemy! Health left: 92.16158577694715
Player 1 hit enemy! Health left: 68.45389870355478
Player 1 hit enemy! Health left: 63.789797304250996
Player 1 hit enemy! Health left: 59.28246193533576
Player 1 hit enemy! Health left: 55.44969235058451
Player 0 hit enemy! Health left: 88.16906351929599
Player 0 hit enemy! Health left: 83.20554134165793
Player 0 hit enemy! Health left: 79.39283846757962
Player 0 hit enemy! Health left: 74.11918278272931
Player 0 hit enemy! Health left: 70.06429006181627
Player 0 hit enemy! Health left: 65.00652825394695
Player 0 hit enemy! Health left: 61.192051561339184
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 0
```

2) The game crashed
```
Traceback (most recent call last):
  File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 57, in <module>
    pyglet.app.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/__init__.py", line 76, in run
Exception in thread Thread-1 (_thread_run):
    event_loop.run(interval)Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.run()
    self.clock.call_scheduled_functions(dt)  File "/usr/local/lib/python3.10/threading.py", line 953, in run

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    self._target(*self._args, **self._kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 41, in _thread_run
    item.func(now - item.last_ts, *item.args, **item.kwargs)
      File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 52, in update
self.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 120, in run
    obj.on_update(dt)    filled = player.refill_buffer()

  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 96, in on_update
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 238, in refill_buffer
    super().on_update(dt)    self._refill(write_size)

  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 55, in on_update
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 257, in _refill
    self.shoot()    self._queue_audio_data(audio_data, length)
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 50, in shoot

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 289, in _queue_audio_data
    self._play_shoot_sound()    self._update_write_cursor(audio_data, length)
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 29, in _play_shoot_sound

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 296, in _update_write_cursor
    self.shooting_noise.play()    assert self._check_cursors()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 216, in play

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    self._set_playing(True)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 168, in _set_playing
    assert self._buffer_cursor <= self._play_cursor
AssertionError    self._audio_player.prefill_audio()

  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 365, in prefill_audio
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._update_play_cursor()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 195, in _update_play_cursor
    assert self._check_cursors()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 330, in _check_cursors
    assert self._buffer_cursor <= self._play_cursor
AssertionError
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1
```

3) Game crashed again, but with the different mistake
```
Traceback (most recent call last):
  File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 57, in <module>
    pyglet.app.run()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/__init__.py", line 76, in run
    event_loop.run(interval)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/kitscribe/projects/airplane_multiplayer/main.py", line 52, in update
    obj.on_update(dt)
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 96, in on_update
    super().on_update(dt)
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 55, in on_update
    self.shoot()
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 50, in shoot
    self._play_shoot_sound()
  File "/home/kitscribe/projects/airplane_multiplayer/code/plane.py", line 29, in _play_shoot_sound
    self.shooting_noise.play()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 216, in play
    self._set_playing(True)
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/player.py", line 168, in _set_playing
    self._audio_player.prefill_audio()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 365, in prefill_audio
    write_size = self._get_write_size()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 226, in _get_write_size
    self._update_play_cursor()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 188, in _update_play_cursor
    self._handle_processed_buffers()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 200, in _handle_processed_buffers
    processed = self.alsource.unqueue_buffers()
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/interface.py", line 250, in unqueue_buffers
    self._check_error('Failed to unqueue buffers from source.')
  File "/home/kitscribe/projects/airplane_multiplayer/env/lib/python3.10/site-packages/pyglet/media/drivers/openal/interface.py", line 37, in _check_error
    raise OpenALException(message=message,
pyglet.media.drivers.openal.interface.OpenALException: OpenAL Exception [40963: b'Invalid Value']: Failed to unqueue buffers from source.
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1
```

**Comment by caffeinepills** [comment]
I would try the latest version since the audio backend rework. If you still have issues, please open a new issue.
