### ISSUE TITLE
Erratic error: pyglet.gl.lib.GLException: (0x1281): Invalid value. A numeric argument is out of range.

### ISSUE THREAD

**Issue by jej** [pyglet/pyglet#858]
I am struggling with an erratic error. I get it when playing a video. I tried different format, mp4, m4v but seems not related to the video itself. The video plays well, following the doc example. But after some restart of the app, it fails. If I reboot the computer or unplug/replug the external monitor, the error generally goes away. But it appears again later, even if I modify other parts of the app not related to the player. I got some opengl errors during the early dev of my app but it was always my fault. Here I don't have any idea why this error appears randomly.

The trace:
```
Traceback (most recent call last):
  File "/home/user/src/app/./myapp.py", line 262, in <module>
    Application().run()
  File "/home/user/src/app/./myapp.py", line 115, in run
    pyglet.app.run()
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/app/__init__.py", line 76, in run
    event_loop.run(interval)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/media/player.py", line 460, in update_texture
    self._texture.blit_into(image, 0, 0, 0)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/image/__init__.py", line 1469, in blit_into
    self.owner.blit_into(source, x + self.x, y + self.y, z + self.z)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/image/__init__.py", line 1364, in blit_into
    source.blit_to_texture(self.target, self.level, x, y, z)
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/image/__init__.py", line 823, in blit_to_texture
    glTexSubImage2D(target, level,
  File "/home/user/src/venv/lib/python3.10/site-packages/pyglet/gl/lib.py", line 79, in errcheck
    raise GLException(f'(0x{error}): {msg}')
pyglet.gl.lib.GLException: (0x1281): Invalid value. A numeric argument is out of range.
AL lib: (EE) alc_cleanup: 1 device not closed
```

[pyglet info](https://pastebin.com/ugeZXzN4)

I spent hours on this, now I don't have any more ideas...

Thanks for your help.

**Comment by caffeinepills** [comment]
Is this happening with one source or different sources? Can you provide a source that is causing the error? I do see you are using ffmpeg 4.3. I would suggest upgrading to ffmpeg 4.4 or 5.x if possible.

**Comment by jej** [comment]
Hey, thanks for your quick reply.

Different sources same problem (a mpeg from a camera, a youtube rip, a video converted with handbrake...). Does not seems related to the video itself.

I will try the ffmpeg upgrade as you say.

I think something is improving the situation... I reverted to previous commits, trying to revert each modifications I did step by step. Because before the video player integration, it was working smoothly.

Maybe this line is involved:
```
from pyglet.media import Player, load
```
I like to import just the minimum. But I changed to:
```
import pyglet
```
and in my code
```
        self.player = pyglet.media.Player()
        source = pyglet.media.load(config.path.project + '/' + self.src)
```
instead of ` self.player = Player()`, etc.

Maybe the `import.media` is running some code during import, disturbing the context? Is this possible? My app has up to 3 windows opened, different contents are displayed on each. I checked carefully that gfx operations are done on the good context...

**Comment by benmoran56** [comment]
Yes, importing the media module does cause it to initialize the audio driver interface. If you only import pyglet, then other modules are behind a lazy loading proxy.

**Comment by jej** [comment]
So I should avoid this kind of practice?
```
from pyglet import image
from pyglet.image import ImageData, AbstractImage
from pyglet.shapes import BorderedRectangle, Polygon, Rectangle, Triangle
from pyglet.text import Label
from pyglet import sprite
```

**Comment by benmoran56** [comment]
Only if you're having issues, which is much more common with multiple windows. 
For typical single window applications it doesn't really matter.

**Comment by jej** [comment]
Ok then. I had some weird think, so it's better if I clean that now...

Thanks you both for your help.

**Comment by jej** [comment]
Well, still very embarrassed... Is it possible that the player (running in it's thread if I understand well), generates the video frame texture in a different context that the context I display to?

**Comment by pushfoo** [comment]
> Is it possible that the player (running in it's thread if I understand well), generates the video frame texture in a different context that the context I display to?

1. Can you log the information for the contexts used during texture creation and display to compare them?
2. What OS & version are you on?
3. If you're on Linux, which display server + DE are you on?
4. What GPU(s) do you have?

I think I once read about multi-GPU setups having strange issues with memory or drawing contexts on some operating systems, especially across monitors plugged into different GPUs. If nobody else has better advice, then you may want to investigate this.

**Comment by jej** [comment]
> Can you log the information for the contexts used during texture creation and display to compare them?

Is there a pyglet way to do that? or I just create a function to display window.context and gfx objects context?

> multi-GPU setups having strange issues with memory or drawing contexts on some operating systems

I have a dell laptop with integrated gpu. I use external monitor but the problem is the same with integrated screen.

Thanks.

**Comment by jej** [comment]
Well, it's going worst, grrrrr....

Here is a description of my app. There are 2 windows: Script and Projector. Script displays some content, take keyboard events and order Projector to display some different content when key hit. I carefully checked that the objects are created in the context they are displayed.

I monitored the `switch_to()` by overloading:
```
class GenericWindow(pyglet.window.Window):
    def switch_to(self):
        stack = inspect.stack()[1]
        print("switch_to:", self.__class__, self.context, "caller:", stack.filename, stack.lineno, stack.function)
        try:
            print('player:', config.app.player, "texture context:", config.app.player.texture._context)
        except:
            pass
        super().switch_to()
```
This log information about switching:
```
switch_to: <class 'projector.ProjectorWindow'> XlibContext(id=139868168355696, share=None) caller: /home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/app/base.py 117 _redraw_windows
switch_to: <class 'script.ScriptWindow'> XlibContext(id=139869174240768, share=None) caller: /home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/app/base.py 117 _redraw_windows
Key hit...
switch_to: <class 'projector.ProjectorWindow'> XlibContext(id=139868168355696, share=None) caller: /home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/app/base.py 117 _redraw_windows
Here, load media, and the player queue + play
switch_to: <class 'script.ScriptWindow'> XlibContext(id=139869174240768, share=None) caller: /home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/app/base.py 117 _redraw_windows
player: <pyglet.media.player.Player object at 0x7f35994d1210> texture context: XlibContext(id=139868168355696, share=None)
```
Here is the current code involving the player (but a lot of modifications never changed anything...):
```
    def before_transition_event(self):
        print("Here, load media, and the player queue + play")
        config.app.player = pyglet.media.Player()
        source = pyglet.media.load(config.path.project + '/' + self.src)
        config.app.player.queue(source)
        config.app.player.play()
```
It seems according to the log that the player is well created in Projector context and displayed also in its context.

And as usual I get the erratic error. The debug log slow down the app and it works most of the time. If I remove it, app runs at full speed and fails most of the time.

I am worry about the non-reproducibility of this bug, it leaves me few chances to go further...

**Comment by jej** [comment]
> Can you provide a source that is causing the error?

@caffeinepills
Here it is: https://send.papamica.fr/f.php?h=3wcPMzkH

**Comment by jej** [comment]
Another error I see sometime when the app quits is:
```
Exception ignored in: <function OpenALDriver.__del__ at 0x7f42b2d09c60>
Traceback (most recent call last):
  File "/home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
  File "/home/user/app/python-app/src/venv/lib/python3.10/site-packages/pyglet/media/mediathreads.py", line 59, in stop
    self._thread.join()
  File "/usr/local/lib/python3.10/threading.py", line 1093, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

Sometime:
```
AL lib: (EE) alc_cleanup: 1 device not closed
```

May it helps...

**Comment by jej** [comment]
Another information: I launched the app more than 10 times outside vscode debugger, it never failed. Back to vscodium, failed again (I get the same errors when quitting, see above).

So I guess the debugger is involved here... Do you have any information about that? Any advice? `pyglet.options` tricks that could help?

Thanks.

Common launch config...
```
        {
            "name": "Standalone",
            "type": "python",
            "request": "launch",
            "program": "myapp.py",
            "console": "integratedTerminal", 
            "justMyCode": true,
            "args": [
                "--project",
                "../project-sample"
            ]
        },
```

**Comment by jej** [comment]
After some investigation in the lazy loading and @benmoran56  comment about modules loading:
```
TYPE_CHECKING = True
```
before importing pyglet solves the problem to run the app in vscod/ium... No more lazy load and no more error.

Code involved: https://github.com/pyglet/pyglet/blob/f10c4d2bad103d0370f3700c1cd9071a2f3fccfd/pyglet/__init__.py#L333-L374

Does anybody got this problem already? What to do?

**Comment by jej** [comment]
Hi all,

Here is how I can reproduce the bug systematically with the media_player example: https://github.com/pyglet/pyglet/compare/master...jej:pyglet:bug-858-mediaplayer-example

You can checkout this branch to try it: https://github.com/jej/pyglet/tree/bug-858-mediaplayer-example

Launch it: `./media_player.py myvideo.mp4`

If the bug does not appear directly, move the `winbug` black window around. I get this error immediately:
```
Traceback (most recent call last):
  File "./pyglet/examples/media/./media_player.py", line 449, in <module>
    main(target_file, dbg_file, debug)
  File "./pyglet/examples/media/./media_player.py", line 395, in main
    pyglet.app.run()
  File "./pyglet/pyglet/app/__init__.py", line 76, in run
    event_loop.run(interval)
  File "./pyglet/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
              ^^^^^^^^^^^
  File "./pyglet/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "./pyglet/pyglet/clock.py", line 226, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "./pyglet/pyglet/media/player.py", line 460, in update_texture
    self._texture.blit_into(image, 0, 0, 0)
  File "./pyglet/pyglet/image/__init__.py", line 1469, in blit_into
    self.owner.blit_into(source, x + self.x, y + self.y, z + self.z)
  File "./pyglet/pyglet/image/__init__.py", line 1364, in blit_into
    source.blit_to_texture(self.target, self.level, x, y, z)
  File "./pyglet/pyglet/image/__init__.py", line 823, in blit_to_texture
    glTexSubImage2D(target, level,
  File "./pyglet/pyglet/gl/lib.py", line 79, in errcheck
    raise GLException(f'(0x{error}): {msg}')
pyglet.gl.lib.GLException: (0x1282): Invalid operation. The specified operation is not allowed in the current state.
AL lib: (EE) alc_cleanup: 1 device not closed
```

Then checkout the player fix: https://github.com/jej/pyglet/tree/fix-video-player-context

Run again, it should work.

Is it a misuse of me, or a misunderstanding of context, or hardware issue on my side?


@benmoran56 @caffeinepills @pushfoo

**Comment by matanox** [comment]
Was it really a matter of pyglet module loading order when loading `pyglet.media.Player()`?
Or just that pyglet.media.Player should not be run on a thread?

**Comment by caffeinepills** [comment]
Closing as this jej's fix was PR'd
