### ISSUE TITLE
AttributeError's are suppressed in 1.4.6+

### ISSUE THREAD

**Issue by Torxed** [pyglet/pyglet#87]
To demonstrate the issue, below is an [executable code](https://gist.github.com/Torxed/c82ff9ca710cf0cb108497f215d53ab4) snippet.

The problem appears to be (in `event.py`):

```python
        except AttributeError:
            pass
```

Commenting it out produces:
```
  File "C:\Python36\lib\site-packages\pyglet\event.py", line 423, in dispatch_event
    if getattr(self, event_type)(*args):
AttributeError: 'UnformattedDocument' object has no attribute 'on_insert_text'
```

Usually, I'm used to getting out the different errors and pyglet crashing, which is more of a desired behavior unless it's internal stuff ofcourse, like some of my more experimental codes I'm used to getting:

```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    W = window()
  File "test.py", line 50, in __init__
    self.add_sprite('smilyface', smilyface(debug=True, x=100, y=100, width=20, height=20, alpha=0))
  File "test.py", line 16, in __init__
    super(smilyface, self).__init__(*args, **kwargs)
  File "/home/anton/github/pyglet2d/pyglet_gui.py", line 222, in __init__
    ImageObject.__init__(self, texture, *args, **kwargs)
  File "/home/anton/github/pyglet2d/pyglet_gui.py", line 167, in __init__
    self.batch = kwargs['batch']
  File "/usr/lib/python3.7/site-packages/pyglet/sprite.py", line 322, in batch
    self._create_vertex_list()
  File "/usr/lib/python3.7/site-packages/pyglet/sprite.py", line 401, in _create_vertex_list
    4, GL_QUADS, self._group, vertex_format, 'c4B', ('t3f', self._texture.tex_coords))
AttributeError: 'NoneType' object has no attribute 'tex_coords'
```

And I quite like it, but Pyglet still handles all the internal errors pretty well.
Below is the code example.

```python
import pyglet
from math import *

key = pyglet.window.key
tile_width_half = 84/2
tile_height_half = 51/2

class Tile(pyglet.sprite.Sprite):
	def __init__(self, width=84, height=51, image='path.png', *args, **kwargs):
		self.texture = pyglet.image.load(image)
		pyglet.sprite.Sprite.__init__(self, self.texture, **kwargs)

class mathtile():
	def __init__(self, x=42, y=25, width=84, height=51):
		self.max_x = x + (width/2)
		self.max_y = y + (height/2)
		self.min_x = x - self.max_x
		self.min_y = y - self.max_y

	def __repr__(self):
		return f'Tile: x,y: {self.x}x{self.y} w,h: {self.width}x{self.height}'

class Game(pyglet.window.Window):
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.tile = Tile(image='path_mouse.png')

	def on_mouse_motion(self, x, y, dx, dy):
		mouse_relative_x = x % self.tile.width
		mouse_relative_y = y % self.tile.height

		tile = mathtile(self.tile.x, self.tile.y, self.tile.width, self.tile.height)
		print('Moo:')
		print(tile)
		print('What the hell?')

	def on_draw(self):
		self.clear()
		self.tile.draw()

	def on_key_press(self, symbol, modifiers):
		if symbol == key.ESCAPE:
			pyglet.app.exit()
	def on_key_release(self, symbol, modifiers):
		pass
	def update(self,dt):
		pass

if __name__ == '__main__':
	game = Game(800,600,"title")
	pyglet.clock.schedule_interval(game.update,1/60)

	pyglet.app.run()
```

**Comment by benmoran56** [comment]
Something like this seems to work: 

```python

        # Check instance for an event handler
        func = getattr(self, event_type, None)
        if func:
            try:
                return func(*args)
            except Exception as e:
                self._raise_dispatch_exception(event_type, args, getattr(self, event_type), e)
                return EVENT_UNHANDLED

        return False
```

I'm not sure if there will be any side effects yet, but it seems to do the trick.

**Comment by benmoran56** [comment]
PR merged!  

It might be a good idea to backport to 1.4 branch as well. Do you think you can make another PR, based off of the pyglet-1.4-maintenace branch?  I can get it pushed out with the next point release.

**Comment by Torxed** [comment]
I fix :)

**Comment by benmoran56** [comment]
Today I was manually merging in other changes, so I did this as well. The new code will be in v2.0, as well as the upcoming v1.4.7 release. Thanks again!

**Comment by pvcraven** [comment]
I'm still getting the same or a similar issue. I posted in Issue #105.
