### ISSUE TITLE
Bad recognition of opengl version?

### ISSUE THREAD

**Issue by vinniec** [pyglet/pyglet#969]
**Describe the bug**
pyglet is not working due to problems with opengl version.
pyglet.info says 1.1.0  however on my system it appears that gl 2.1.0 is installed.
I have an intel integrated video card on which unfortunately I cannot download drivers outside of those that windows installs (another strange thigs is that pyglet.info says that I have windows 10, but I have win 11).

One solution might be to install mesa3d as suggested by the [opengl site](https://www.khronos.org/opengl/wiki/Getting_Started#Downloading_OpenGL):
> **Without drivers, you will default to a software version of OpenGL 1.1** (on Win98, ME, and 2000), **a Direct3D wrapper that supports OpenGL 1.1** (WinXP), or a Direct3D wrapper that supports OpenGL 1.1 (Windows Vista and Windows 7). None of these options are particularly fast, so installing drivers is always a good idea.
> If your system does not contain a GPU, or the GPU vendor delivers graphics drivers providing OpenGL support that's so old as to be useless to you, you might want to consider installing the Mesa3D OpenGL library on your system. 

However, I did not want to do this for two reasons:
1) I have to compile it ([or maybe not](https://github.com/pal1000/mesa-dist-win))
2) However, my pc seems to have support for opengl 2.1.0 so I don't want to mess up.
I'm more under the impression that for some strange reason pyglet thinks there is no opengl as stated in the part I bolded on the previous opengl site quote.

P.s. I just wanted to report the bug, I never used pyglet, just wanted to try it, so I have no knowledge about it.

**System Information:**
```
Platform
------------------------------------------------------------------------------
platform:  Windows-10-10.0.22000-SP0
release:   10
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): C:\Users\*******

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.9
pyglet.compat_platform: win32
pyglet.__file__: C:\Python311\Lib\site-packages\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
Insufficient OpenGL version: 1.1.0

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.xaudio2.adaptation.XAudio2Driver object at 0x000001FDA1398050>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'openal32', handle 10000000 at 0x1fda4e32810>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_EFX

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab: Wintab Digitizer Services 1.39 (Spec 1.4)
```

**How To Reproduce**
```python
import pyglet
window = pyglet.window.Window()
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\pyglet\window\win32\__init__.py", line 104, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Python311\Lib\site-packages\pyglet\window\__init__.py", line 582, in __init__
    self._create_projection()
  File "C:\Python311\Lib\site-packages\pyglet\window\__init__.py", line 590, in _create_projection
    shader.Shader(self._default_vertex_source, 'vertex'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyglet\graphics\shader.py", line 699, in __init__
    shader_id = glCreateShader(shader_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyglet\gl\lib_wgl.py", line 66, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyglet\gl\lib.py", line 25, in MissingFunction
    raise MissingFunctionException(name, requires, suggestions)
pyglet.gl.lib.MissingFunctionException: glCreateShader is not exported by the available OpenGL driver.  OpenGL 2.0 is required for this functionality.
```

**Comment by vinniec** [comment]
I tried those binary versions of mesa3d that I had mentioned because it includes a driver install batch only per one application and I tried pointing to a python.exe of a portable editor called thonny.
It still doesn't work however the error has changed, meaning that indeed the access to the libraries has changed.

```
Traceback (most recent call last):
  File "G:\fla\thonny\lib\site-packages\pyglet\__init__.py", line 306, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\fla\lavori\programmazione\pyglet_helloworld.py", line 2, in <module>
    window = pyglet.window.Window()
  File "G:\fla\thonny\lib\site-packages\pyglet\__init__.py", line 312, in __getattr__
    __import__(import_name)
  File "G:\fla\thonny\lib\site-packages\pyglet\window\__init__.py", line 1901, in <module>
    gl._create_shadow_window()
  File "G:\fla\thonny\lib\site-packages\pyglet\gl\__init__.py", line 165, in _create_shadow_window
    _shadow_window = ShadowWindow()
  File "G:\fla\thonny\lib\site-packages\pyglet\gl\__init__.py", line 159, in __init__
    super().__init__(width=1, height=1, visible=False)
  File "G:\fla\thonny\lib\site-packages\pyglet\window\win32\__init__.py", line 104, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "G:\fla\thonny\lib\site-packages\pyglet\window\__init__.py", line 523, in __init__
    config = screen.get_best_config(template_config)
  File "G:\fla\thonny\lib\site-packages\pyglet\canvas\base.py", line 162, in get_best_config
    configs = self.get_matching_configs(template)
  File "G:\fla\thonny\lib\site-packages\pyglet\canvas\win32.py", line 36, in get_matching_configs
    configs = template.match(canvas)
  File "G:\fla\thonny\lib\site-packages\pyglet\gl\win32.py", line 24, in match
    return self._get_pixel_format_descriptor_matching_configs(canvas)
  File "G:\fla\thonny\lib\site-packages\pyglet\gl\win32.py", line 67, in _get_pixel_format_descriptor_matching_configs
    pf = _gdi32.ChoosePixelFormat(canvas.hdc, byref(pfd))
OSError: exception: access violation writing 0x0000000000000024
```

**Comment by benmoran56** [comment]
Hi, thanks for opening the ticket. 

The pyglet 2.0+ series requires OpenGL 3.3, but you can still install the 1.5 series release. The latest being 1.5.27. EX:
```py
pip install --user pyglet==1.5.27
```
Give that a try, and see if it works for you. 

Regarding the platform, that's actually correct. The internal platform code for Windows 11 (21H2) is 10.0.22000. 
Essentially we're just displaying the output of:
```py
import platform
platform.platform()
```

**Comment by vinniec** [comment]
Yep, this version work :)
Thanks

**Comment by benmoran56** [comment]
Closing as completed.

Also, there is a new v1.5.28 just released. You may want upgrade to that as it contains many bug fixes.
