### ISSUE TITLE
Source zipfile differs on github and pypi; pypi version contains incorrect pyproject.toml

### ISSUE THREAD

**Issue by heerener** [pyglet/pyglet#999]
**Describe the bug**
The source zipfile downloaded from pypi differs from the one downloaded from github - diff attached: [github-to-pypi.txt](https://github.com/pyglet/pyglet/files/13416745/github-to-pypi.txt)

My main issue is with the pyproject.toml file that's present only in the pypi zipfile. Trying to `pip install -e .` leads to:

```
Processing /home/heeren/Downloads/pyglet-2.0.10                                                                                                                                                               
  Installing build dependencies ... done                                                               
  ERROR: Error expected str, bytes or os.PathLike object, not list while executing command Getting requirements to build wheel                                                                                
  Getting requirements to build wheel ... error                                                        
ERROR: Exception:                                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                            
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper                                                                         
    status = run_func(*args)                                                                                                                                                                                  
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper                                                                                      
    return func(self, options, args)                                                                                                                                                                          
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run                                                                                         
    requirement_set = resolver.resolve(                                                                
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve                                                                        
    collected = self.factory.collect_root_requirements(root_reqs)                                      
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 513, in collect_root_requirements                                                      
    reqs = list(                                                                                       
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 474, in _make_requirements_from_install_req                                            
    cand = self._make_candidate_from_link(                                                             
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link                                                      
    self._link_candidate_cache[link] = LinkCandidate(                                                  
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__                                                                    
    super().__init__(       
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__                                                                    
    self.dist = self._prepare()                                                                                                                                                                               
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare                                                                    
    dist = self._prepare_distribution()                                                                                                                                                                       
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution                                                       
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)                       
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)                                      
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement                                                               
    dist = _get_prepared_distribution(
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution                                                                
    abstract_dist.prepare_distribution_metadata(
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 751, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/home/heeren/Downloads/venv/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1783, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/lib/python3.10/os.py", line 811, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not list
```

The issue is with `build-backend = ["flit_core.buildapi", "flit_core.wheel"]`, which is supposed to be a string. `"flit_core.buildapi"` works, `"flit_core.wheel"` doesn't, so I assume you'll want the first.

Expected behaviour: both zipfiles are the same and install correctly.

**System Information:**
Ubuntu 22.04
Quadro P2000

**Additional question:** 
Out of sheer curiosity: where is the pyproject.toml file generated?

**Comment by benmoran56** [comment]
Thanks for opening the ticket.

That pyproject.toml is actually just a test file sitting on one of my personal machines. We're building our zip with `python setup.py sdist --formats=zip`, which is (unintentionally) pulling that file in. I'll remove it so that it's not in the next point release. 

As for the source of the file, it was a quick test from a while ago. This ticket might be a good reminder to finish migrating from setup.py

**Comment by benmoran56** [comment]
Rather than remove it, I went ahead and updated the pyproject.toml file so it should work correctly now.
In keeping up with modern Python packaging standards, we'll probably retire the setup.py in pyglet 2.1.

**Comment by heerener** [comment]
Awesome! Good luck with the conversion, though it seems like it's mostly done :-)

Do you have an estimation (vague or not) on when the next point release would be?

**Comment by benmoran56** [comment]
We just merged major `media` module cleanups into master, so it might be a short while. This needs to be tested thoroughly.

**Comment by unitof** [comment]
Would you consider applying these changes (fixing the `pyproject.toml` syntax & defining `__version__` in `__init__.py`) in a patch update to 1.5? I am happy submit a PR, branching off https://github.com/pyglet/pyglet/tree/v1.5.28.

I am working on [a Homebrew formula for manim](https://github.com/Homebrew/homebrew-core/pull/166434), and manim depends on `pyglet = ">=1.5.8,<2"`. This bug has been causing me build errors I'm very happy to have finally resolved today, thanks to finally googling upon this issue!

However I'd love to get rid of my [clumsy `inreplace` patches](https://github.com/unitof/homebrew-core/blob/bac7431657ccb0e07001f4a86d338f330211d482/Formula/m/manim.rb#L193-L199) and instead just require an upstream v1.5.29.

**Comment by unitof** [comment]
Update: manim now depends on `pyglet = ">=2.0dev23"`, my bad. All set!

**Comment by benmoran56** [comment]
Great, glad that was easy enough. This ticket itself can probably be closed now, because the `pyproject.toml` has been in place for a few releases now. Please do follow up if you have any other issues.
